var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=(a,b)=>{throw b;},ca="",da;"undefined"!=typeof document&&document.currentScript&&(ca=document.currentScript.src);ca=0!==ca.indexOf("blob:")?ca.substr(0,ca.replace(/[?#].*/,"").lastIndexOf("/")+1):"";da=a=>{document.title=a};var ea=g.print||console.log.bind(console),k=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.quit&&(ba=g.quit);var fa;g.wasmBinary&&(fa=g.wasmBinary);
var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&l("no native wasm support detected");var ha,m,p=!1,ia,r,v,ja,ka,x,y,z,la,A;function ma(){var a=ha.buffer;g.HEAP8=r=new Int8Array(a);g.HEAP16=ja=new Int16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU8=v=new Uint8Array(a);g.HEAPU16=ka=new Uint16Array(a);g.HEAPU32=y=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=A=new Float64Array(a);g.HEAP64=la=new BigInt64Array(a);g.HEAPU64=new BigUint64Array(a)}
var na=[],oa=[],pa=[],qa=[],ra=[];function sa(){var a=g.preRun.shift();na.unshift(a)}var ta=0,ua=null,va=null;function l(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";k(a);p=!0;ia=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function wa(a){return a.startsWith("data:application/octet-stream;base64,")}var xa;xa="index.wasm";if(!wa(xa)){var ya=xa;xa=g.locateFile?g.locateFile(ya,ca):ca+ya}
function za(a){if(a==xa&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}function Aa(a){return fa||"function"!=typeof fetch?Promise.resolve().then(()=>za(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>za(a))}function Ba(a,b,c){return Aa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{k("failed to asynchronously prepare wasm: "+d);l(d)})}
function Ca(a,b){var c=xa;fa||"function"!=typeof WebAssembly.instantiateStreaming||wa(c)||"function"!=typeof fetch?Ba(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k("wasm streaming compile failed: "+e);k("falling back to ArrayBuffer instantiation");return Ba(c,a,b)}))}function Da(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ea=a=>{for(;0<a.length;)a.shift()(g)},Fa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,B=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d},Ga=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},D=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=
240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},Ha=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ia=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ha(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ja=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=
b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ka=a=>{if("/"===a)return"/";a=Ia(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},La=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);l("initRandomDevice")},Ma=a=>(Ma=La())(a);
function Na(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ha(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var Oa=[],Pa=[];function Qa(a,b){Pa[a]={input:[],he:[],se:b};Ra(a,Sa)}
var Sa={open:function(a){var b=Pa[a.node.Me];if(!b)throw new E(43);a.ie=b;a.seekable=!1},close:function(a){a.ie.se.De(a.ie)},De:function(a){a.ie.se.De(a.ie)},read:function(a,b,c,d){if(!a.ie||!a.ie.se.cf)throw new E(60);for(var e=0,f=0;f<d;f++){try{var h=a.ie.se.cf(a.ie)}catch(n){throw new E(29);}if(void 0===h&&0===e)throw new E(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.ie||!a.ie.se.Ve)throw new E(60);try{for(var e=0;e<d;e++)a.ie.se.Ve(a.ie,
b[c+e])}catch(f){throw new E(29);}d&&(a.node.timestamp=Date.now());return e}},Ta={cf:function(){a:{if(!Oa.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Ga(a)+1);a=D(a,b,0,b.length);b.length=a;Oa=b}b=Oa.shift()}return b},Ve:function(a,b){null===b||10===b?(ea(B(a.he,0)),a.he=[]):0!=b&&a.he.push(b)},De:function(a){a.he&&0<
a.he.length&&(ea(B(a.he,0)),a.he=[])},gg:function(){return{Wf:25856,Yf:5,Vf:191,Xf:35387,Uf:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},hg:function(){return 0},ig:function(){return[24,80]}},Ua={Ve:function(a,b){null===b||10===b?(k(B(a.he,0)),a.he=[]):0!=b&&a.he.push(b)},De:function(a){a.he&&0<a.he.length&&(k(B(a.he,0)),a.he=[])}};
function Va(a,b){var c=a.Td?a.Td.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Td,a.Td=new Uint8Array(b),0<a.ge&&a.Td.set(c.subarray(0,a.ge),0))}
var F={je:null,me(){return F.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new E(63);F.je||(F.je={dir:{node:{ne:F.ee.ne,ke:F.ee.ke,we:F.ee.we,Je:F.ee.Je,kf:F.ee.kf,tf:F.ee.tf,lf:F.ee.lf,jf:F.ee.jf,Oe:F.ee.Oe},stream:{qe:F.fe.qe}},file:{node:{ne:F.ee.ne,ke:F.ee.ke},stream:{qe:F.fe.qe,read:F.fe.read,write:F.fe.write,Ye:F.fe.Ye,ef:F.fe.ef,gf:F.fe.gf}},link:{node:{ne:F.ee.ne,ke:F.ee.ke,xe:F.ee.xe},stream:{}},Ze:{node:{ne:F.ee.ne,ke:F.ee.ke},stream:Wa}});
c=Xa(a,b,c,d);16384===(c.mode&61440)?(c.ee=F.je.dir.node,c.fe=F.je.dir.stream,c.Td={}):32768===(c.mode&61440)?(c.ee=F.je.file.node,c.fe=F.je.file.stream,c.ge=0,c.Td=null):40960===(c.mode&61440)?(c.ee=F.je.link.node,c.fe=F.je.link.stream):8192===(c.mode&61440)&&(c.ee=F.je.Ze.node,c.fe=F.je.Ze.stream);c.timestamp=Date.now();a&&(a.Td[b]=c,a.timestamp=c.timestamp);return c},dg(a){return a.Td?a.Td.subarray?a.Td.subarray(0,a.ge):new Uint8Array(a.Td):new Uint8Array(0)},ee:{ne(a){var b={};b.ag=8192===(a.mode&
61440)?a.id:1;b.fg=a.id;b.mode=a.mode;b.ng=1;b.uid=0;b.eg=0;b.Me=a.Me;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ge:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Qf=new Date(a.timestamp);b.lg=new Date(a.timestamp);b.$f=new Date(a.timestamp);b.xf=4096;b.Sf=Math.ceil(b.size/b.xf);return b},ke(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.ge!=b))if(0==b)a.Td=null,a.ge=0;else{var c=a.Td;a.Td=new Uint8Array(b);
c&&a.Td.set(c.subarray(0,Math.min(b,a.ge)));a.ge=b}},we(){throw Ya[44];},Je(a,b,c,d){return F.createNode(a,b,c,d)},kf(a,b,c){if(16384===(a.mode&61440)){try{var d=Za(b,c)}catch(f){}if(d)for(var e in d.Td)throw new E(55);}delete a.parent.Td[a.name];a.parent.timestamp=Date.now();a.name=c;b.Td[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},tf(a,b){delete a.Td[b];a.timestamp=Date.now()},lf(a,b){var c=Za(a,b),d;for(d in c.Td)throw new E(55);delete a.Td[b];a.timestamp=Date.now()},jf(a){var b=[".",".."],
c;for(c in a.Td)a.Td.hasOwnProperty(c)&&b.push(c);return b},Oe(a,b,c){a=F.createNode(a,b,41471,0);a.link=c;return a},xe(a){if(40960!==(a.mode&61440))throw new E(28);return a.link}},fe:{read(a,b,c,d,e){var f=a.node.Td;if(e>=a.node.ge)return 0;a=Math.min(a.node.ge-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===r.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Td||a.Td.subarray)){if(f)return a.Td=
b.subarray(c,c+d),a.ge=d;if(0===a.ge&&0===e)return a.Td=b.slice(c,c+d),a.ge=d;if(e+d<=a.ge)return a.Td.set(b.subarray(c,c+d),e),d}Va(a,e+d);if(a.Td.subarray&&b.subarray)a.Td.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Td[e+f]=b[c+f];a.ge=Math.max(a.ge,e+d);return d},qe(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ge);if(0>b)throw new E(28);return b},Ye(a,b,c){Va(a.node,b+c);a.node.ge=Math.max(a.node.ge,b+c)},ef(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new E(43);
a=a.node.Td;if(e&2||a.buffer!==r.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;l();b=void 0;if(!b)throw new E(48);r.set(a,b)}else c=!1,b=a.byteOffset;return{rg:b,Nf:c}},gf(a,b,c,d){F.fe.write(a,b,0,d,c,!1);return 0}}},$a=g.preloadPlugins||[];function ab(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var bb=null,cb={},db=[],eb=1,fb=null,gb=!0,E=null,Ya={},ib=(a,b={})=>{a=Na(a);if(!a)return{path:"",node:null};b=Object.assign({af:!0,We:0},b);if(8<b.We)throw new E(32);a=a.split("/").filter(h=>!!h);for(var c=bb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Za(c,a[e]);d=Ia(d+"/"+a[e]);c.Ke&&(!f||f&&b.af)&&(c=c.Ke.root);if(!f||b.$e)for(f=0;40960===(c.mode&61440);)if(c=hb(d),d=Na(Ja(d),c),c=ib(d,{We:b.We+1}).node,40<f++)throw new E(32);}return{path:d,node:c}},jb=a=>{for(var b;;){if(a===
a.parent)return a=a.me.ff,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},kb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%fb.length},Za=(a,b)=>{var c;if(c=(c=lb(a,"x"))?c:a.ee.we?0:2)throw new E(c,a);for(c=fb[kb(a.id,b)];c;c=c.Gf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ee.we(a,b)},Xa=(a,b,c,d)=>{a=new mb(a,b,c,d);b=kb(a.parent.id,a.name);a.Gf=fb[b];return fb[b]=a},nb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+=
"w");return b},lb=(a,b)=>{if(gb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},ob=(a,b)=>{try{return Za(a,b),20}catch(c){}return lb(a,"wx")},pb=()=>{for(var a=0;4096>=a;a++)if(!db[a])return a;throw new E(33);},qb=a=>{a=db[a];if(!a)throw new E(8);return a},sb=a=>{var b=-1;rb||(rb=function(){this.oe={}},rb.prototype={},Object.defineProperties(rb.prototype,{object:{get(){return this.node},set(c){this.node=c}},
flags:{get(){return this.oe.flags},set(c){this.oe.flags=c}},position:{get(){return this.oe.position},set(c){this.oe.position=c}}}));a=Object.assign(new rb,a);-1==b&&(b=pb());a.fd=b;return db[b]=a},Wa={open:a=>{a.fe=cb[a.node.Me].fe;a.fe.open&&a.fe.open(a)},qe:()=>{throw new E(70);}},Ra=(a,b)=>{cb[a]={fe:b}},tb=(a,b)=>{var c="/"===b,d=!b;if(c&&bb)throw new E(10);if(!c&&!d){var e=ib(b,{af:!1});b=e.path;e=e.node;if(e.Ke)throw new E(10);if(16384!==(e.mode&61440))throw new E(54);}b={type:a,qg:{},ff:b,
Ff:[]};a=a.me(b);a.me=b;b.root=a;c?bb=a:e&&(e.Ke=b,e.me&&e.me.Ff.push(b))},G=(a,b,c)=>{var d=ib(a,{parent:!0}).node;a=Ka(a);if(!a||"."===a||".."===a)throw new E(28);var e=ob(d,a);if(e)throw new E(e);if(!d.ee.Je)throw new E(63);return d.ee.Je(d,a,b,c)},ub=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);G(a,b|8192,c)},vb=(a,b)=>{if(!Na(a))throw new E(44);var c=ib(b,{parent:!0}).node;if(!c)throw new E(44);b=Ka(b);var d=ob(c,b);if(d)throw new E(d);if(!c.ee.Oe)throw new E(63);c.ee.Oe(c,b,a)},hb=a=>{a=ib(a).node;
if(!a)throw new E(44);if(!a.ee.xe)throw new E(28);return Na(jb(a.parent),a.ee.xe(a))},xb=(a,b,c)=>{if(""===a)throw new E(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ia(a);try{e=ib(a,{$e:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new E(20);}else e=G(a,c,0),d=!0;if(!e)throw new E(44);
8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new E(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==nb(b)||b&512)?31:lb(e,nb(b)):44))throw new E(c);if(b&512&&!d){c=e;c="string"==typeof c?ib(c,{$e:!0}).node:c;if(!c.ee.ke)throw new E(63);if(16384===(c.mode&61440))throw new E(31);if(32768!==(c.mode&61440))throw new E(28);if(d=lb(c,"w"))throw new E(d);c.ee.ke(c,{size:0,timestamp:Date.now()})}b&=-131713;e=sb({node:e,path:jb(e),flags:b,seekable:!0,position:0,
fe:e.fe,Kf:[],error:!1});e.fe.open&&e.fe.open(e);!g.logReadFiles||b&1||(wb||(wb={}),a in wb||(wb[a]=1));return e},yb=a=>{if(null===a.fd)throw new E(8);a.Ue&&(a.Ue=null);try{a.fe.close&&a.fe.close(a)}catch(b){throw b;}finally{db[a.fd]=null}a.fd=null},zb=(a,b,c)=>{if(null===a.fd)throw new E(8);if(!a.seekable||!a.fe.qe)throw new E(70);if(0!=c&&1!=c&&2!=c)throw new E(28);a.position=a.fe.qe(a,b,c);a.Kf=[]},Ab=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new E(28);if(null===a.fd)throw new E(8);if(0===(a.flags&2097155))throw new E(8);
if(16384===(a.node.mode&61440))throw new E(31);if(!a.fe.write)throw new E(28);a.seekable&&a.flags&1024&&zb(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new E(70);b=a.fe.write(a,b,c,d,e,f);h||(a.position+=b);return b},Bb=()=>{E||(E=function(a,b){this.name="ErrnoError";this.node=b;this.If=function(c){this.Ce=c};this.If(a);this.message="FS error"},E.prototype=Error(),E.prototype.constructor=E,[44].forEach(a=>{Ya[a]=new E(a);Ya[a].stack="<generic error, no stack>"}))},
Cb,Db=()=>{var a="/";a="string"==typeof a?a:jb(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=Ia(a+"/"+c);try{G(a,16895,0)}catch(d){}}}},Fb=(a,b,c)=>{a=Ia("/dev/"+a);var d=ab(!!b,!!c);Eb||(Eb=64);var e=Eb++<<8|0;Ra(e,{open:f=>{f.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(f,h,n,t)=>{for(var q=0,w=0;w<t;w++){try{var u=b()}catch(C){throw new E(29);}if(void 0===u&&0===q)throw new E(6);if(null===u||void 0===u)break;q++;h[n+w]=u}q&&(f.node.timestamp=
Date.now());return q},write:(f,h,n,t)=>{for(var q=0;q<t;q++)try{c(h[n+q])}catch(w){throw new E(29);}t&&(f.node.timestamp=Date.now());return q}});ub(a,d,e)},Eb,Gb={},rb,wb,Hb=0;function Ib(){for(var a=H.length-1;0<=a;--a)Jb(a);H=[];Kb=[]}var Kb=[];function Lb(){if(navigator.userActivation?navigator.userActivation.isActive:Hb&&Mb.Re)for(var a=0;a<Kb.length;++a){var b=Kb[a];Kb.splice(a,1);--a;b.sg.apply(null,b.Pf)}}var H=[];
function Jb(a){var b=H[a];b.target.removeEventListener(b.pe,b.Bf,b.ze);H.splice(a,1)}function Nb(a){function b(d){++Hb;Mb=a;Lb();a.Ee(d);Lb();--Hb}if(!a.target)return-4;if(a.Ae)a.Bf=b,a.target.addEventListener(a.pe,b,a.ze),H.push(a),Ob||(qa.push(Ib),Ob=!0);else for(var c=0;c<H.length;++c)H[c].target==a.target&&H[c].pe==a.pe&&Jb(c--);return 0}var Ob,Mb,Pb,Qb,Rb,Sb,Tb,Vb,Wb=[0,document,window];function Xb(a){a=2<a?a?B(v,a):"":a;return Wb[a]||document.querySelector(a)}
function Yb(a){return 0>Wb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Zb(a,b){A[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)A[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)A[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)x[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];x[a+1296>>2]=b.connected;x[a+1300>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;D(b.id,v,a+1304,64);D(b.mapping,v,a+1368,64)}var $b;$b=()=>performance.now();
function ac(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function bc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function cc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var dc=1,ec=[],I=[],fc=[],gc=[],hc=[],J=[],ic=[],jc=[],K=[],kc={},lc=4;
function L(a){mc||(mc=a)}function nc(a){for(var b=dc++,c=a.length;c<b;c++)a[c]=null;return b}function oc(a,b){a.oe||(a.oe=a.getContext,a.getContext=function(d,e){e=a.oe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?pc(c,b):0}function pc(a,b){var c=nc(jc),d={handle:c,attributes:b,version:b.Ef,Qe:a};a.canvas&&(a.canvas.Mf=d);jc[c]=d;("undefined"==typeof b.Af||b.Af)&&qc(d);return c}
function qc(a){a||(a=rc);if(!a.Df){a.Df=!0;var b=a.Qe;ac(b);bc(b);cc(b);b.le=b.getExtension("EXT_disjoint_timer_query");b.mg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var sc={},mc,rc;function tc(a){M.activeTexture(a)}function uc(a,b){M.attachShader(I[a],J[b])}function vc(a,b,c){M.bindAttribLocation(I[a],b,c?B(v,c):"")}function wc(a,b){M.bindBuffer(a,ec[b])}
function xc(a,b){M.bindTexture(a,hc[b])}function yc(a,b){M.blendFunc(a,b)}function zc(a,b,c,d){M.bufferData(a,c?v.subarray(c,c+b):b,d)}function Ac(a,b,c,d){M.bufferSubData(a,b,v.subarray(d,d+c))}function Bc(a){M.clear(a)}function Cc(a,b,c,d){M.clearColor(a,b,c,d)}function Dc(a){M.clearDepth(a)}function Ec(a){M.compileShader(J[a])}function Fc(a,b,c,d,e,f,h,n){M.compressedTexImage2D(a,b,c,d,e,f,n?v.subarray(n,n+h):null)}
function Gc(){var a=nc(I),b=M.createProgram();b.name=a;b.Ie=b.Ge=b.He=0;b.Xe=1;I[a]=b;return a}function Hc(a){var b=nc(J);J[b]=M.createShader(a);return b}function Ic(a){M.cullFace(a)}function Jc(a){if(a){var b=I[a];b?(M.deleteProgram(b),b.name=0,I[a]=null):L(1281)}}function Kc(a){if(a){var b=J[a];b?(M.deleteShader(b),J[a]=null):L(1281)}}function Lc(a){M.depthFunc(a)}function Mc(a,b){M.detachShader(I[a],J[b])}function Nc(a){M.disable(a)}function Oc(a,b,c){M.drawArrays(a,b,c)}var Pc=[];
function Qc(a,b,c,d){M.drawElements(a,b,c,d)}function Rc(a){M.enable(a)}function Sc(a){M.enableVertexAttribArray(a)}function Tc(a){M.frontFace(a)}function Uc(a,b,c,d){for(var e=0;e<a;e++){var f=M[c](),h=f&&nc(d);f?(f.name=h,d[h]=f):L(1282);x[b+4*e>>2]=h}}function Vc(a,b){Uc(a,b,"createBuffer",ec)}function Wc(a,b){Uc(a,b,"createTexture",hc)}function Xc(a,b,c,d,e,f,h,n){b=I[b];if(a=M[a](b,c))d=n&&D(a.name,v,n,d),e&&(x[e>>2]=d),f&&(x[f>>2]=a.size),h&&(x[h>>2]=a.type)}
function Yc(a,b){return M.getAttribLocation(I[a],b?B(v,b):"")}function Zc(a,b){y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296}
function $c(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&L(1280);return;case 36345:d=0;break;case 34466:var e=M.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=M.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":L(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:L(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:r[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){L(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:L(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Zc(b,
d);break;case 0:x[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:r[b>>0]=d?1:0}}else L(1281)}function ad(a,b){$c(a,b,2)}function bd(a,b,c,d){a=M.getProgramInfoLog(I[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,v,d,b):0;c&&(x[c>>2]=b)}
function cd(a,b,c){if(c)if(a>=dc)L(1281);else if(a=I[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.Ie)for(b=0;b<M.getProgramParameter(a,35718);++b)a.Ie=Math.max(a.Ie,M.getActiveUniform(a,b).name.length+1);x[c>>2]=a.Ie}else if(35722==b){if(!a.Ge)for(b=0;b<M.getProgramParameter(a,35721);++b)a.Ge=Math.max(a.Ge,M.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.Ge}else if(35381==b){if(!a.He)for(b=0;b<M.getProgramParameter(a,35382);++b)a.He=
Math.max(a.He,M.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.He}else x[c>>2]=M.getProgramParameter(a,b);else L(1281)}function dd(a,b,c){if(c){a=M.le.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Zc(c,d)}else L(1281)}function ed(a,b,c){if(c){a=M.le.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else L(1281)}function fd(a,b,c,d){a=M.getShaderInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,v,d,b):0;c&&(x[c>>2]=b)}
function gd(a,b,c){c?35716==b?(a=M.getShaderInfoLog(J[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(J[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=M.getShaderParameter(J[a],b):L(1281)}var hd=a=>{var b=Ga(a)+1,c=N(b);c&&D(a,v,c,b);return c};
function jd(a){var b=kc[a];if(!b){switch(a){case 7939:b=M.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=hd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=M.getParameter(a))||L(1280);b=b&&hd(b);break;case 7938:b=hd("OpenGL ES 2.0 ("+M.getParameter(7938)+")");break;case 35724:b=M.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=hd(b);break;
default:L(1280)}kc[a]=b}return b}function kd(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function ld(a){var b=a.ye,c=a.sf,d;if(!b)for(a.ye=b={},a.rf={},d=0;d<M.getProgramParameter(a,35718);++d){var e=M.getActiveUniform(a,d);var f=e.name;e=e.size;var h=kd(f);h=0<h?f.slice(0,h):f;var n=a.Xe;a.Xe+=e;c[h]=[e,n];for(f=0;f<e;++f)b[n]=f,a.rf[n++]=h}}
function md(a,b){b=b?B(v,b):"";if(a=I[a]){ld(a);var c=a.ye,d=0,e=b,f=kd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.sf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else L(1281);return-1}function O(a){var b=M.zf;if(b){var c=b.ye[a];"number"==typeof c&&(b.ye[a]=c=M.getUniformLocation(b,b.rf[a]+(0<c?"["+c+"]":"")));return c}L(1282)}
function nd(a,b,c,d){if(c)if(a=I[a],ld(a),a=M.getUniform(a,O(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else L(1281)}
function od(a,b,c,d){if(c)if(a=M.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else L(1281)}function pd(a){a=I[a];M.linkProgram(a);a.ye=0;a.sf={}}function qd(a,b){3317==a&&(lc=b);M.pixelStorei(a,b)}
function rd(a,b,c,d,e){a-=5120;a=1==a?v:4==a?x:6==a?z:5==a||28922==a?y:ka;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=lc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}function sd(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?x[d+4*f>>2]:-1,n=x[c+4*f>>2];h=n?B(v,n,0>h?void 0:h):"";e+=h}M.shaderSource(J[a],e)}function td(a,b,c,d,e,f,h,n,t){M.texImage2D(a,b,c,d,e,f,h,n,t?rd(n,h,d,e,t):null)}function ud(a,b,c){M.texParameterf(a,b,c)}
function vd(a,b,c){M.texParameteri(a,b,c)}var P=[];function wd(a,b){M.uniform1i(O(a),b)}var xd=[];function yd(a,b,c){if(144>=b)for(var d=P[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);M.uniform2fv(O(a),d)}function zd(a,b,c,d,e){M.uniform4f(O(a),b,c,d,e)}function Ad(a,b,c){if(72>=b){var d=P[4*b-1],e=z;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=z.subarray(c>>2,c+16*b>>2);M.uniform4fv(O(a),d)}
function Bd(a,b,c,d){if(18>=b){var e=P[16*b-1],f=z;d>>=2;for(var h=0;h<16*b;h+=16){var n=d+h;e[h]=f[n];e[h+1]=f[n+1];e[h+2]=f[n+2];e[h+3]=f[n+3];e[h+4]=f[n+4];e[h+5]=f[n+5];e[h+6]=f[n+6];e[h+7]=f[n+7];e[h+8]=f[n+8];e[h+9]=f[n+9];e[h+10]=f[n+10];e[h+11]=f[n+11];e[h+12]=f[n+12];e[h+13]=f[n+13];e[h+14]=f[n+14];e[h+15]=f[n+15]}}else e=z.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(O(a),!!c,e)}function Cd(a){a=I[a];M.useProgram(a);M.zf=a}function Dd(a,b,c,d,e,f){M.vertexAttribPointer(a,b,c,!!d,e,f)}
function Ed(a,b,c,d){M.viewport(a,b,c,d)}
function Fd(a,b,c,d){Qb||(Qb=N(72));a=Xb(a);return Nb({target:a,Re:!0,pe:"click",Ae:d,Ee:function(e=event){var f=a,h=Qb;A[h>>3]=e.timeStamp;h>>=2;x[h+2]=e.screenX;x[h+3]=e.screenY;x[h+4]=e.clientX;x[h+5]=e.clientY;x[h+6]=e.ctrlKey;x[h+7]=e.shiftKey;x[h+8]=e.altKey;x[h+9]=e.metaKey;ja[2*h+20]=e.button;ja[2*h+21]=e.buttons;x[h+11]=e.movementX;x[h+12]=e.movementY;f=Yb(f);x[h+13]=e.clientX-f.left;x[h+14]=e.clientY-f.top;Gd.apply(null,[d,4,Qb,b])&&e.preventDefault()},ze:c})}
function Hd(a,b,c,d,e){Sb||(Sb=N(280));return Nb({target:a,pe:e,Ae:d,Ee:function(f=event){var h=Sb,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,t=!!n;x[h>>2]=t;x[h+4>>2]=document.fullscreenEnabled||document.webkitFullscreenEnabled;var q=t?n:Rb,w=q&&q.id?q.id:"";D(q?q==window?"#window":q==screen?"#screen":q&&q.nodeName?q.nodeName:"":"",v,h+8,128);D(w,v,h+136,128);x[h+264>>2]=q?q.clientWidth:0;x[h+268>>2]=q?q.clientHeight:
0;x[h+272>>2]=screen.width;x[h+276>>2]=screen.height;t&&(Rb=n);Gd.apply(null,[d,19,h,b])&&f.preventDefault()},ze:c})}function Id(a,b,c,d,e){Tb||(Tb=N(1432));b={target:Xb(2),Re:!0,pe:e,Ae:c,Ee:function(f=event){var h=Tb;Zb(h,f.gamepad);Gd.apply(null,[c,d,h,a])&&f.preventDefault()},ze:b};return Nb(b)}
function Jd(a,b,c,d,e,f){Vb||(Vb=N(1696));a=Xb(a);return Nb({target:a,Re:"touchstart"==f||"touchend"==f,pe:f,Ae:d,Ee:function(h){for(var n,t={},q=h.touches,w=0;w<q.length;++w)n=q[w],n.df=n.hf=0,t[n.identifier]=n;for(w=0;w<h.changedTouches.length;++w)n=h.changedTouches[w],n.df=1,t[n.identifier]=n;for(w=0;w<h.targetTouches.length;++w)t[h.targetTouches[w].identifier].hf=1;q=Vb;A[q>>3]=h.timeStamp;var u=q>>2;x[u+3]=h.ctrlKey;x[u+4]=h.shiftKey;x[u+5]=h.altKey;x[u+6]=h.metaKey;u+=7;var C=Yb(a),V=0;for(w in t)if(n=
t[w],x[u]=n.identifier,x[u+1]=n.screenX,x[u+2]=n.screenY,x[u+3]=n.clientX,x[u+4]=n.clientY,x[u+5]=n.pageX,x[u+6]=n.pageY,x[u+7]=n.df,x[u+8]=n.hf,x[u+9]=n.clientX-C.left,x[u+10]=n.clientY-C.top,u+=13,31<++V)break;x[q+8>>2]=V;Gd.apply(null,[d,e,q,b])&&h.preventDefault()},ze:c})}
function Kd(a,b){Ld=a;Md=b;if(Nd)if(Od||(Od=!0),0==a)Q=function(){var d=Math.max(0,Pd+b-$b())|0;setTimeout(Qd,d)};else if(1==a)Q=function(){Rd(Qd)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}Q=function(){setImmediate(Qd)}}}
function Sd(a){!Nd||l("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Nd=a;var b=Td;Od=!1;Qd=function(){if(!p)if(0<Ud.length){var c=Date.now(),d=Ud.shift();d.cg(d.Of);if(Vd){var e=Vd,f=0==e%1?e-1:Math.floor(e);Vd=d.Zf?f:(8*e+(f+.5))/9}ea('main loop blocker "'+d.name+'" took '+(Date.now()-c)+" ms");g.setStatus&&(c=g.statusMessage||"Please wait...",d=Vd,e=Wd.bg,
d?d<e?g.setStatus(c+" ("+(e-d)+"/"+e+")"):g.setStatus(c):g.setStatus(""));b<Td||setTimeout(Qd,0)}else b<Td||(Xd=Xd+1|0,1==Ld&&1<Md&&0!=Xd%Md?Q():(0==Ld&&(Pd=$b()),p||g.preMainLoop&&!1===g.preMainLoop()||(Yd(a),g.postMainLoop&&g.postMainLoop()),b<Td||("object"==typeof SDL&&SDL.audio&&SDL.audio.Hf&&SDL.audio.Hf(),Q())))}}
var Zd=a=>{a instanceof Da||"unwind"==a||ba(1,a)},$d=a=>{ia=a;if(!noExitRuntime){if(g.onExit)g.onExit(a);p=!0}ba(a,new Da(a))},Yd=a=>{if(!p)try{if(a(),!noExitRuntime)try{ia=a=ia,$d(a)}catch(b){Zd(b)}}catch(b){Zd(b)}},ae=(a,b)=>setTimeout(()=>{Yd(a)},b),Od=!1,Q=null,Td=0,Nd=null,Ld=0,Md=0,Xd=0,Ud=[];function be(){Td++;var a=Ld,b=Md,c=Nd;Nd=null;Sd(c);Kd(a,b);Q()}var Wd={},Pd,Qd,Vd,ce=!1,de=!1,ee=[];
function fe(){function a(){de=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!ge){ge=!0;$a.push({canHandle:function(c){return!g.pg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=new Blob([c],{type:he(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:he(d)}));var n=URL.createObjectURL(h),t=new Image;t.onload=()=>{t.complete||l("Image "+
d+" could not be decoded");var q=document.createElement("canvas");q.width=t.width;q.height=t.height;q.getContext("2d").drawImage(t,0,0);URL.revokeObjectURL(n);e&&e(c)};t.onerror=()=>{ea("Image "+n+" could not be decoded");f&&f()};t.src=n}});$a.push({canHandle:function(c){return!g.og&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){h||(h=!0,e&&e(c))}var h=!1,n=URL.createObjectURL(new Blob([c],{type:he(d)})),t=new Audio;t.addEventListener("canplaythrough",()=>f(t),!1);
t.onerror=function(){if(!h){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var q="",w=0,u=0,C=0;C<c.length;C++)for(w=w<<8|c[C],u+=8;6<=u;){var V=w>>u-6&63;u-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[V]}2==u?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],q+="=="):4==u&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],q+="=");t.src="data:audio/x-"+d.substr(-3)+
";base64,"+q;f(t)}};t.src=n;ae(()=>{f(t)},1E4)}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!de&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function ie(a,b,c,d){if(b&&g.te&&a==g.canvas)return g.te;var e;if(b){var f={antialias:!1,alpha:!1,Ef:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof sc&&(e=oc(a,f)))var n=jc[e].Qe}else n=a.getContext("2d");if(!n)return null;c&&(b||"undefined"==typeof M||l("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.te=n,b&&(rc=jc[e],g.te=M=rc&&rc.Qe),g.ug=b,ee.forEach(t=>t()),fe());return n}var je=!1,ke=void 0,le=void 0;
function me(a,b){function c(){ce=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=ne,ke&&d.requestPointerLock(),ce=!0,le?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),oe(g.canvas),pe()):oe(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),le?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&
-8388609),oe(g.canvas),pe()):oe(d));if(g.onFullScreen)g.onFullScreen(ce);if(g.onFullscreen)g.onFullscreen(ce)}ke=a;le=b;"undefined"==typeof ke&&(ke=!0);"undefined"==typeof le&&(le=!1);var d=g.canvas;je||(je=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function ne(){if(!ce)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var qe=0;function Rd(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===qe)qe=b+1E3/60;else for(;b+2>=qe;)qe+=1E3/60;setTimeout(a,Math.max(qe-b,0))}}
function he(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var re=0,se=0,te=0,ue=0;
function ve(a){if(de)"mousemove"!=a.type&&"mozMovementX"in a?te=ue=0:(te=a.movementX||a.mozMovementX||a.webkitMovementX||0,ue=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(re=SDL.jg+te,se=SDL.kg+ue):(re+=te,se+=ue);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,te=e-re,ue=a-se,re=e,se=a)}}var we=[];function pe(){var a=g.canvas;we.forEach(b=>b(a.width,a.height))}function xe(a,b,c){oe(g.canvas,a,b);c||pe()}
function oe(a,b,c){b&&c?(a.Lf=b,a.Cf=c):(b=a.Lf,c=a.Cf);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}le?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var ye={},ge;
function ze(a,b,c,d){this.id=a;this.y=this.x=0;this.Te=!1;this.qf=this.pf=0;this.width=b;this.height=c;this.nf=b;this.mf=c;this.title=d;this.attributes=R;this.buttons=0;this.keys=[];this.Se=[];this.Jf=0;this.Be=this.Fe=this.ve=this.Ne=this.re=this.ue=this.Le=this.uf=this.bf=this.wf=this.vf=this.Pe=this.title=null}function S(a){return 0>=a||!T?null:T[a-1]}
var Ae=null,U=null,Be=null,T=null,Ce=null,R=null,De={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0};
function Ee(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Fe(){var a=U,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Ge(a){U&&U.Be&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||dynCall_vii.apply(null,[U.Be,U.id,a]))}
function He(a,b){if(U){var c=Ee(a);if(-1!=c){var d=b&&U.keys[c];U.keys[c]=b;U.Se[a]=b;U.Fe&&(d&&(b=2),Ie.apply(null,[U.Fe,U.id,c,a,b,Fe()]))}}}function Je(){Ke()}function Le(){Ke()}function Me(a){He(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Ne(a){He(a.keyCode,0)}function Oe(){if(U)for(var a=0;a<U.Se.length;++a)U.Se[a]&&He(a,0)}function Pe(a){U&&(ve(a),a.target==g.canvas&&U.ue&&U.ue&&Qe.apply(null,[U.ue,U.id,re,se]))}
function Re(a){U&&a.target==g.canvas&&U.re&&dynCall_vii.apply(null,[U.re,U.id,1])}function Se(a){U&&a.target==g.canvas&&U.re&&dynCall_vii.apply(null,[U.re,U.id,0])}function Te(a,b){if(U&&(ve(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){U.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else U.buttons&=~(1<<c);U.Le&&Ue.apply(null,[U.Le,U.id,c,b,Fe()])}}function Ve(a){U&&Te(a,1)}function We(a){U&&Te(a,0)}
function Xe(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);U&&U.Ne&&a.target==g.canvas&&(Qe.apply(null,[U.Ne,U.id,"mousewheel"==a.type?a.wheelDeltaX:a.deltaX,b]),a.preventDefault())}
var W={},Ye=[],Ze=null;
function Ke(){if(Xd!==Ze||!Xd){Ye=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Ze=Xd;for(var a=0;a<Ye.length;++a){var b=Ye[a];if(b){W[a]||(ea("glfw joystick connected:",a),W[a]={id:hd(b.id),Tf:b.buttons.length,Rf:b.axes.length,buttons:N(b.buttons.length),axes:N(4*b.axes.length)});for(var c=W[a],d=0;d<b.buttons.length;++d)r[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)z[c.axes+4*d>>2]=b.axes[d]}else W[a]&&(ea("glfw joystick disconnected",
a),$e(W[a].id),$e(W[a].buttons),$e(W[a].axes),delete W[a])}}}
function af(a){function b(n){var t="/.glfw_dropped_files/"+n.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=u=>{if(2!=q.readyState)++f,ea("failed to read dropped file: "+n.name+": "+q.error);else{var C=new Uint8Array(u.target.result);u={};u.flags=u.flags||577;var V=xb(t,u.flags,u.mode);if("string"==typeof C){var Ub=new Uint8Array(Ga(C)+1);C=D(C,Ub,0,Ub.length);Ab(V,Ub,0,C,void 0,u.yf)}else if(ArrayBuffer.isView(C))Ab(V,C,0,C.byteLength,void 0,u.yf);else throw Error("Unsupported data type");
yb(V);if(++f===e){bf.apply(null,[U.ve,U.id,e,c]);for(u=0;u<d.length;++u)$e(d[u]);$e(c)}}};q.readAsArrayBuffer(n);var w=hd(t);d.push(w);y[c+4*h>>2]=w}if(U&&U.ve&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=N(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;Db();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function cf(a){if(U&&U.ve)return a.preventDefault(),!1}function df(a){try{a()}catch(b){l(b)}}
function ef(a){var b={},c;for(c in a)(function(d){var e=a[d];b[d]="function"==typeof e?function(){ff.push(d);try{return e.apply(null,arguments)}finally{p||(ff.pop()===d||l(),X&&1===Y&&0===ff.length&&(Y=0,df(gf),"undefined"!=typeof Fibers&&Fibers.tg()))}}:e})(c);return b}var Y=0,X=null,hf=0,ff=[],jf={},kf={},lf=0,mf=null,nf=[];function of(){var a=N(4108),b=a+12;y[a>>2]=b;y[a+4>>2]=b+4096;b=ff[0];var c=jf[b];void 0===c&&(c=lf++,jf[b]=c,kf[c]=b);x[a+8>>2]=c;return a}
function pf(a){if(!p){if(0===Y){var b=!1,c=!1;a((d=0)=>{if(!p&&(hf=d,b=!0,c)){Y=2;df(()=>qf(X));"undefined"!=typeof ye&&Nd&&be();d=!1;try{var e=(0,m[kf[x[X+8>>2]]])()}catch(n){e=n,d=!0}var f=!1;if(!X){var h=mf;h&&(mf=null,(d?h.reject:h.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Y=1,X=of(),"undefined"!=typeof ye&&Nd&&(Q=null,Td++),df(()=>rf(X)))}else 2===Y?(Y=0,df(sf),$e(X),X=null,nf.forEach(d=>Yd(d))):l(`invalid state: ${Y}`);return hf}}
function mb(a,b,c,d){a||(a=this);this.parent=a;this.me=a.me;this.Ke=null;this.id=eb++;this.name=b;this.mode=c;this.ee={};this.fe={};this.Me=d}Object.defineProperties(mb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Bb();fb=Array(4096);tb(F,"/");G("/tmp",16895,0);G("/home",16895,0);G("/home/web_user",16895,0);
(()=>{G("/dev",16895,0);Ra(259,{read:()=>0,write:(d,e,f,h)=>h});ub("/dev/null",259);Qa(1280,Ta);Qa(1536,Ua);ub("/dev/tty",1280);ub("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ma(a).byteLength);return a[--b]};Fb("random",c);Fb("urandom",c);G("/dev/shm",16895,0);G("/dev/shm/tmp",16895,0)})();
(()=>{G("/proc",16895,0);var a=G("/proc/self",16895,0);G("/proc/self/fd",16895,0);tb({me:()=>{var b=Xa(a,"fd",16895,73);b.ee={we:(c,d)=>{var e=qb(+d);c={parent:null,me:{ff:"fake"},ee:{xe:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var M,Z=0;32>Z;++Z)Pc.push(Array(Z));var tf=new Float32Array(288);for(Z=0;288>Z;++Z)P[Z]=tf.subarray(0,Z+1);var uf=new Int32Array(288);for(Z=0;288>Z;++Z)xd[Z]=uf.subarray(0,Z+1);g.requestFullscreen=function(a,b){me(a,b)};
g.requestAnimationFrame=function(a){Rd(a)};g.setCanvasSize=function(a,b,c){xe(a,b,c)};g.pauseMainLoop=function(){Q=null;Td++};g.resumeMainLoop=function(){be()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return ie(a,b,c,d)};
var wf={g:(a,b,c,d)=>{l(`Assertion failed: ${a?B(v,a):""}, at: `+[b?b?B(v,b):"":"unknown filename",c,d?d?B(v,d):"":"unknown function"])},Pa:function(a,b){try{if(0===b)return-28;var c=Ga("/")+1;if(b<c)return-68;D("/",v,a,b);return c}catch(d){if("undefined"==typeof Gb||"ErrnoError"!==d.name)throw d;return-d.Ce}},Ta:function(){return Date.now()},S:function(a,b,c){a=Xb(a);if(!a)return-4;a=Yb(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},ia:function(a,b){if(0>a||a>=Pb.length)return-5;if(!Pb[a])return-7;
Zb(b,Pb[a]);return 0},A:$b,ja:function(){return Pb.length},Gd:tc,Fd:uc,N:function(a,b){M.le.beginQueryEXT(a,K[b])},Ed:vc,Dd:wc,Cd:function(a,b){M.bindFramebuffer(a,fc[b])},Bd:function(a,b){M.bindRenderbuffer(a,gc[b])},Ad:xc,F:function(a){M.bindVertexArray(ic[a])},zd:function(a,b,c,d){M.blendColor(a,b,c,d)},yd:function(a){M.blendEquation(a)},xd:function(a,b){M.blendEquationSeparate(a,b)},wd:yc,vd:function(a,b,c,d){M.blendFuncSeparate(a,b,c,d)},ud:zc,td:Ac,sd:function(a){return M.checkFramebufferStatus(a)},
rd:Bc,qd:Cc,pd:Dc,od:function(a){M.clearStencil(a)},nd:function(a,b,c,d){M.colorMask(!!a,!!b,!!c,!!d)},md:Ec,ld:Fc,kd:function(a,b,c,d,e,f,h,n,t){M.compressedTexSubImage2D(a,b,c,d,e,f,h,t?v.subarray(t,t+n):null)},jd:function(a,b,c,d,e,f,h,n){M.copyTexImage2D(a,b,c,d,e,f,h,n)},hd:function(a,b,c,d,e,f,h,n){M.copyTexSubImage2D(a,b,c,d,e,f,h,n)},gd:Gc,fd:Hc,ed:Ic,dd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=ec[d];e&&(M.deleteBuffer(e),e.name=0,ec[d]=null)}},cd:function(a,b){for(var c=0;c<
a;++c){var d=x[b+4*c>>2],e=fc[d];e&&(M.deleteFramebuffer(e),e.name=0,fc[d]=null)}},bd:Jc,Q:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=K[d];e&&(M.le.deleteQueryEXT(e),K[d]=null)}},ad:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=gc[d];e&&(M.deleteRenderbuffer(e),e.name=0,gc[d]=null)}},$c:Kc,_c:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=hc[d];e&&(M.deleteTexture(e),e.name=0,hc[d]=null)}},E:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];M.deleteVertexArray(ic[d]);
ic[d]=null}},Yc:Lc,Xc:function(a){M.depthMask(!!a)},Wc:function(a,b){M.depthRange(a,b)},Vc:Mc,Uc:Nc,Tc:function(a){M.disableVertexAttribArray(a)},Sc:Oc,Jd:function(a,b,c,d){M.drawArraysInstanced(a,b,c,d)},Kd:function(a,b){for(var c=Pc[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];M.drawBuffers(c)},Rc:Qc,Id:function(a,b,c,d,e){M.drawElementsInstanced(a,b,c,d,e)},Qc:Rc,Pc:Sc,M:function(a){M.le.endQueryEXT(a)},Nc:function(){M.finish()},Mc:function(){M.flush()},Lc:function(a,b,c,d){M.framebufferRenderbuffer(a,b,c,
gc[d])},Kc:function(a,b,c,d,e){M.framebufferTexture2D(a,b,c,hc[d],e)},Jc:Tc,Ic:Vc,Gc:function(a,b){Uc(a,b,"createFramebuffer",fc)},R:function(a,b){for(var c=0;c<a;c++){var d=M.le.createQueryEXT();if(!d){for(L(1282);c<a;)x[b+4*c++>>2]=0;break}var e=nc(K);d.name=e;K[e]=d;x[b+4*c>>2]=e}},Fc:function(a,b){Uc(a,b,"createRenderbuffer",gc)},Ec:Wc,Md:function(a,b){Uc(a,b,"createVertexArray",ic)},Hc:function(a){M.generateMipmap(a)},Cc:function(a,b,c,d,e,f,h){Xc("getActiveAttrib",a,b,c,d,e,f,h)},Bc:function(a,
b,c,d,e,f,h){Xc("getActiveUniform",a,b,c,d,e,f,h)},Ac:function(a,b,c,d){a=M.getAttachedShaders(I[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=J.indexOf(a[b])},zc:Yc,yc:function(a,b){$c(a,b,4)},xc:function(a,b,c){c?x[c>>2]=M.getBufferParameter(a,b):L(1281)},wc:function(){var a=M.getError()||mc;mc=0;return a},vc:ad,uc:function(a,b,c,d){a=M.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},tc:function(a,
b){$c(a,b,0)},qc:bd,rc:cd,H:dd,J:ed,G:dd,I:ed,K:function(a,b,c){c?x[c>>2]=M.le.getQueryEXT(a,b):L(1281)},pc:function(a,b,c){c?x[c>>2]=M.getRenderbufferParameter(a,b):L(1281)},nc:fd,mc:function(a,b,c,d){a=M.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},lc:function(a,b,c,d){if(a=M.getShaderSource(J[a]))b=0<b&&d?D(a,v,d,b):0,c&&(x[c>>2]=b)},oc:gd,kc:jd,jc:function(a,b,c){c?z[c>>2]=M.getTexParameter(a,b):L(1281)},ic:function(a,b,c){c?x[c>>2]=M.getTexParameter(a,
b):L(1281)},fc:md,hc:function(a,b,c){nd(a,b,c,2)},gc:function(a,b,c){nd(a,b,c,0)},cc:function(a,b,c){c?x[c>>2]=M.getVertexAttribOffset(a,b):L(1281)},ec:function(a,b,c){od(a,b,c,2)},dc:function(a,b,c){od(a,b,c,5)},bc:function(a,b){M.hint(a,b)},ac:function(a){return(a=ec[a])?M.isBuffer(a):0},$b:function(a){return M.isEnabled(a)},_b:function(a){return(a=fc[a])?M.isFramebuffer(a):0},Zb:function(a){return(a=I[a])?M.isProgram(a):0},P:function(a){return(a=K[a])?M.le.isQueryEXT(a):0},Yb:function(a){return(a=
gc[a])?M.isRenderbuffer(a):0},Xb:function(a){return(a=J[a])?M.isShader(a):0},Wb:function(a){return(a=hc[a])?M.isTexture(a):0},Ld:function(a){return(a=ic[a])?M.isVertexArray(a):0},Vb:function(a){M.lineWidth(a)},Ub:pd,Tb:qd,Sb:function(a,b){M.polygonOffset(a,b)},L:function(a,b){M.le.queryCounterEXT(K[a],b)},Rb:function(a,b,c,d,e,f,h){(h=rd(f,e,c,d,h))?M.readPixels(a,b,c,d,e,f,h):L(1280)},Qb:function(){},Pb:function(a,b,c,d){M.renderbufferStorage(a,b,c,d)},Ob:function(a,b){M.sampleCoverage(a,!!b)},Nb:function(a,
b,c,d){M.scissor(a,b,c,d)},Mb:function(){L(1280)},Lb:sd,Kb:function(a,b,c){M.stencilFunc(a,b,c)},Jb:function(a,b,c,d){M.stencilFuncSeparate(a,b,c,d)},Ib:function(a){M.stencilMask(a)},Hb:function(a,b){M.stencilMaskSeparate(a,b)},Gb:function(a,b,c){M.stencilOp(a,b,c)},Fb:function(a,b,c,d){M.stencilOpSeparate(a,b,c,d)},Eb:td,Db:ud,Cb:function(a,b,c){M.texParameterf(a,b,z[c>>2])},Bb:vd,Ab:function(a,b,c){M.texParameteri(a,b,x[c>>2])},zb:function(a,b,c,d,e,f,h,n,t){var q=null;t&&(q=rd(n,h,e,f,t));M.texSubImage2D(a,
b,c,d,e,f,h,n,q)},yb:function(a,b){M.uniform1f(O(a),b)},xb:function(a,b,c){if(288>=b)for(var d=P[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);M.uniform1fv(O(a),d)},wb:wd,vb:function(a,b,c){if(288>=b)for(var d=xd[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);M.uniform1iv(O(a),d)},ub:function(a,b,c){M.uniform2f(O(a),b,c)},tb:yd,sb:function(a,b,c){M.uniform2i(O(a),b,c)},rb:function(a,b,c){if(144>=b)for(var d=xd[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=
x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);M.uniform2iv(O(a),d)},qb:function(a,b,c,d){M.uniform3f(O(a),b,c,d)},pb:function(a,b,c){if(96>=b)for(var d=P[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);M.uniform3fv(O(a),d)},ob:function(a,b,c,d){M.uniform3i(O(a),b,c,d)},nb:function(a,b,c){if(96>=b)for(var d=xd[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>
2);M.uniform3iv(O(a),d)},mb:zd,lb:Ad,kb:function(a,b,c,d,e){M.uniform4i(O(a),b,c,d,e)},jb:function(a,b,c){if(72>=b)for(var d=xd[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);M.uniform4iv(O(a),d)},ib:function(a,b,c,d){if(72>=b)for(var e=P[4*b-1],f=0;f<4*b;f+=4)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);M.uniformMatrix2fv(O(a),
!!c,e)},hb:function(a,b,c,d){if(32>=b)for(var e=P[9*b-1],f=0;f<9*b;f+=9)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2],e[f+4]=z[d+(4*f+16)>>2],e[f+5]=z[d+(4*f+20)>>2],e[f+6]=z[d+(4*f+24)>>2],e[f+7]=z[d+(4*f+28)>>2],e[f+8]=z[d+(4*f+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);M.uniformMatrix3fv(O(a),!!c,e)},gb:Bd,fb:Cd,eb:function(a){M.validateProgram(I[a])},db:function(a,b){M.vertexAttrib1f(a,b)},cb:function(a,b){M.vertexAttrib1f(a,z[b>>2])},ab:function(a,b,c){M.vertexAttrib2f(a,
b,c)},$a:function(a,b){M.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},_a:function(a,b,c,d){M.vertexAttrib3f(a,b,c,d)},Za:function(a,b){M.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},Ya:function(a,b,c,d,e){M.vertexAttrib4f(a,b,c,d,e)},Xa:function(a,b){M.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},Hd:function(a,b){M.vertexAttribDivisor(a,b)},Wa:Dd,Va:Ed,Qa:(a,b,c)=>v.copyWithin(a,b,b+c),Na:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ha.buffer.byteLength+65535>>>16;try{ha.grow(e);ma();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},ka:function(){return(Pb=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},va:function(a,b,c,d){return Fd(a,b,c,d)},wa:function(a,b,c,d){if(!document.fullscreenEnabled&&!document.webkitFullscreenEnabled)return-1;a=Xb(a);if(!a)return-4;
Hd(a,b,c,d,"webkitfullscreenchange");return Hd(a,b,c,d,"fullscreenchange")},qa:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?Id(a,b,c,26,"gamepadconnected"):-1},pa:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?Id(a,b,c,27,"gamepaddisconnected"):-1},ra:function(a,b,c,d){return Jd(a,b,c,d,25,"touchcancel")},ta:function(a,b,c,d){return Jd(a,b,c,d,23,"touchend")},sa:function(a,b,c,d){return Jd(a,b,c,d,24,"touchmove")},ua:function(a,b,c,d){return Jd(a,
b,c,d,22,"touchstart")},ma:function(a){da(a?B(v,a):"")},na:function(a){return pf(b=>ae(b,a))},Ua:function(a){try{var b=qb(a);yb(b);return 0}catch(c){if("undefined"==typeof Gb||"ErrnoError"!==c.name)throw c;return c.Ce}},Oa:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);try{if(isNaN(b))return 61;var e=qb(a);zb(e,b,c);la[d>>3]=BigInt(e.position);e.Ue&&0===b&&0===c&&(e.Ue=null);return 0}catch(f){if("undefined"==typeof Gb||
"ErrnoError"!==f.name)throw f;return f.Ce}},Ra:function(a,b,c,d){try{a:{var e=qb(a);a=b;for(var f,h=b=0;h<c;h++){var n=y[a>>2],t=y[a+4>>2];a+=8;var q=Ab(e,r,n,t,f);if(0>q){var w=-1;break a}b+=q;"undefined"!==typeof f&&(f+=q)}w=b}y[d>>2]=w;return 0}catch(u){if("undefined"==typeof Gb||"ErrnoError"!==u.name)throw u;return u.Ce}},B:tc,v:uc,k:vc,a:wc,i:xc,id:yc,n:zc,l:Ac,C:Bc,D:Cc,Dc,Ea:Ec,Ha:Fc,Ba:Gc,Ga:Hc,O:Ic,ya:Jc,x:Kc,Zc:Lc,y:Mc,Z:Nc,z:Oc,La:Qc,t:Rc,f:Sc,Oc:Tc,o:Vc,Ja:Wc,e:Yc,Nd:ad,za:bd,u:cd,Da:fd,
w:gd,sc:jd,b:md,Aa:pd,Ka:qd,Fa:sd,Ia:td,Ca:ud,m:vd,Ma:wd,p:yd,Sa:zd,xa:Ad,bb:Bd,h:Cd,c:Dd,q:Ed,r:function(a,b,c,d){var e;for(e=0;e<T.length&&null!==T[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?me():xe(a,b);for(e=0;e<T.length&&null==T[e];e++);d=0<R[139265];e==T.length&&(d?g.te=ie(g.canvas,!0,!0,{antialias:1<R[135181],depth:0<R[135173],stencil:0<R[135174],alpha:0<R[135172]}):fe());!g.te&&d?f=0:(a=new ze(f,a,b,c),f-1==T.length?
T.push(a):T[f-1]=a,U=a,f=a.id)}return f},fa:function(){R=De},s:function(){return 1},j:function(){return $b()/1E3-Ce},ea:function(a,b){return x[b>>2]=0},ga:function(){if(T)return 1;Ce=$b()/1E3;R=De;T=[];U=null;Be=devicePixelRatio;window.addEventListener("gamepadconnected",Je,!0);window.addEventListener("gamepaddisconnected",Le,!0);window.addEventListener("keydown",Me,!0);window.addEventListener("keypress",Ge,!0);window.addEventListener("keyup",Ne,!0);window.addEventListener("blur",Oe,!0);(function b(){window.matchMedia("(resolution: "+
window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});Be=devicePixelRatio;U&&U.uf&&vf.apply(null,[U.uf,U.id,Be,Be])})();g.canvas.addEventListener("touchmove",Pe,!0);g.canvas.addEventListener("touchstart",Ve,!0);g.canvas.addEventListener("touchcancel",We,!0);g.canvas.addEventListener("touchend",We,!0);g.canvas.addEventListener("mousemove",Pe,!0);g.canvas.addEventListener("mousedown",Ve,!0);g.canvas.addEventListener("mouseup",We,!0);g.canvas.addEventListener("wheel",Xe,!0);g.canvas.addEventListener("mousewheel",
Xe,!0);g.canvas.addEventListener("mouseenter",Re,!0);g.canvas.addEventListener("mouseleave",Se,!0);g.canvas.addEventListener("drop",af,!0);g.canvas.addEventListener("dragover",cf,!0);we.push((b,c)=>{if(U){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(U.pf=U.x,U.qf=U.y,U.nf=U.width,U.mf=U.height,U.x=U.y=0,U.width=screen.width,U.height=screen.height,U.Te=!0):1==U.Te?(U.x=U.pf,U.y=U.qf,U.width=U.nf,U.height=U.mf,U.Te=!1):U.width!=b||U.height!=
c?(U.width=b,U.height=c):d=!1;d&&(xe(U.width,U.height,!0),U&&U.Pe&&bf.apply(null,[U.Pe,U.id,U.width,U.height]),U&&U.bf&&bf.apply(null,[U.bf,U.id,U.width,U.height]))}});return 1},U:function(){},_:function(a,b){if(a=S(a)){var c=a.Be;a.Be=b;b=c}else b=null;return b},V:function(a,b){a=S(a);if(!a)return null;var c=a.re;a.re=b;return c},X:function(a,b){if(a=S(a)){var c=a.ue;a.ue=b;b=c}else b=null;return b},aa:function(a,b){if(a=S(a)){var c=a.ve;a.ve=b;b=c}else b=null;return b},ha:function(a){var b=Ae;Ae=
a;return b},$:function(a,b){if(a=S(a)){var c=a.Fe;a.Fe=b;b=c}else b=null;return b},Y:function(a,b){if(a=S(a)){var c=a.Le;a.Le=b;b=c}else b=null;return b},W:function(a,b){if(a=S(a)){var c=a.Ne;a.Ne=b;b=c}else b=null;return b},ba:function(a,b){a=S(a);if(!a)return null;var c=a.vf;a.vf=b;return c},ca:function(a,b){a=S(a);if(!a)return null;var c=a.wf;a.wf=b;return c},T:function(a,b){if(a=S(a))a.Jf=b},da:function(a,b){if(a=S(a)){var c=a.Pe;a.Pe=b;b=c}else b=null;return b},la:function(){},oa:function(){window.removeEventListener("gamepadconnected",
Je,!0);window.removeEventListener("gamepaddisconnected",Le,!0);window.removeEventListener("keydown",Me,!0);window.removeEventListener("keypress",Ge,!0);window.removeEventListener("keyup",Ne,!0);window.removeEventListener("blur",Oe,!0);g.canvas.removeEventListener("touchmove",Pe,!0);g.canvas.removeEventListener("touchstart",Ve,!0);g.canvas.removeEventListener("touchcancel",We,!0);g.canvas.removeEventListener("touchend",We,!0);g.canvas.removeEventListener("mousemove",Pe,!0);g.canvas.removeEventListener("mousedown",
Ve,!0);g.canvas.removeEventListener("mouseup",We,!0);g.canvas.removeEventListener("wheel",Xe,!0);g.canvas.removeEventListener("mousewheel",Xe,!0);g.canvas.removeEventListener("mouseenter",Re,!0);g.canvas.removeEventListener("mouseleave",Se,!0);g.canvas.removeEventListener("drop",af,!0);g.canvas.removeEventListener("dragover",cf,!0);g.canvas.width=g.canvas.height=1;U=T=null},d:function(a,b){R[a]=b}};
(function(){function a(c){c=c.exports;m=c=ef(c);ha=m.Od;ma();oa.unshift(m.Pd);ta--;g.monitorRunDependencies&&g.monitorRunDependencies(ta);if(0==ta&&(null!==ua&&(clearInterval(ua),ua=null),va)){var d=va;va=null;d()}return c}var b={a:wf};ta++;g.monitorRunDependencies&&g.monitorRunDependencies(ta);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}Ca(b,function(c){a(c.instance)});return{}})();
var $e=a=>($e=m.Qd)(a),N=a=>(N=m.Rd)(a),xf=g._main=(a,b)=>(xf=g._main=m.Sd)(a,b),dynCall_vii=g.dynCall_vii=(a,b,c)=>(dynCall_vii=g.dynCall_vii=m.Ud)(a,b,c),bf=g.dynCall_viii=(a,b,c,d)=>(bf=g.dynCall_viii=m.Vd)(a,b,c,d),Ie=g.dynCall_viiiii=(a,b,c,d,e,f)=>(Ie=g.dynCall_viiiii=m.Wd)(a,b,c,d,e,f),Ue=g.dynCall_viiii=(a,b,c,d,e)=>(Ue=g.dynCall_viiii=m.Xd)(a,b,c,d,e),Qe=g.dynCall_vidd=(a,b,c,d)=>(Qe=g.dynCall_vidd=m.Yd)(a,b,c,d),Gd=g.dynCall_iiii=(a,b,c,d)=>(Gd=g.dynCall_iiii=m.Zd)(a,b,c,d),dynCall_vi=g.dynCall_vi=
(a,b)=>(dynCall_vi=g.dynCall_vi=m._d)(a,b),vf=g.dynCall_viff=(a,b,c,d)=>(vf=g.dynCall_viff=m.$d)(a,b,c,d),rf=a=>(rf=m.ae)(a),gf=()=>(gf=m.be)(),qf=a=>(qf=m.ce)(a),sf=()=>(sf=m.de)();g.___start_em_js=49008;g.___stop_em_js=49083;var yf;va=function zf(){yf||Af();yf||(va=zf)};
function Af(){function a(){if(!yf&&(yf=!0,g.calledRun=!0,!p)){g.noFSInit||Cb||(Cb=!0,Bb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Fb("stdin",g.stdin):vb("/dev/tty","/dev/stdin"),g.stdout?Fb("stdout",null,g.stdout):vb("/dev/tty","/dev/stdout"),g.stderr?Fb("stderr",null,g.stderr):vb("/dev/tty1","/dev/stderr"),xb("/dev/stdin",0),xb("/dev/stdout",1),xb("/dev/stderr",1));gb=!1;Ea(oa);Ea(pa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Bf){var b=xf;try{var c=b(0,0);ia=c;$d(c)}catch(d){Zd(d)}}if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)b=g.postRun.shift(),ra.unshift(b);Ea(ra)}}if(!(0<ta)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)sa();Ea(na);0<ta||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Bf=!0;g.noInitialRun&&(Bf=!1);Af();
