var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.mf||(g.mf=0);g.mf++;
g.ENVIRONMENT_IS_PTHREAD||g.$ww||function(a){function b(r,q,v){var p=new XMLHttpRequest;p.open("GET",r,!0);p.responseType="arraybuffer";p.onprogress=function(u){var y=q;u.total&&(y=u.total);if(u.loaded){p.ye?g.Je[r].loaded=u.loaded:(p.ye=!0,g.Je||(g.Je={}),g.Je[r]={loaded:u.loaded,total:y});var E=y=u=0,fa;for(fa in g.Je){var ha=g.Je[fa];u+=ha.total;y+=ha.loaded;E++}u=Math.ceil(u*g.mf/E);g.setStatus&&g.setStatus(`Downloading data... (${y}/${u})`)}else!g.Je&&g.setStatus&&g.setStatus("Downloading data...")};
p.onerror=function(){throw Error("NetworkError for: "+r);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)v(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(r){console.error("package error:",r)}function d(){function r(u,y,E){this.start=u;this.end=y;this.audio=E}function q(u){if(!u)throw"Loading data file failed."+Error().stack;if(u.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
u=new Uint8Array(u);r.prototype.ig=u;u=a.files;for(var y=0;y<u.length;++y)r.prototype.ye[u[y].filename].onload();g.removeRunDependency("datafile_www/index.data")}g.FS_createPath("/","shaders",!0,!0);r.prototype={ye:{},open:function(u,y){this.name=y;this.ye[y]=this;g.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.ig.subarray(this.start,this.end))},finish:function(u){g.FS_createDataFile(this.name,null,u,!0,!0,!0);g.removeRunDependency(`fp ${this.name}`);this.ye[this.name]=null}};
for(var v=a.files,p=0;p<v.length;++p)(new r(v[p].start,v[p].end,v[p].audio||0)).open("GET",v[p].filename);g.addRunDependency("datafile_www/index.data");g.Hf||(g.Hf={});g.Hf["www/index.data"]={xg:!1};l?(q(l),l=null):h=q}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+
"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;l||b(e,f,function(r){h?(h(r),h=null):l=r},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/shaders/grid.fs",
start:0,end:1616},{filename:"/shaders/line.fs",start:1616,end:2182},{filename:"/shaders/line.vs",start:2182,end:3230}],remote_package_size:3230});var aa=Object.assign({},g),ba=(a,b)=>{throw b;},ca="",da,ea;"undefined"!=typeof document&&document.currentScript&&(ca=document.currentScript.src);ca=0!==ca.indexOf("blob:")?ca.substr(0,ca.replace(/[?#].*/,"").lastIndexOf("/")+1):"";da=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
ea=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=g.print||console.log.bind(console),k=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.quit&&(ba=g.quit);var ja;g.wasmBinary&&(ja=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&m("no native wasm support detected");var ka,n=!1,la,t,w,ma,na,x,z,A,oa,B;
function pa(){var a=ka.buffer;g.HEAP8=t=new Int8Array(a);g.HEAP16=ma=new Int16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=na=new Uint16Array(a);g.HEAPU32=z=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=B=new Float64Array(a);g.HEAP64=oa=new BigInt64Array(a);g.HEAPU64=new BigUint64Array(a)}var qa=[],ra=[],sa=[],ta=[],ua=[];function va(){var a=g.preRun.shift();qa.unshift(a)}var wa=0,xa=null,ya=null;
function za(){wa++;g.monitorRunDependencies&&g.monitorRunDependencies(wa)}function Aa(){wa--;g.monitorRunDependencies&&g.monitorRunDependencies(wa);if(0==wa&&(null!==xa&&(clearInterval(xa),xa=null),ya)){var a=ya;ya=null;a()}}function m(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";k(a);n=!0;la=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ba(a){return a.startsWith("data:application/octet-stream;base64,")}var Ca;Ca="index.wasm";
if(!Ba(Ca)){var Da=Ca;Ca=g.locateFile?g.locateFile(Da,ca):ca+Da}function Ea(a){try{if(a==Ca&&ja)return new Uint8Array(ja);throw"both async and sync fetching of the wasm failed";}catch(b){m(b)}}function Fa(a){return ja||"function"!=typeof fetch?Promise.resolve().then(()=>Ea(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ea(a))}
function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{k("failed to asynchronously prepare wasm: "+d);m(d)})}function Ha(a,b){var c=Ca;ja||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k("wasm streaming compile failed: "+e);k("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}
function Ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}function Ja(a){for(;0<a.length;)a.shift()(g)}var Ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function La(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?La(w,a,b):""}
var Ma=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},D=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ma(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Na=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Oa=a=>{if("/"===
a)return"/";a=D(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Pa(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);m("initRandomDevice")}function Qa(a){return(Qa=Pa())(a)}
function Ra(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ma(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function Sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}
function F(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ta(a){var b=Array(Sa(a)+1);a=F(a,b,0,b.length);b.length=a;return b}var Ua=[];function Va(a,b){Ua[a]={input:[],xe:[],Le:b};Wa(a,Xa)}
var Xa={open:function(a){var b=Ua[a.node.df];if(!b)throw new G(43);a.we=b;a.seekable=!1},close:function(a){a.we.Le.We(a.we)},We:function(a){a.we.Le.We(a.we)},read:function(a,b,c,d){if(!a.we||!a.we.Le.Af)throw new G(60);for(var e=0,f=0;f<d;f++){try{var h=a.we.Le.Af(a.we)}catch(l){throw new G(29);}if(void 0===h&&0===e)throw new G(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.we||!a.we.Le.sf)throw new G(60);try{for(var e=0;e<d;e++)a.we.Le.sf(a.we,
b[c+e])}catch(f){throw new G(29);}d&&(a.node.timestamp=Date.now());return e}},Ya={Af:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ta(b)}return a.input.shift()},sf:function(a,b){null===b||10===b?(ia(La(a.xe,0)),a.xe=[]):0!=b&&a.xe.push(b)},We:function(a){a.xe&&0<a.xe.length&&(ia(La(a.xe,0)),a.xe=[])}},Za=
{sf:function(a,b){null===b||10===b?(k(La(a.xe,0)),a.xe=[]):0!=b&&a.xe.push(b)},We:function(a){a.xe&&0<a.xe.length&&(k(La(a.xe,0)),a.xe=[])}},H={Ae:null,De:function(){return H.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);H.Ae||(H.Ae={dir:{node:{Fe:H.te.Fe,ze:H.te.ze,Pe:H.te.Pe,bf:H.te.bf,Jf:H.te.Jf,gf:H.te.gf,Kf:H.te.Kf,If:H.te.If,ff:H.te.ff},stream:{He:H.ue.He}},file:{node:{Fe:H.te.Fe,ze:H.te.ze},stream:{He:H.ue.He,read:H.ue.read,
write:H.ue.write,vf:H.ue.vf,rf:H.ue.rf,Ff:H.ue.Ff}},link:{node:{Fe:H.te.Fe,ze:H.te.ze,Re:H.te.Re},stream:{}},wf:{node:{Fe:H.te.Fe,ze:H.te.ze},stream:$a}});c=ab(a,b,c,d);16384===(c.mode&61440)?(c.te=H.Ae.dir.node,c.ue=H.Ae.dir.stream,c.fe={}):32768===(c.mode&61440)?(c.te=H.Ae.file.node,c.ue=H.Ae.file.stream,c.ve=0,c.fe=null):40960===(c.mode&61440)?(c.te=H.Ae.link.node,c.ue=H.Ae.link.stream):8192===(c.mode&61440)&&(c.te=H.Ae.wf.node,c.ue=H.Ae.wf.stream);c.timestamp=Date.now();a&&(a.fe[b]=c,a.timestamp=
c.timestamp);return c},zg:function(a){return a.fe?a.fe.subarray?a.fe.subarray(0,a.ve):new Uint8Array(a.fe):new Uint8Array(0)},xf:function(a,b){var c=a.fe?a.fe.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.fe,a.fe=new Uint8Array(b),0<a.ve&&a.fe.set(c.subarray(0,a.ve),0))},fg:function(a,b){if(a.ve!=b)if(0==b)a.fe=null,a.ve=0;else{var c=a.fe;a.fe=new Uint8Array(b);c&&a.fe.set(c.subarray(0,Math.min(b,a.ve)));a.ve=b}},te:{Fe:function(a){var b={};b.vg=8192===(a.mode&
61440)?a.id:1;b.Cg=a.id;b.mode=a.mode;b.Hg=1;b.uid=0;b.Ag=0;b.df=a.df;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ve:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.pg=new Date(a.timestamp);b.Fg=new Date(a.timestamp);b.ug=new Date(a.timestamp);b.Uf=4096;b.rg=Math.ceil(b.size/b.Uf);return b},ze:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&H.fg(a,b.size)},Pe:function(){throw bb[44];},bf:function(a,b,c,d){return H.createNode(a,
b,c,d)},Jf:function(a,b,c){if(16384===(a.mode&61440)){try{var d=cb(b,c)}catch(f){}if(d)for(var e in d.fe)throw new G(55);}delete a.parent.fe[a.name];a.parent.timestamp=Date.now();a.name=c;b.fe[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},gf:function(a,b){delete a.fe[b];a.timestamp=Date.now()},Kf:function(a,b){var c=cb(a,b),d;for(d in c.fe)throw new G(55);delete a.fe[b];a.timestamp=Date.now()},If:function(a){var b=[".",".."],c;for(c in a.fe)a.fe.hasOwnProperty(c)&&b.push(c);return b},ff:function(a,
b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},Re:function(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},ue:{read:function(a,b,c,d,e){var f=a.node.fe;if(e>=a.node.ve)return 0;a=Math.min(a.node.ve-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===t.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.fe||a.fe.subarray)){if(f)return a.fe=b.subarray(c,c+d),a.ve=d;if(0===
a.ve&&0===e)return a.fe=b.slice(c,c+d),a.ve=d;if(e+d<=a.ve)return a.fe.set(b.subarray(c,c+d),e),d}H.xf(a,e+d);if(a.fe.subarray&&b.subarray)a.fe.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.fe[e+f]=b[c+f];a.ve=Math.max(a.ve,e+d);return d},He:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ve);if(0>b)throw new G(28);return b},vf:function(a,b,c){H.xf(a.node,b+c);a.node.ve=Math.max(a.node.ve,b+c)},rf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);
a=a.node.fe;if(e&2||a.buffer!==t.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;m();b=void 0;if(!b)throw new G(48);t.set(a,b)}else c=!1,b=a.byteOffset;return{Lg:b,mg:c}},Ff:function(a,b,c,d){H.ue.write(a,b,0,d,c,!1);return 0}}};function db(a,b,c){var d=`al ${a}`;ea(a,e=>{e||m(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Aa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&za(d)}
var eb=g.preloadPlugins||[];function fb(a,b,c,d){"undefined"!=typeof gb&&hb();var e=!1;eb.forEach(function(f){!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e}function ib(a,b,c,d,e,f,h,l,r,q){function v(y){function E(fa){q&&q();l||jb(a,b,fa,d,e,r);f&&f();Aa(u)}fb(y,p,E,()=>{h&&h();Aa(u)})||E(y)}var p=b?Ra(D(a+"/"+b)):a,u=`cp ${p}`;za(u);"string"==typeof c?db(c,y=>v(y),h):v(c)}function kb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var lb=null,mb={},nb=[],ob=1,I=null,pb=!0,G=null,bb={},J=(a,b={})=>{a=Ra(a);if(!a)return{path:"",node:null};b=Object.assign({yf:!0,tf:0},b);if(8<b.tf)throw new G(32);a=a.split("/").filter(h=>!!h);for(var c=lb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=cb(c,a[e]);d=D(d+"/"+a[e]);c.Qe&&(!f||f&&b.yf)&&(c=c.Qe.root);if(!f||b.nf)for(f=0;40960===(c.mode&61440);)if(c=qb(d),d=Ra(Na(d),c),c=J(d,{tf:b.tf+1}).node,40<f++)throw new G(32);}return{path:d,node:c}},rb=a=>{for(var b;;){if(a===
a.parent)return a=a.De.Ef,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},sb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%I.length},cb=(a,b)=>{var c;if(c=(c=tb(a,"x"))?c:a.te.Pe?0:2)throw new G(c,a);for(c=I[sb(a.id,b)];c;c=c.Ke){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.te.Pe(a,b)},ab=(a,b,c,d)=>{a=new ub(a,b,c,d);b=sb(a.parent.id,a.name);a.Ke=I[b];return I[b]=a},vb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");
return b},tb=(a,b)=>{if(pb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},wb=(a,b)=>{try{return cb(a,b),20}catch(c){}return tb(a,"wx")},xb=()=>{for(var a=0;4096>=a;a++)if(!nb[a])return a;throw new G(33);},zb=(a,b=-1)=>{yb||(yb=function(){this.ye={}},yb.prototype={},Object.defineProperties(yb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.ye.flags},
set:function(c){this.ye.flags=c}},position:{get:function(){return this.ye.position},set:function(c){this.ye.position=c}}}));a=Object.assign(new yb,a);-1==b&&(b=xb());a.Ee=b;return nb[b]=a},$a={open:a=>{a.ue=mb[a.node.df].ue;a.ue.open&&a.ue.open(a)},He:()=>{throw new G(70);}},Wa=(a,b)=>{mb[a]={ue:b}},Ab=(a,b)=>{var c="/"===b,d=!b;if(c&&lb)throw new G(10);if(!c&&!d){var e=J(b,{yf:!1});b=e.path;e=e.node;if(e.Qe)throw new G(10);if(16384!==(e.mode&61440))throw new G(54);}b={type:a,Kg:{},Ef:b,dg:[]};a=
a.De(b);a.De=b;b.root=a;c?lb=a:e&&(e.Qe=b,e.De&&e.De.dg.push(b))},K=(a,b,c)=>{var d=J(a,{parent:!0}).node;a=Oa(a);if(!a||"."===a||".."===a)throw new G(28);var e=wb(d,a);if(e)throw new G(e);if(!d.te.bf)throw new G(63);return d.te.bf(d,a,b,c)},Bb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return K(a,b|8192,c)},Cb=(a,b)=>{if(!Ra(a))throw new G(44);var c=J(b,{parent:!0}).node;if(!c)throw new G(44);b=Oa(b);var d=wb(c,b);if(d)throw new G(d);if(!c.te.ff)throw new G(63);c.te.ff(c,b,a)},Db=a=>{var b=J(a,
{parent:!0}).node;if(!b)throw new G(44);var c=Oa(a);a=cb(b,c);a:{try{var d=cb(b,c)}catch(f){d=f.Ce;break a}var e=tb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new G(d);if(!b.te.gf)throw new G(63);if(a.Qe)throw new G(10);b.te.gf(b,c);b=sb(a.parent.id,a.name);if(I[b]===a)I[b]=a.Ke;else for(b=I[b];b;){if(b.Ke===a){b.Ke=a.Ke;break}b=b.Ke}},qb=a=>{a=J(a).node;if(!a)throw new G(44);if(!a.te.Re)throw new G(28);return Ra(rb(a.parent),a.te.Re(a))},Eb=(a,b)=>{a="string"==typeof a?J(a,{nf:!0}).node:
a;if(!a.te.ze)throw new G(63);a.te.ze(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Gb=(a,b,c)=>{if(""===a)throw new G(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=D(a);try{e=J(a,{nf:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new G(20);}else e=K(a,c,0),d=!0;if(!e)throw new G(44);
8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new G(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==vb(b)||b&512)?31:tb(e,vb(b)):44))throw new G(c);if(b&512&&!d){c=e;c="string"==typeof c?J(c,{nf:!0}).node:c;if(!c.te.ze)throw new G(63);if(16384===(c.mode&61440))throw new G(31);if(32768!==(c.mode&61440))throw new G(28);if(d=tb(c,"w"))throw new G(d);c.te.ze(c,{size:0,timestamp:Date.now()})}b&=-131713;e=zb({node:e,path:rb(e),flags:b,seekable:!0,position:0,
ue:e.ue,jg:[],error:!1});e.ue.open&&e.ue.open(e);!g.logReadFiles||b&1||(Fb||(Fb={}),a in Fb||(Fb[a]=1));return e},Hb=a=>{if(null===a.Ee)throw new G(8);a.qf&&(a.qf=null);try{a.ue.close&&a.ue.close(a)}catch(b){throw b;}finally{nb[a.Ee]=null}a.Ee=null},Ib=(a,b,c)=>{if(null===a.Ee)throw new G(8);if(!a.seekable||!a.ue.He)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.ue.He(a,b,c);a.jg=[]},Jb=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new G(28);if(null===a.Ee)throw new G(8);if(0===(a.flags&2097155))throw new G(8);
if(16384===(a.node.mode&61440))throw new G(31);if(!a.ue.write)throw new G(28);a.seekable&&a.flags&1024&&Ib(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new G(70);b=a.ue.write(a,b,c,d,e,f);h||(a.position+=b);return b},Kb=()=>{G||(G=function(a,b){this.name="ErrnoError";this.node=b;this.gg=function(c){this.Ce=c};this.gg(a);this.message="FS error"},G.prototype=Error(),G.prototype.constructor=G,[44].forEach(a=>{bb[a]=new G(a);bb[a].stack="<generic error, no stack>"}))},
Lb,Mb=(a,b)=>{a="string"==typeof a?a:rb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=D(a+"/"+c);try{K(d,16895,0)}catch(e){}a=d}}return d},Nb=(a,b,c,d)=>{a=D(("string"==typeof a?a:rb(a))+"/"+b);c=kb(c,d);return K(a,(void 0!==c?c:438)&4095|32768,0)},jb=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:rb(a),h=b?D(a+"/"+b):a);a=kb(d,e);h=K(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Eb(h,
a|146);b=Gb(h,577);Jb(b,c,0,c.length,0,f);Hb(b);Eb(h,a)}return h},L=(a,b,c,d)=>{a=D(("string"==typeof a?a:rb(a))+"/"+b);b=kb(!!c,!!d);L.Df||(L.Df=64);var e=L.Df++<<8|0;Wa(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,l,r)=>{for(var q=0,v=0;v<r;v++){try{var p=c()}catch(u){throw new G(29);}if(void 0===p&&0===q)throw new G(6);if(null===p||void 0===p)break;q++;h[l+v]=p}q&&(f.node.timestamp=Date.now());return q},write:(f,h,l,r)=>{for(var q=0;q<r;q++)try{d(h[l+q])}catch(v){throw new G(29);
}r&&(f.node.timestamp=Date.now());return q}});return Bb(a,b,e)},Ob=a=>{if(!(a.Cf||a.bg||a.link||a.fe)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(da)try{a.fe=Ta(da(a.url)),a.ve=a.fe.length}catch(b){throw new G(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Pb=(a,b,c,d,
e)=>{if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Cf:!1,url:c};var f=Nb(a,b,d,e);c.fe?f.fe=c.fe:c.url&&(f.fe=null,f.url=c.url);Object.defineProperties(f,{ve:{get:function(){return this.fe.length}}});var h={};Object.keys(f.ue).forEach(l=>{var r=f.ue[l];h[l]=function(){Ob(f);return r.apply(null,arguments)}});h.read=(l,r,q,v,p)=>{Ob(f);l=l.node.fe;if(p>=l.length)r=0;else{v=Math.min(l.length-
p,v);if(l.slice)for(var u=0;u<v;u++)r[q+u]=l[p+u];else for(u=0;u<v;u++)r[q+u]=l.get(p+u);r=v}return r};h.rf=()=>{Ob(f);m();throw new G(48);};f.ue=h;return f},M={},yb,Fb,Qb=void 0;function Rb(){Qb+=4;return x[Qb-4>>2]}function Sb(a){a=nb[a];if(!a)throw new G(8);return a}var Tb=0;function Ub(){for(var a=N.length-1;0<=a;--a)Vb(a);N=[];Wb=[]}var Wb=[];function Xb(){if(Tb&&Yb.kf)for(var a=0;a<Wb.length;++a){var b=Wb[a];Wb.splice(a,1);--a;b.Mg.apply(null,b.og)}}var N=[];
function Vb(a){var b=N[a];b.target.removeEventListener(b.Ge,b.Yf,b.Te);N.splice(a,1)}function Zb(a){function b(d){++Tb;Yb=a;Xb();a.Xe(d);Xb();--Tb}if(!a.target)return-4;if(a.Ue)a.Yf=b,a.target.addEventListener(a.Ge,b,a.Te),N.push(a),$b||(ta.push(Ub),$b=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Ge==a.Ge&&Vb(c--);return 0}var $b,Yb,ac,bc,cc,dc,ec,fc,gc=[0,document,window];function hc(a){a=2<a?C(a):a;return gc[a]||document.querySelector(a)}
function ic(a){return 0>gc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function jc(a,b){B[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)B[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)B[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)x[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];x[a+1296>>2]=b.connected;x[a+1300>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;F(b.id,w,a+1304,64);F(b.mapping,w,a+1368,64)}var kc;kc=()=>performance.now();
function mc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function nc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function oc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var pc=1,qc=[],O=[],rc=[],sc=[],tc=[],P=[],uc=[],vc=[],Q=[],wc={},xc=4;
function R(a){yc||(yc=a)}function zc(a){for(var b=pc++,c=a.length;c<b;c++)a[c]=null;return b}function Ac(a,b){a.ye||(a.ye=a.getContext,a.getContext=function(d,e){e=a.ye(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Bc(c,b):0}function Bc(a,b){var c=zc(vc),d={Bg:c,attributes:b,version:b.cg,jf:a};a.canvas&&(a.canvas.lg=d);vc[c]=d;("undefined"==typeof b.Xf||b.Xf)&&Cc(d);return c}
function Cc(a){a||(a=Dc);if(!a.$f){a.$f=!0;var b=a.jf;mc(b);nc(b);oc(b);b.Be=b.getExtension("EXT_disjoint_timer_query");b.Gg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ec={},yc,Dc;function Fc(a){S.activeTexture(a)}function Gc(a,b){S.attachShader(O[a],P[b])}function Hc(a,b,c){S.bindAttribLocation(O[a],b,C(c))}function Ic(a,b){S.bindBuffer(a,qc[b])}
function Jc(a,b){S.bindTexture(a,tc[b])}function Kc(a,b){S.blendFunc(a,b)}function Lc(a,b,c,d){S.bufferData(a,c?w.subarray(c,c+b):b,d)}function Mc(a,b,c,d){S.bufferSubData(a,b,w.subarray(d,d+c))}function Nc(a){S.clear(a)}function Oc(a,b,c,d){S.clearColor(a,b,c,d)}function Pc(a){S.clearDepth(a)}function Qc(a){S.compileShader(P[a])}function Rc(a,b,c,d,e,f,h,l){S.compressedTexImage2D(a,b,c,d,e,f,l?w.subarray(l,l+h):null)}
function Sc(){var a=zc(O),b=S.createProgram();b.name=a;b.af=b.Ze=b.$e=0;b.uf=1;O[a]=b;return a}function Tc(a){var b=zc(P);P[b]=S.createShader(a);return b}function Uc(a){S.cullFace(a)}function Vc(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=qc[d];e&&(S.deleteBuffer(e),e.name=0,qc[d]=null)}}function Wc(a){if(a){var b=O[a];b?(S.deleteProgram(b),b.name=0,O[a]=null):R(1281)}}function Xc(a){if(a){var b=P[a];b?(S.deleteShader(b),P[a]=null):R(1281)}}function Yc(a){S.depthFunc(a)}
function Zc(a,b){S.detachShader(O[a],P[b])}function $c(a){S.disable(a)}function ad(a,b,c){S.drawArrays(a,b,c)}var bd=[];function cd(a,b,c,d){S.drawElements(a,b,c,d)}function dd(a){S.enable(a)}function ed(a){S.enableVertexAttribArray(a)}function fd(a){S.frontFace(a)}function gd(a,b,c,d){for(var e=0;e<a;e++){var f=S[c](),h=f&&zc(d);f?(f.name=h,d[h]=f):R(1282);x[b+4*e>>2]=h}}function hd(a,b){gd(a,b,"createBuffer",qc)}function jd(a,b){gd(a,b,"createTexture",tc)}
function kd(a,b,c,d,e,f,h,l){b=O[b];if(a=S[a](b,c))d=l&&F(a.name,w,l,d),e&&(x[e>>2]=d),f&&(x[f>>2]=a.size),h&&(x[h>>2]=a.type)}function ld(a,b){return S.getAttribLocation(O[a],C(b))}function md(a,b){z[a>>2]=b;z[a+4>>2]=(b-z[a>>2])/4294967296}
function nd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=S.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=S.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:t[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:md(b,
d);break;case 0:x[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:t[b>>0]=d?1:0}}else R(1281)}function od(a,b){nd(a,b,2)}function pd(a,b,c,d){a=S.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,w,d,b):0;c&&(x[c>>2]=b)}
function qd(a,b,c){if(c)if(a>=pc)R(1281);else if(a=O[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.af)for(b=0;b<S.getProgramParameter(a,35718);++b)a.af=Math.max(a.af,S.getActiveUniform(a,b).name.length+1);x[c>>2]=a.af}else if(35722==b){if(!a.Ze)for(b=0;b<S.getProgramParameter(a,35721);++b)a.Ze=Math.max(a.Ze,S.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.Ze}else if(35381==b){if(!a.$e)for(b=0;b<S.getProgramParameter(a,35382);++b)a.$e=
Math.max(a.$e,S.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.$e}else x[c>>2]=S.getProgramParameter(a,b);else R(1281)}function rd(a,b,c){if(c){a=S.Be.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;md(c,d)}else R(1281)}function sd(a,b,c){if(c){a=S.Be.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)}function td(a,b,c,d){a=S.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,w,d,b):0;c&&(x[c>>2]=b)}
function ud(a,b,c){c?35716==b?(a=S.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(P[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=S.getShaderParameter(P[a],b):R(1281)}function vd(a){var b=Sa(a)+1,c=T(b);c&&F(a,w,c,b);return c}
function wd(a){var b=wc[a];if(!b){switch(a){case 7939:b=S.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=vd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=S.getParameter(a))||R(1280);b=b&&vd(b);break;case 7938:b=vd("OpenGL ES 2.0 ("+S.getParameter(7938)+")");break;case 35724:b=S.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=vd(b);break;
default:R(1280)}wc[a]=b}return b}function xd(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function yd(a){var b=a.Se,c=a.Qf,d;if(!b)for(a.Se=b={},a.Pf={},d=0;d<S.getProgramParameter(a,35718);++d){var e=S.getActiveUniform(a,d);var f=e.name;e=e.size;var h=xd(f);h=0<h?f.slice(0,h):f;var l=a.uf;a.uf+=e;c[h]=[e,l];for(f=0;f<e;++f)b[l]=f,a.Pf[l++]=h}}
function zd(a,b){b=C(b);if(a=O[a]){yd(a);var c=a.Se,d=0,e=b,f=xd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Qf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else R(1281);return-1}function U(a){var b=S.Wf;if(b){var c=b.Se[a];"number"==typeof c&&(b.Se[a]=c=S.getUniformLocation(b,b.Pf[a]+(0<c?"["+c+"]":"")));return c}R(1282)}
function Ad(a,b,c,d){if(c)if(a=O[a],yd(a),a=S.getUniform(a,U(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else R(1281)}
function Bd(a,b,c,d){if(c)if(a=S.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else R(1281)}function Cd(a){a=O[a];S.linkProgram(a);a.Se=0;a.Qf={}}function Dd(a,b){3317==a&&(xc=b);S.pixelStorei(a,b)}
function Ed(a,b,c,d,e){a-=5120;a=1==a?w:4==a?x:6==a?A:5==a||28922==a?z:na;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=xc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}function Fd(a,b,c,d,e,f,h){(h=Ed(f,e,c,d,h))?S.readPixels(a,b,c,d,e,f,h):R(1280)}function Gd(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?x[d+4*f>>2]:-1;e+=C(x[c+4*f>>2],0>h?void 0:h)}S.shaderSource(P[a],e)}function Hd(a,b,c,d,e,f,h,l,r){S.texImage2D(a,b,c,d,e,f,h,l,r?Ed(l,h,d,e,r):null)}
function Id(a,b,c){S.texParameterf(a,b,c)}function Jd(a,b,c){S.texParameteri(a,b,c)}var Kd=[];function Ld(a,b,c){if(288>=b)for(var d=Kd[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);S.uniform1fv(U(a),d)}function Md(a,b){S.uniform1i(U(a),b)}var Nd=[];function Od(a,b,c){if(288>=b)for(var d=Nd[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);S.uniform1iv(U(a),d)}
function Pd(a,b,c){if(144>=b)for(var d=Kd[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);S.uniform2fv(U(a),d)}function Qd(a,b,c){if(144>=b)for(var d=Nd[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);S.uniform2iv(U(a),d)}function Rd(a,b,c){if(96>=b)for(var d=Kd[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);S.uniform3fv(U(a),d)}
function Sd(a,b,c){if(96>=b)for(var d=Nd[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);S.uniform3iv(U(a),d)}function Td(a,b,c,d,e){S.uniform4f(U(a),b,c,d,e)}function Ud(a,b,c){if(72>=b){var d=Kd[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=A.subarray(c>>2,c+16*b>>2);S.uniform4fv(U(a),d)}
function Vd(a,b,c){if(72>=b)for(var d=Nd[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);S.uniform4iv(U(a),d)}
function Wd(a,b,c,d){if(18>=b){var e=Kd[16*b-1],f=A;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=A.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(U(a),!!c,e)}function Xd(a){a=O[a];S.useProgram(a);S.Wf=a}function Yd(a,b,c,d,e,f){S.vertexAttribPointer(a,b,c,!!d,e,f)}
function Zd(a,b,c,d){S.viewport(a,b,c,d)}
function $d(a,b,c,d){bc||(bc=T(72));a=hc(a);return Zb({target:a,kf:!0,Ge:"click",Ue:d,Xe:function(e=event){var f=a,h=bc;B[h>>3]=e.timeStamp;h>>=2;x[h+2]=e.screenX;x[h+3]=e.screenY;x[h+4]=e.clientX;x[h+5]=e.clientY;x[h+6]=e.ctrlKey;x[h+7]=e.shiftKey;x[h+8]=e.altKey;x[h+9]=e.metaKey;ma[2*h+20]=e.button;ma[2*h+21]=e.buttons;x[h+11]=e.movementX;x[h+12]=e.movementY;f=ic(f);x[h+13]=e.clientX-f.left;x[h+14]=e.clientY-f.top;ae.apply(null,[d,4,bc,b])&&e.preventDefault()},Te:c})}
function be(a,b,c,d,e){dc||(dc=T(280));return Zb({target:a,Ge:e,Ue:d,Xe:function(f=event){var h=dc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,r=!!l;x[h>>2]=r;x[h+4>>2]=document.fullscreenEnabled||document.webkitFullscreenEnabled;var q=r?l:cc,v=q&&q.id?q.id:"";F(q?q==window?"#window":q==screen?"#screen":q&&q.nodeName?q.nodeName:"":"",w,h+8,128);F(v,w,h+136,128);x[h+264>>2]=q?q.clientWidth:0;x[h+268>>2]=q?q.clientHeight:
0;x[h+272>>2]=screen.width;x[h+276>>2]=screen.height;r&&(cc=l);ae.apply(null,[d,19,h,b])&&f.preventDefault()},Te:c})}function ce(a,b,c,d,e){ec||(ec=T(1432));b={target:hc(2),kf:!0,Ge:e,Ue:c,Xe:function(f=event){var h=ec;jc(h,f.gamepad);ae.apply(null,[c,d,h,a])&&f.preventDefault()},Te:b};return Zb(b)}
function de(a,b,c,d,e,f){fc||(fc=T(1696));a=hc(a);return Zb({target:a,kf:"touchstart"==f||"touchend"==f,Ge:f,Ue:d,Xe:function(h){for(var l,r={},q=h.touches,v=0;v<q.length;++v)l=q[v],l.Bf=l.Gf=0,r[l.identifier]=l;for(v=0;v<h.changedTouches.length;++v)l=h.changedTouches[v],l.Bf=1,r[l.identifier]=l;for(v=0;v<h.targetTouches.length;++v)r[h.targetTouches[v].identifier].Gf=1;q=fc;B[q>>3]=h.timeStamp;var p=q>>2;x[p+3]=h.ctrlKey;x[p+4]=h.shiftKey;x[p+5]=h.altKey;x[p+6]=h.metaKey;p+=7;var u=ic(a),y=0;for(v in r)if(l=
r[v],x[p]=l.identifier,x[p+1]=l.screenX,x[p+2]=l.screenY,x[p+3]=l.clientX,x[p+4]=l.clientY,x[p+5]=l.pageX,x[p+6]=l.pageY,x[p+7]=l.Bf,x[p+8]=l.Gf,x[p+9]=l.clientX-u.left,x[p+10]=l.clientY-u.top,p+=13,31<++y)break;x[q+8>>2]=y;ae.apply(null,[d,e,q,b])&&h.preventDefault()},Te:c})}function ee(a){a instanceof Ia||"unwind"==a||ba(1,a)}function fe(a){la=la=a;if(!noExitRuntime){if(g.onExit)g.onExit(a);n=!0}ba(a,new Ia(a))}
function ge(a){if(!n)try{if(a(),!noExitRuntime)try{fe(la)}catch(b){ee(b)}}catch(b){ee(b)}}function he(a,b){return setTimeout(()=>{ge(a)},b)}
function ie(a,b){je=a;ke=b;if(le)if(me||(me=!0),0==a)ne=function(){var d=Math.max(0,oe+b-kc())|0;setTimeout(pe,d)};else if(1==a)ne=function(){qe(pe)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}ne=function(){setImmediate(pe)}}}
function re(a){!le||m("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");le=a;var b=se;me=!1;pe=function(){if(!n)if(0<te.length){var c=Date.now(),d=te.shift();d.yg(d.ng);if(ue){var e=ue,f=0==e%1?e-1:Math.floor(e);ue=d.tg?f:(8*e+(f+.5))/9}ia('main loop blocker "'+d.name+'" took '+(Date.now()-c)+" ms");g.setStatus&&(c=g.statusMessage||"Please wait...",d=ue,e=ve.wg,
d?d<e?g.setStatus(c+" ("+(e-d)+"/"+e+")"):g.setStatus(c):g.setStatus(""));b<se||setTimeout(pe,0)}else b<se||(we=we+1|0,1==je&&1<ke&&0!=we%ke?ne():(0==je&&(oe=kc()),n||g.preMainLoop&&!1===g.preMainLoop()||(ge(a),g.postMainLoop&&g.postMainLoop()),b<se||("object"==typeof SDL&&SDL.audio&&SDL.audio.eg&&SDL.audio.eg(),ne())))}}var me=!1,ne=null,se=0,le=null,je=0,ke=0,we=0,te=[];function xe(){se++;var a=je,b=ke,c=le;le=null;re(c);ie(a,b);ne()}var ve={},oe,pe,ue,ye=!1,ze=!1,Ae=[];
function hb(){function a(){ze=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!Be){Be=!0;eb.push({canHandle:function(c){return!g.Jg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=new Blob([c],{type:Ce(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Ce(d)}));var l=URL.createObjectURL(h),r=new Image;r.onload=()=>{r.complete||m("Image "+
d+" could not be decoded");var q=document.createElement("canvas");q.width=r.width;q.height=r.height;q.getContext("2d").drawImage(r,0,0);URL.revokeObjectURL(l);e&&e(c)};r.onerror=()=>{ia("Image "+l+" could not be decoded");f&&f()};r.src=l}});eb.push({canHandle:function(c){return!g.Ig&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){h||(h=!0,e&&e(c))}var h=!1,l=URL.createObjectURL(new Blob([c],{type:Ce(d)})),r=new Audio;r.addEventListener("canplaythrough",()=>f(r),!1);
r.onerror=function(){if(!h){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var q="",v=0,p=0,u=0;u<c.length;u++)for(v=v<<8|c[u],p+=8;6<=p;){var y=v>>p-6&63;p-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[y]}2==p?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],q+="=="):4==p&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],q+="=");r.src="data:audio/x-"+d.substr(-3)+
";base64,"+q;f(r)}};r.src=l;he(()=>{f(r)},1E4)}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!ze&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function De(a,b,c,d){if(b&&g.Me&&a==g.canvas)return g.Me;var e;if(b){var f={antialias:!1,alpha:!1,cg:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof Ec&&(e=Ac(a,f)))var l=vc[e].jf}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof S||m("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Me=l,b&&(Dc=vc[e],g.Me=S=Dc&&Dc.jf),g.Og=b,Ae.forEach(r=>r()),hb());return l}var Ee=!1,Fe=void 0,Ge=void 0;
function He(a,b){function c(){ye=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ie,Fe&&d.requestPointerLock(),ye=!0,Ge?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=z[SDL.screen>>2]|8388608),Je(g.canvas),Ke()):Je(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Ge?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=z[SDL.screen>>2]&
-8388609),Je(g.canvas),Ke()):Je(d));if(g.onFullScreen)g.onFullScreen(ye);if(g.onFullscreen)g.onFullscreen(ye)}Fe=a;Ge=b;"undefined"==typeof Fe&&(Fe=!0);"undefined"==typeof Ge&&(Ge=!1);var d=g.canvas;Ee||(Ee=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Ie(){if(!ye)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Le=0;function qe(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Le)Le=b+1E3/60;else for(;b+2>=Le;)Le+=1E3/60;setTimeout(a,Math.max(Le-b,0))}}
function Ce(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Me=0,Ne=0,Oe=0,Pe=0;
function Qe(a){if(ze)"mousemove"!=a.type&&"mozMovementX"in a?Oe=Pe=0:(Oe=a.movementX||a.mozMovementX||a.webkitMovementX||0,Pe=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Me=SDL.Dg+Oe,Ne=SDL.Eg+Pe):(Me+=Oe,Ne+=Pe);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Oe=e-Me,Pe=a-Ne,Me=e,Ne=a)}}var Re=[];function Ke(){var a=g.canvas;Re.forEach(b=>b(a.width,a.height))}function Se(a,b,c){Je(g.canvas,a,b);c||Ke()}
function Je(a,b,c){b&&c?(a.kg=b,a.Zf=c):(b=a.kg,c=a.Zf);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Ge?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var gb={},Be;
function Te(a,b,c,d){this.id=a;this.y=this.x=0;this.pf=!1;this.Of=this.Nf=0;this.width=b;this.height=c;this.Mf=b;this.Lf=c;this.title=d;this.attributes=V;this.buttons=0;this.keys=[];this.lf=[];this.hg=0;this.Ve=this.Ye=this.Oe=this.ef=this.Ie=this.Ne=this.cf=this.Rf=this.zf=this.Tf=this.Sf=this.hf=this.title=null}function W(a){return 0>=a||!X?null:X[a-1]}
var Ue=null,Y=null,Ve=null,X=null,We=null,V=null,Xe={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0};
function Ye(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Ze(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function $e(a){Y&&Y.Ve&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||dynCall_vii.apply(null,[Y.Ve,Y.id,a]))}
function af(a,b){if(Y){var c=Ye(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.lf[a]=b;Y.Ye&&(d&&(b=2),bf.apply(null,[Y.Ye,Y.id,c,a,b,Ze()]))}}}function cf(){df()}function ef(){df()}function ff(a){af(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function hf(a){af(a.keyCode,0)}function jf(){if(Y)for(var a=0;a<Y.lf.length;++a)Y.lf[a]&&af(a,0)}function kf(a){Y&&(Qe(a),a.target==g.canvas&&Y.Ne&&Y.Ne&&lf.apply(null,[Y.Ne,Y.id,Me,Ne]))}
function mf(a){Y&&a.target==g.canvas&&Y.Ie&&dynCall_vii.apply(null,[Y.Ie,Y.id,1])}function nf(a){Y&&a.target==g.canvas&&Y.Ie&&dynCall_vii.apply(null,[Y.Ie,Y.id,0])}function of(a,b){if(Y&&(Qe(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.cf&&pf.apply(null,[Y.cf,Y.id,c,b,Ze()])}}function qf(a){Y&&of(a,1)}function rf(a){Y&&of(a,0)}
function sf(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);Y&&Y.ef&&a.target==g.canvas&&(lf.apply(null,[Y.ef,Y.id,"mousewheel"==a.type?a.wheelDeltaX:a.deltaX,b]),a.preventDefault())}
var tf={},uf=[],vf=null;
function df(){if(we!==vf||!we){uf=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];vf=we;for(var a=0;a<uf.length;++a){var b=uf[a];if(b){tf[a]||(ia("glfw joystick connected:",a),tf[a]={id:vd(b.id),sg:b.buttons.length,qg:b.axes.length,buttons:T(b.buttons.length),axes:T(4*b.axes.length)});for(var c=tf[a],d=0;d<b.buttons.length;++d)t[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)A[c.axes+4*d>>2]=b.axes[d]}else tf[a]&&(ia("glfw joystick disconnected",
a),wf(tf[a].id),wf(tf[a].buttons),wf(tf[a].axes),delete tf[a])}}}
function xf(a){function b(l){var r="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=p=>{if(2!=q.readyState)++f,ia("failed to read dropped file: "+l.name+": "+q.error);else{var u=new Uint8Array(p.target.result);p={};p.flags=p.flags||577;var y=Gb(r,p.flags,p.mode);if("string"==typeof u){var E=new Uint8Array(Sa(u)+1);u=F(u,E,0,E.length);Jb(y,E,0,u,void 0,p.Vf)}else if(ArrayBuffer.isView(u))Jb(y,u,0,u.byteLength,void 0,p.Vf);else throw Error("Unsupported data type");Hb(y);
if(++f===e){yf.apply(null,[Y.Oe,Y.id,e,c]);for(p=0;p<d.length;++p)wf(d[p]);wf(c)}}};q.readAsArrayBuffer(l);var v=vd(r);d.push(v);z[c+4*h>>2]=v}if(Y&&Y.Oe&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=T(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;Mb("/",".glfw_dropped_files");for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function zf(a){if(Y&&Y.Oe)return a.preventDefault(),!1}
function Af(a){try{a()}catch(b){m(b)}}function Bf(a){var b={},c;for(c in a)(function(d){var e=a[d];b[d]="function"==typeof e?function(){Cf.push(d);try{return e.apply(null,arguments)}finally{n||(Cf.pop()===d||m(),Df&&1===Ef&&0===Cf.length&&(Ef=0,Af(Ff),"undefined"!=typeof Fibers&&Fibers.Ng()))}}:e})(c);return b}var Ef=0,Df=null,Gf=0,Cf=[],Hf={},If={},Jf=0,Kf=null,Lf=[];
function Mf(){var a=T(4108),b=a+12;x[a>>2]=b;x[a+4>>2]=b+4096;b=Cf[0];var c=Hf[b];void 0===c&&(c=Jf++,Hf[b]=c,If[c]=b);x[a+8>>2]=c;return a}
function Nf(a){if(!n){if(0===Ef){var b=!1,c=!1;a((d=0)=>{if(!n&&(Gf=d,b=!0,c)){Ef=2;Af(()=>Of(Df));"undefined"!=typeof gb&&le&&xe();d=!1;try{var e=(0,g.asm[If[x[Df+8>>2]]])()}catch(l){e=l,d=!0}var f=!1;if(!Df){var h=Kf;h&&(Kf=null,(d?h.reject:h.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Ef=1,Df=Mf(),"undefined"!=typeof gb&&le&&(ne=null,se++),Af(()=>Pf(Df)))}else 2===Ef?(Ef=0,Af(Qf),wf(Df),Df=null,Lf.forEach(d=>ge(d))):m(`invalid state: ${Ef}`);return Gf}}
function ub(a,b,c,d){a||(a=this);this.parent=a;this.De=a.De;this.Qe=null;this.id=ob++;this.name=b;this.mode=c;this.te={};this.ue={};this.df=d}Object.defineProperties(ub.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},bg:{get:function(){return 16384===(this.mode&61440)}},Cf:{get:function(){return 8192===(this.mode&61440)}}});Kb();
I=Array(4096);Ab(H,"/");K("/tmp",16895,0);K("/home",16895,0);K("/home/web_user",16895,0);(()=>{K("/dev",16895,0);Wa(259,{read:()=>0,write:(d,e,f,h)=>h});Bb("/dev/null",259);Va(1280,Ya);Va(1536,Za);Bb("/dev/tty",1280);Bb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Qa(a).byteLength);return a[--b]};L("/dev","random",c);L("/dev","urandom",c);K("/dev/shm",16895,0);K("/dev/shm/tmp",16895,0)})();
(()=>{K("/proc",16895,0);var a=K("/proc/self",16895,0);K("/proc/self/fd",16895,0);Ab({De:()=>{var b=ab(a,"fd",16895,73);b.te={Pe:(c,d)=>{var e=nb[+d];if(!e)throw new G(8);c={parent:null,De:{Ef:"fake"},te:{Re:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=Mb;g.FS_createDataFile=jb;g.FS_createPreloadedFile=ib;g.FS_unlink=Db;g.FS_createLazyFile=Pb;g.FS_createDevice=L;for(var S,Z=0;32>Z;++Z)bd.push(Array(Z));var Rf=new Float32Array(288);
for(Z=0;288>Z;++Z)Kd[Z]=Rf.subarray(0,Z+1);var Sf=new Int32Array(288);for(Z=0;288>Z;++Z)Nd[Z]=Sf.subarray(0,Z+1);g.requestFullscreen=function(a,b){He(a,b)};g.requestAnimationFrame=function(a){qe(a)};g.setCanvasSize=function(a,b,c){Se(a,b,c)};g.pauseMainLoop=function(){ne=null;se++};g.resumeMainLoop=function(){xe()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return De(a,b,c,d)};
var Vf={e:function(a,b,c,d){m(`Assertion failed: ${C(a)}, at: `+[b?C(b):"unknown filename",c,d?C(d):"unknown function"])},A:function(a,b,c){Qb=c;try{var d=Sb(a);switch(b){case 0:var e=Rb();return 0>e?-28:zb(d,e).Ee;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Rb(),d.flags|=e,0;case 5:return e=Rb(),ma[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return x[Tf()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.Ce}},
Pa:function(a,b){try{if(0===b)return-28;var c=Sa("/")+1;if(b<c)return-68;F("/",w,a,b);return c}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.Ce}},Sa:function(a,b,c){Qb=c;try{var d=Sb(a);switch(b){case 21509:case 21505:return d.we?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.we?0:-59;case 21519:if(!d.we)return-59;var e=Rb();return x[e>>2]=0;case 21520:return d.we?-28:-59;case 21531:a=e=Rb();if(!d.ue.ag)throw new G(59);return d.ue.ag(d,
b,a);case 21523:return d.we?0:-59;case 21524:return d.we?0:-59;default:return-28}}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.Ce}},Ta:function(a,b,c,d){Qb=d;try{b=C(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Sb(a).path;if(0==e.length)throw new G(44);b=D(f+"/"+e)}var h=d?Rb():0;return Gb(b,c,h).Ee}catch(l){if("undefined"==typeof M||"ErrnoError"!==l.name)throw l;return-l.Ce}},Ua:function(){return Date.now()},U:function(a,b,c){a=hc(a);if(!a)return-4;a=ic(a);
B[b>>3]=a.width;B[c>>3]=a.height;return 0},N:function(a,b){if(0>a||a>=ac.length)return-5;if(!ac[a])return-7;jc(b,ac[a]);return 0},B:kc,O:function(){return ac.length},Kd:Fc,Jd:Gc,_d:function(a,b){S.Be.beginQueryEXT(a,Q[b])},Id:Hc,Hd:Ic,Gd:function(a,b){S.bindFramebuffer(a,rc[b])},Fd:function(a,b){S.bindRenderbuffer(a,sc[b])},Ed:Jc,Sd:function(a){S.bindVertexArray(uc[a])},Dd:function(a,b,c,d){S.blendColor(a,b,c,d)},Cd:function(a){S.blendEquation(a)},Bd:function(a,b){S.blendEquationSeparate(a,b)},Ad:Kc,
zd:function(a,b,c,d){S.blendFuncSeparate(a,b,c,d)},yd:Lc,xd:Mc,wd:function(a){return S.checkFramebufferStatus(a)},vd:Nc,ud:Oc,td:Pc,sd:function(a){S.clearStencil(a)},rd:function(a,b,c,d){S.colorMask(!!a,!!b,!!c,!!d)},qd:Qc,pd:Rc,od:function(a,b,c,d,e,f,h,l,r){S.compressedTexSubImage2D(a,b,c,d,e,f,h,r?w.subarray(r,r+l):null)},nd:function(a,b,c,d,e,f,h,l){S.copyTexImage2D(a,b,c,d,e,f,h,l)},ld:function(a,b,c,d,e,f,h,l){S.copyTexSubImage2D(a,b,c,d,e,f,h,l)},kd:Sc,jd:Tc,id:Uc,hd:Vc,gd:function(a,b){for(var c=
0;c<a;++c){var d=x[b+4*c>>2],e=rc[d];e&&(S.deleteFramebuffer(e),e.name=0,rc[d]=null)}},fd:Wc,K:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(S.Be.deleteQueryEXT(e),Q[d]=null)}},ed:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=sc[d];e&&(S.deleteRenderbuffer(e),e.name=0,sc[d]=null)}},dd:Xc,cd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=tc[d];e&&(S.deleteTexture(e),e.name=0,tc[d]=null)}},Rd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];S.deleteVertexArray(uc[d]);
uc[d]=null}},bd:Yc,ad:function(a){S.depthMask(!!a)},$c:function(a,b){S.depthRange(a,b)},_c:Zc,Zc:$c,Yc:function(a){S.disableVertexAttribArray(a)},Xc:ad,Nd:function(a,b,c,d){S.drawArraysInstanced(a,b,c,d)},Od:function(a,b){for(var c=bd[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];S.drawBuffers(c)},Wc:cd,Md:function(a,b,c,d,e){S.drawElementsInstanced(a,b,c,d,e)},Vc:dd,Uc:ed,Zd:function(a){S.Be.endQueryEXT(a)},Tc:function(){S.finish()},Sc:function(){S.flush()},Rc:function(a,b,c,d){S.framebufferRenderbuffer(a,b,c,
sc[d])},Qc:function(a,b,c,d,e){S.framebufferTexture2D(a,b,c,tc[d],e)},Pc:fd,Oc:hd,Mc:function(a,b){gd(a,b,"createFramebuffer",rc)},L:function(a,b){for(var c=0;c<a;c++){var d=S.Be.createQueryEXT();if(!d){for(R(1282);c<a;)x[b+4*c++>>2]=0;break}var e=zc(Q);d.name=e;Q[e]=d;x[b+4*c>>2]=e}},Lc:function(a,b){gd(a,b,"createRenderbuffer",sc)},Kc:jd,Qd:function(a,b){gd(a,b,"createVertexArray",uc)},Nc:function(a){S.generateMipmap(a)},Jc:function(a,b,c,d,e,f,h){kd("getActiveAttrib",a,b,c,d,e,f,h)},Ic:function(a,
b,c,d,e,f,h){kd("getActiveUniform",a,b,c,d,e,f,h)},Hc:function(a,b,c,d){a=S.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=P.indexOf(a[b])},Gc:ld,Fc:function(a,b){nd(a,b,4)},Ec:function(a,b,c){c?x[c>>2]=S.getBufferParameter(a,b):R(1281)},Dc:function(){var a=S.getError()||yc;yc=0;return a},Cc:od,Bc:function(a,b,c,d){a=S.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},Ac:function(a,
b){nd(a,b,0)},xc:pd,yc:qd,Ud:rd,Wd:sd,Td:rd,Vd:sd,Xd:function(a,b,c){c?x[c>>2]=S.Be.getQueryEXT(a,b):R(1281)},wc:function(a,b,c){c?x[c>>2]=S.getRenderbufferParameter(a,b):R(1281)},uc:td,tc:function(a,b,c,d){a=S.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},sc:function(a,b,c,d){if(a=S.getShaderSource(P[a]))b=0<b&&d?F(a,w,d,b):0,c&&(x[c>>2]=b)},vc:ud,rc:wd,qc:function(a,b,c){c?A[c>>2]=S.getTexParameter(a,b):R(1281)},pc:function(a,b,c){c?x[c>>2]=S.getTexParameter(a,
b):R(1281)},lc:zd,nc:function(a,b,c){Ad(a,b,c,2)},mc:function(a,b,c){Ad(a,b,c,0)},ic:function(a,b,c){c?x[c>>2]=S.getVertexAttribOffset(a,b):R(1281)},kc:function(a,b,c){Bd(a,b,c,2)},jc:function(a,b,c){Bd(a,b,c,5)},hc:function(a,b){S.hint(a,b)},gc:function(a){return(a=qc[a])?S.isBuffer(a):0},fc:function(a){return S.isEnabled(a)},ec:function(a){return(a=rc[a])?S.isFramebuffer(a):0},bc:function(a){return(a=O[a])?S.isProgram(a):0},J:function(a){return(a=Q[a])?S.Be.isQueryEXT(a):0},ac:function(a){return(a=
sc[a])?S.isRenderbuffer(a):0},$b:function(a){return(a=P[a])?S.isShader(a):0},_b:function(a){return(a=tc[a])?S.isTexture(a):0},Pd:function(a){return(a=uc[a])?S.isVertexArray(a):0},Zb:function(a){S.lineWidth(a)},Yb:Cd,Xb:Dd,Wb:function(a,b){S.polygonOffset(a,b)},Yd:function(a,b){S.Be.queryCounterEXT(Q[a],b)},Vb:Fd,Ub:function(){},Tb:function(a,b,c,d){S.renderbufferStorage(a,b,c,d)},Sb:function(a,b){S.sampleCoverage(a,!!b)},Rb:function(a,b,c,d){S.scissor(a,b,c,d)},Qb:function(){R(1280)},Pb:Gd,Ob:function(a,
b,c){S.stencilFunc(a,b,c)},Nb:function(a,b,c,d){S.stencilFuncSeparate(a,b,c,d)},Mb:function(a){S.stencilMask(a)},Lb:function(a,b){S.stencilMaskSeparate(a,b)},Kb:function(a,b,c){S.stencilOp(a,b,c)},Jb:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},Ib:Hd,Hb:Id,Gb:function(a,b,c){S.texParameterf(a,b,A[c>>2])},Fb:Jd,Eb:function(a,b,c){S.texParameteri(a,b,x[c>>2])},Db:function(a,b,c,d,e,f,h,l,r){var q=null;r&&(q=Ed(l,h,e,f,r));S.texSubImage2D(a,b,c,d,e,f,h,l,q)},Cb:function(a,b){S.uniform1f(U(a),b)},
Bb:Ld,Ab:Md,yb:Od,xb:function(a,b,c){S.uniform2f(U(a),b,c)},wb:Pd,vb:function(a,b,c){S.uniform2i(U(a),b,c)},ub:Qd,tb:function(a,b,c,d){S.uniform3f(U(a),b,c,d)},sb:Rd,rb:function(a,b,c,d){S.uniform3i(U(a),b,c,d)},qb:Sd,pb:Td,nb:Ud,mb:function(a,b,c,d,e){S.uniform4i(U(a),b,c,d,e)},lb:Vd,kb:function(a,b,c,d){if(72>=b)for(var e=Kd[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);S.uniformMatrix2fv(U(a),!!c,e)},
jb:function(a,b,c,d){if(32>=b)for(var e=Kd[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);S.uniformMatrix3fv(U(a),!!c,e)},ib:Wd,hb:Xd,gb:function(a){S.validateProgram(O[a])},fb:function(a,b){S.vertexAttrib1f(a,b)},eb:function(a,b){S.vertexAttrib1f(a,A[b>>2])},cb:function(a,b,c){S.vertexAttrib2f(a,
b,c)},bb:function(a,b){S.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},ab:function(a,b,c,d){S.vertexAttrib3f(a,b,c,d)},$a:function(a,b){S.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},_a:function(a,b,c,d,e){S.vertexAttrib4f(a,b,c,d,e)},Za:function(a,b){S.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},Ld:function(a,b){S.vertexAttribDivisor(a,b)},Ya:Yd,Xa:Zd,Wa:function(a,b,c){w.copyWithin(a,b,b+c)},Na:function(a){var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ka.buffer.byteLength+65535>>>16;try{ka.grow(e);pa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},q:function(a){eval(C(a))},P:function(){return(ac=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},qa:function(a,b,c,d){return $d(a,b,c,d)},ra:function(a,b,c,d){if(!document.fullscreenEnabled&&!document.webkitFullscreenEnabled)return-1;
a=hc(a);if(!a)return-4;be(a,b,c,d,"webkitfullscreenchange");return be(a,b,c,d,"fullscreenchange")},la:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?ce(a,b,c,26,"gamepadconnected"):-1},ka:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?ce(a,b,c,27,"gamepaddisconnected"):-1},ma:function(a,b,c,d){return de(a,b,c,d,25,"touchcancel")},oa:function(a,b,c,d){return de(a,b,c,d,23,"touchend")},na:function(a,b,c,d){return de(a,b,c,d,24,"touchmove")},pa:function(a,
b,c,d){return de(a,b,c,d,22,"touchstart")},T:function(a){return Nf(b=>he(b,a))},I:fe,C:function(a){try{var b=Sb(a);Hb(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.Ce}},Ra:function(a,b,c,d){try{a:{var e=Sb(a);a=b;for(var f,h=b=0;h<c;h++){var l=z[a>>2],r=z[a+4>>2];a+=8;var q=e,v=l,p=r,u=f,y=t;if(0>p||0>u)throw new G(28);if(null===q.Ee)throw new G(8);if(1===(q.flags&2097155))throw new G(8);if(16384===(q.node.mode&61440))throw new G(31);if(!q.ue.read)throw new G(28);
var E="undefined"!=typeof u;if(!E)u=q.position;else if(!q.seekable)throw new G(70);var fa=q.ue.read(q,y,v,p,u);E||(q.position+=fa);var ha=fa;if(0>ha){var gf=-1;break a}b+=ha;if(ha<r)break;"undefined"!==typeof f&&(f+=ha)}gf=b}z[d>>2]=gf;return 0}catch(lc){if("undefined"==typeof M||"ErrnoError"!==lc.name)throw lc;return lc.Ce}},Oa:function(a,b,c,d){try{b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);if(isNaN(b))return 61;var e=Sb(a);Ib(e,b,c);oa[d>>3]=BigInt(e.position);e.qf&&0===b&&0===c&&
(e.qf=null);return 0}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return f.Ce}},Qa:function(a,b,c,d){try{a:{var e=Sb(a);a=b;for(var f,h=b=0;h<c;h++){var l=z[a>>2],r=z[a+4>>2];a+=8;var q=Jb(e,t,l,r,f);if(0>q){var v=-1;break a}b+=q;"undefined"!==typeof f&&(f+=q)}v=b}z[d>>2]=v;return 0}catch(p){if("undefined"==typeof M||"ErrnoError"!==p.name)throw p;return p.Ce}},H:Fc,v:Gc,h:Hc,b:Ic,d:Jc,zb:Kc,j:Lc,m:Mc,D:Nc,E:Oc,Va:Pc,Ea:Qc,Ja:Rc,Ca:Sc,Ga:Tc,oc:Uc,Ia:Vc,x:Wc,y:Xc,ob:Yc,z:Zc,zc:$c,
G:ad,md:cd,F:dd,f:ed,db:fd,k:hd,La:jd,o:ld,cc:od,Aa:pd,u:qd,Da:td,w:ud,i:wd,n:zd,Ba:Cd,Ma:Dd,Ha:Fd,Fa:Gd,Ka:Hd,p:Id,c:Jd,za:Ld,$d:Md,t:Od,ya:Pd,va:Qd,xa:Rd,ua:Sd,S:Td,wa:Ud,ta:Vd,sa:Wd,l:Xd,g:Yd,dc:Zd,r:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?He():Se(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<V[139265];e==X.length&&(d?g.Me=De(g.canvas,!0,!0,{antialias:1<V[135181],depth:0<
V[135173],stencil:0<V[135174],alpha:0<V[135172]}):hb());!g.Me&&d?f=0:(a=new Te(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},ha:function(){V=Xe},s:function(){return 1},R:function(){return kc()/1E3-We},ga:function(a,b){return x[b>>2]=0},ia:function(){if(X)return 1;We=kc()/1E3;V=Xe;X=[];Y=null;Ve=devicePixelRatio;window.addEventListener("gamepadconnected",cf,!0);window.addEventListener("gamepaddisconnected",ef,!0);window.addEventListener("keydown",ff,!0);window.addEventListener("keypress",
$e,!0);window.addEventListener("keyup",hf,!0);window.addEventListener("blur",jf,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});Ve=devicePixelRatio;Y&&Y.Rf&&Uf.apply(null,[Y.Rf,Y.id,Ve,Ve])})();g.canvas.addEventListener("touchmove",kf,!0);g.canvas.addEventListener("touchstart",qf,!0);g.canvas.addEventListener("touchcancel",rf,!0);g.canvas.addEventListener("touchend",rf,!0);g.canvas.addEventListener("mousemove",kf,!0);g.canvas.addEventListener("mousedown",
qf,!0);g.canvas.addEventListener("mouseup",rf,!0);g.canvas.addEventListener("wheel",sf,!0);g.canvas.addEventListener("mousewheel",sf,!0);g.canvas.addEventListener("mouseenter",mf,!0);g.canvas.addEventListener("mouseleave",nf,!0);g.canvas.addEventListener("drop",xf,!0);g.canvas.addEventListener("dragover",zf,!0);Re.push((b,c)=>{if(Y){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.Nf=Y.x,Y.Of=Y.y,Y.Mf=Y.width,Y.Lf=Y.height,Y.x=Y.y=0,Y.width=
screen.width,Y.height=screen.height,Y.pf=!0):1==Y.pf?(Y.x=Y.Nf,Y.y=Y.Of,Y.width=Y.Mf,Y.height=Y.Lf,Y.pf=!1):Y.width!=b||Y.height!=c?(Y.width=b,Y.height=c):d=!1;d&&(Se(Y.width,Y.height,!0),Y&&Y.hf&&yf.apply(null,[Y.hf,Y.id,Y.width,Y.height]),Y&&Y.zf&&yf.apply(null,[Y.zf,Y.id,Y.width,Y.height]))}});return 1},W:function(){},$:function(a,b){if(a=W(a)){var c=a.Ve;a.Ve=b;b=c}else b=null;return b},X:function(a,b){a=W(a);if(!a)return null;var c=a.Ie;a.Ie=b;return c},Z:function(a,b){if(a=W(a)){var c=a.Ne;
a.Ne=b;b=c}else b=null;return b},ba:function(a,b){if(a=W(a)){var c=a.Oe;a.Oe=b;b=c}else b=null;return b},ja:function(a){var b=Ue;Ue=a;return b},aa:function(a,b){if(a=W(a)){var c=a.Ye;a.Ye=b;b=c}else b=null;return b},_:function(a,b){if(a=W(a)){var c=a.cf;a.cf=b;b=c}else b=null;return b},Y:function(a,b){if(a=W(a)){var c=a.ef;a.ef=b;b=c}else b=null;return b},ca:function(a,b){a=W(a);if(!a)return null;var c=a.Sf;a.Sf=b;return c},da:function(a,b){a=W(a);if(!a)return null;var c=a.Tf;a.Tf=b;return c},M:function(a,
b){if(a=W(a))a.hg=b},ea:function(a,b){if(a=W(a)){var c=a.hf;a.hf=b;b=c}else b=null;return b},Q:function(){},V:function(a){a=Math.abs(a);0==a?ie(0,0):ie(1,a)},fa:function(){window.removeEventListener("gamepadconnected",cf,!0);window.removeEventListener("gamepaddisconnected",ef,!0);window.removeEventListener("keydown",ff,!0);window.removeEventListener("keypress",$e,!0);window.removeEventListener("keyup",hf,!0);window.removeEventListener("blur",jf,!0);g.canvas.removeEventListener("touchmove",kf,!0);
g.canvas.removeEventListener("touchstart",qf,!0);g.canvas.removeEventListener("touchcancel",rf,!0);g.canvas.removeEventListener("touchend",rf,!0);g.canvas.removeEventListener("mousemove",kf,!0);g.canvas.removeEventListener("mousedown",qf,!0);g.canvas.removeEventListener("mouseup",rf,!0);g.canvas.removeEventListener("wheel",sf,!0);g.canvas.removeEventListener("mousewheel",sf,!0);g.canvas.removeEventListener("mouseenter",mf,!0);g.canvas.removeEventListener("mouseleave",nf,!0);g.canvas.removeEventListener("drop",
xf,!0);g.canvas.removeEventListener("dragover",zf,!0);g.canvas.width=g.canvas.height=1;Y=X=null},a:function(a,b){V[a]=b}};(function(){function a(c){c=c.exports;c=Bf(c);g.asm=c;ka=g.asm.ae;pa();ra.unshift(g.asm.be);Aa("wasm-instantiate");return c}var b={a:Vf};za("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}Ha(b,function(c){a(c.instance)});return{}})();
var Wf=g._main=function(){return(Wf=g._main=g.asm.ce).apply(null,arguments)};function T(){return(T=g.asm.de).apply(null,arguments)}function wf(){return(wf=g.asm.ee).apply(null,arguments)}function Tf(){return(Tf=g.asm.ge).apply(null,arguments)}
var ae=g.dynCall_iiii=function(){return(ae=g.dynCall_iiii=g.asm.he).apply(null,arguments)},dynCall_vii=g.dynCall_vii=function(){return(dynCall_vii=g.dynCall_vii=g.asm.ie).apply(null,arguments)},yf=g.dynCall_viii=function(){return(yf=g.dynCall_viii=g.asm.je).apply(null,arguments)},bf=g.dynCall_viiiii=function(){return(bf=g.dynCall_viiiii=g.asm.ke).apply(null,arguments)},pf=g.dynCall_viiii=function(){return(pf=g.dynCall_viiii=g.asm.le).apply(null,arguments)},lf=g.dynCall_vidd=function(){return(lf=g.dynCall_vidd=
g.asm.me).apply(null,arguments)},dynCall_vi=g.dynCall_vi=function(){return(dynCall_vi=g.dynCall_vi=g.asm.ne).apply(null,arguments)},Uf=g.dynCall_viff=function(){return(Uf=g.dynCall_viff=g.asm.oe).apply(null,arguments)};function Pf(){return(Pf=g.asm.pe).apply(null,arguments)}function Ff(){return(Ff=g.asm.qe).apply(null,arguments)}function Of(){return(Of=g.asm.re).apply(null,arguments)}function Qf(){return(Qf=g.asm.se).apply(null,arguments)}g.___start_em_js=20736;g.___stop_em_js=20811;
g.addRunDependency=za;g.removeRunDependency=Aa;g.FS_createPath=Mb;g.FS_createDataFile=jb;g.FS_createLazyFile=Pb;g.FS_createDevice=L;g.FS_unlink=Db;g.FS_createPreloadedFile=ib;var Xf;ya=function Yf(){Xf||Zf();Xf||(ya=Yf)};
function Zf(){function a(){if(!Xf&&(Xf=!0,g.calledRun=!0,!n)){g.noFSInit||Lb||(Lb=!0,Kb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?L("/dev","stdin",g.stdin):Cb("/dev/tty","/dev/stdin"),g.stdout?L("/dev","stdout",null,g.stdout):Cb("/dev/tty","/dev/stdout"),g.stderr?L("/dev","stderr",null,g.stderr):Cb("/dev/tty1","/dev/stderr"),Gb("/dev/stdin",0),Gb("/dev/stdout",1),Gb("/dev/stderr",1));pb=!1;Ja(ra);Ja(sa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if($f){var b=Wf;try{var c=
b(0,0);fe(c,!0)}catch(d){ee(d)}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)b=g.postRun.shift(),ua.unshift(b);Ja(ua)}}if(!(0<wa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)va();Ja(qa);0<wa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();
var $f=!0;g.noInitialRun&&($f=!1);Zf();
