var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=(a,b)=>{throw b;},ca="",da,ea,fa;"undefined"!=typeof document&&document.currentScript&&(ca=document.currentScript.src);ca=0!==ca.indexOf("blob:")?ca.substr(0,ca.replace(/[?#].*/,"").lastIndexOf("/")+1):"";da=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
ea=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};fa=a=>{document.title=a};var ha=f.print||console.log.bind(console),k=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.quit&&(ba=f.quit);var ia;f.wasmBinary&&(ia=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&l("no native wasm support detected");
var ja,n,p=!1,ka,u,w,la,ma,x,y,A,na,B;function oa(){var a=ja.buffer;f.HEAP8=u=new Int8Array(a);f.HEAP16=la=new Int16Array(a);f.HEAP32=x=new Int32Array(a);f.HEAPU8=w=new Uint8Array(a);f.HEAPU16=ma=new Uint16Array(a);f.HEAPU32=y=new Uint32Array(a);f.HEAPF32=A=new Float32Array(a);f.HEAPF64=B=new Float64Array(a);f.HEAP64=na=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var pa=[],qa=[],ra=[],sa=[],ta=[];function ua(){var a=f.preRun.shift();pa.unshift(a)}var va=0,wa=null,xa=null;
function ya(){va++;f.monitorRunDependencies&&f.monitorRunDependencies(va)}function za(){va--;f.monitorRunDependencies&&f.monitorRunDependencies(va);if(0==va&&(null!==wa&&(clearInterval(wa),wa=null),xa)){var a=xa;xa=null;a()}}function l(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";k(a);p=!0;ka=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Aa(a){return a.startsWith("data:application/octet-stream;base64,")}var Ba;Ba="index.wasm";
if(!Aa(Ba)){var Ca=Ba;Ba=f.locateFile?f.locateFile(Ca,ca):ca+Ca}function Da(a){if(a==Ba&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}function Ea(a){return ia||"function"!=typeof fetch?Promise.resolve().then(()=>Da(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Da(a))}
function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{k("failed to asynchronously prepare wasm: "+d);l(d)})}function Ga(a,b){var c=Ba;ia||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k("wasm streaming compile failed: "+e);k("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}
function Ha(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ia=a=>{for(;0<a.length;)a.shift()(f)},Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,C=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d},Ka=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},D=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=
240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},E=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ma=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=
b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Na=a=>{if("/"===a)return"/";a=E(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Oa=(a,b)=>E(a+"/"+b),Pa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);l("initRandomDevice")},Qa=a=>(Qa=Pa())(a);
function Ra(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:F.Ff();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=La(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Sa=(a,b)=>{function c(h){for(var m=0;m<h.length&&""===h[m];m++);for(var q=h.length-1;0<=q&&""===h[q];q--);return m>q?[]:h.slice(m,q-m+1)}a=Ra(a).substr(1);b=Ra(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ta=[];function Ua(a){var b=Array(Ka(a)+1);a=D(a,b,0,b.length);b.length=a;return b}var Va=[];
function Wa(a,b){Va[a]={input:[],Ke:[],Xe:b};F.ng(a,Xa)}
var Xa={open:function(a){var b=Va[a.node.Rf];if(!b)throw new F.oe(43);a.Ee=b;a.seekable=!1},close:function(a){a.Ee.Xe.Gf(a.Ee)},Gf:function(a){a.Ee.Xe.Gf(a.Ee)},read:function(a,b,c,d){if(!a.Ee||!a.Ee.Xe.Ag)throw new F.oe(60);for(var e=0,g=0;g<d;g++){try{var h=a.Ee.Xe.Ag(a.Ee)}catch(m){throw new F.oe(29);}if(void 0===h&&0===e)throw new F.oe(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Ee||!a.Ee.Xe.kg)throw new F.oe(60);try{for(var e=
0;e<d;e++)a.Ee.Xe.kg(a.Ee,b[c+e])}catch(g){throw new F.oe(29);}d&&(a.node.timestamp=Date.now());return e}},Ya={Ag:function(){a:{if(!Ta.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Ta=Ua(a)}a=Ta.shift()}return a},kg:function(a,b){null===b||10===b?(ha(C(a.Ke,0)),a.Ke=[]):0!=b&&a.Ke.push(b)},Gf:function(a){a.Ke&&0<a.Ke.length&&(ha(C(a.Ke,
0)),a.Ke=[])},oh:function(){return{Th:25856,Vh:5,Sh:191,Uh:35387,Rh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ph:function(){return 0},qh:function(){return[24,80]}},Za={kg:function(a,b){null===b||10===b?(k(C(a.Ke,0)),a.Ke=[]):0!=b&&a.Ke.push(b)},Gf:function(a){a.Ke&&0<a.Ke.length&&(k(C(a.Ke,0)),a.Ke=[])}};
function $a(a,b){var c=a.Ce?a.Ce.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ce,a.Ce=new Uint8Array(b),0<a.Ge&&a.Ce.set(c.subarray(0,a.Ge),0))}
var G={Te:null,He(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(F.rh(c)||F.sh(c))throw new F.oe(63);G.Te||(G.Te={dir:{node:{Qe:G.Be.Qe,Je:G.Be.Je,bf:G.Be.bf,We:G.Be.We,zf:G.Be.zf,hf:G.Be.hf,Af:G.Be.Af,yf:G.Be.yf,Ze:G.Be.Ze},stream:{Re:G.De.Re}},file:{node:{Qe:G.Be.Qe,Je:G.Be.Je},stream:{Re:G.De.Re,read:G.De.read,write:G.De.write,mf:G.De.mf,kf:G.De.kf,xf:G.De.xf}},link:{node:{Qe:G.Be.Qe,Je:G.Be.Je,gf:G.Be.gf},stream:{}},qg:{node:{Qe:G.Be.Qe,Je:G.Be.Je},stream:F.Xg}});c=F.createNode(a,
b,c,d);F.Ie(c.mode)?(c.Be=G.Te.dir.node,c.De=G.Te.dir.stream,c.Ce={}):F.isFile(c.mode)?(c.Be=G.Te.file.node,c.De=G.Te.file.stream,c.Ge=0,c.Ce=null):F.uf(c.mode)?(c.Be=G.Te.link.node,c.De=G.Te.link.stream):F.If(c.mode)&&(c.Be=G.Te.qg.node,c.De=G.Te.qg.stream);c.timestamp=Date.now();a&&(a.Ce[b]=c,a.timestamp=c.timestamp);return c},fi(a){return a.Ce?a.Ce.subarray?a.Ce.subarray(0,a.Ge):new Uint8Array(a.Ce):new Uint8Array(0)},Be:{Qe(a){var b={};b.Zh=F.If(a.mode)?a.id:1;b.hi=a.id;b.mode=a.mode;b.ui=1;b.uid=
0;b.gi=0;b.Rf=a.Rf;F.Ie(a.mode)?b.size=4096:F.isFile(a.mode)?b.size=a.Ge:F.uf(a.mode)?b.size=a.link.length:b.size=0;b.Nh=new Date(a.timestamp);b.ri=new Date(a.timestamp);b.Yh=new Date(a.timestamp);b.Vg=4096;b.Ph=Math.ceil(b.size/b.Vg);return b},Je(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Ge!=b))if(0==b)a.Ce=null,a.Ge=0;else{var c=a.Ce;a.Ce=new Uint8Array(b);c&&a.Ce.set(c.subarray(0,Math.min(b,a.Ge)));a.Ge=b}},bf(){throw F.dg[44];
},We(a,b,c,d){return G.createNode(a,b,c,d)},zf(a,b,c){if(F.Ie(a.mode)){try{var d=F.Ve(b,c)}catch(g){}if(d)for(var e in d.Ce)throw new F.oe(55);}delete a.parent.Ce[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ce[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},hf(a,b){delete a.Ce[b];a.timestamp=Date.now()},Af(a,b){var c=F.Ve(a,b),d;for(d in c.Ce)throw new F.oe(55);delete a.Ce[b];a.timestamp=Date.now()},yf(a){var b=[".",".."],c;for(c in a.Ce)a.Ce.hasOwnProperty(c)&&b.push(c);return b},Ze(a,b,c){a=
G.createNode(a,b,41471,0);a.link=c;return a},gf(a){if(!F.uf(a.mode))throw new F.oe(28);return a.link}},De:{read(a,b,c,d,e){var g=a.node.Ce;if(e>=a.node.Ge)return 0;a=Math.min(a.node.Ge-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===u.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ce||a.Ce.subarray)){if(g)return a.Ce=b.subarray(c,c+d),a.Ge=d;if(0===a.Ge&&0===e)return a.Ce=b.slice(c,c+d),
a.Ge=d;if(e+d<=a.Ge)return a.Ce.set(b.subarray(c,c+d),e),d}$a(a,e+d);if(a.Ce.subarray&&b.subarray)a.Ce.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Ce[e+g]=b[c+g];a.Ge=Math.max(a.Ge,e+d);return d},Re(a,b,c){1===c?b+=a.position:2===c&&F.isFile(a.node.mode)&&(b+=a.node.Ge);if(0>b)throw new F.oe(28);return b},mf(a,b,c){$a(a.node,b+c);a.node.Ge=Math.max(a.node.Ge,b+c)},kf(a,b,c,d,e){if(!F.isFile(a.node.mode))throw new F.oe(43);a=a.node.Ce;if(e&2||a.buffer!==u.buffer){if(0<c||c+b<a.length)a.subarray?
a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;l();b=void 0;if(!b)throw new F.oe(48);u.set(a,b)}else c=!1,b=a.byteOffset;return{yi:b,Kh:c}},xf(a,b,c,d){G.De.write(a,b,0,d,c,!1);return 0}}},ab=(a,b,c)=>{var d=`al ${a}`;ea(a,e=>{e||l(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&za(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&ya(d)},bb=f.preloadPlugins||[];
function cb(a,b,c,d){"undefined"!=typeof db&&eb();var e=!1;bb.forEach(function(g){!e&&g.canHandle(b)&&(g.handle(a,b,c,d),e=!0)});return e}function fb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var F={root:null,wf:[],ug:{},streams:[],xh:1,Se:null,tg:"/",gg:!1,Dg:!0,oe:null,dg:{},jh:null,Tf:0,Fe:(a,b={})=>{a=Ra(a);if(!a)return{path:"",node:null};b=Object.assign({ag:!0,mg:0},b);if(8<b.mg)throw new F.oe(32);a=a.split("/").filter(h=>!!h);for(var c=F.root,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=F.Ve(c,a[e]);d=E(d+"/"+a[e]);F.af(c)&&(!g||g&&b.ag)&&(c=c.vf.root);if(!g||b.Oe)for(g=0;F.uf(c.mode);)if(c=F.gf(d),d=Ra(Ma(d),c),c=F.Fe(d,{mg:b.mg+1}).node,40<g++)throw new F.oe(32);
}return{path:d,node:c}},$e:a=>{for(var b;;){if(F.Jf(a))return a=a.He.Gg,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},fg:(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%F.Se.length},Bg:a=>{var b=F.fg(a.parent.id,a.name);a.df=F.Se[b];F.Se[b]=a},Cg:a=>{var b=F.fg(a.parent.id,a.name);if(F.Se[b]===a)F.Se[b]=a.df;else for(b=F.Se[b];b;){if(b.df===a){b.df=a.df;break}b=b.df}},Ve:(a,b)=>{var c=F.vh(a);if(c)throw new F.oe(c,a);for(c=F.Se[F.fg(a.id,
b)];c;c=c.df){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return F.bf(a,b)},createNode:(a,b,c,d)=>{a=new F.Sg(a,b,c,d);F.Bg(a);return a},Zf:a=>{F.Cg(a)},Jf:a=>a===a.parent,af:a=>!!a.vf,isFile:a=>32768===(a&61440),Ie:a=>16384===(a&61440),uf:a=>40960===(a&61440),If:a=>8192===(a&61440),rh:a=>24576===(a&61440),sh:a=>4096===(a&61440),ii:a=>49152===(a&49152),xg:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},ef:(a,b)=>{if(F.Dg)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&
!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},vh:a=>{var b=F.ef(a,"x");return b?b:a.Be.bf?0:2},jg:(a,b)=>{try{return F.Ve(a,b),20}catch(c){}return F.ef(a,"wx")},Of:(a,b,c)=>{try{var d=F.Ve(a,b)}catch(e){return e.Ne}if(a=F.ef(a,"wx"))return a;if(c){if(!F.Ie(d.mode))return 54;if(F.Jf(d)||F.$e(d)===F.Ff())return 10}else if(F.Ie(d.mode))return 31;return 0},wh:(a,b)=>a?F.uf(a.mode)?32:F.Ie(a.mode)&&("r"!==F.xg(b)||b&512)?31:F.ef(a,F.xg(b)):44,Tg:4096,yh:()=>{for(var a=0;a<=
F.Tg;a++)if(!F.streams[a])return a;throw new F.oe(33);},Pe:a=>{a=F.lh(a);if(!a)throw new F.oe(8);return a},lh:a=>F.streams[a],eh:(a,b=-1)=>{F.Cf||(F.Cf=function(){this.ff={}},F.Cf.prototype={},Object.defineProperties(F.Cf.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ff.flags},set(c){this.ff.flags=c}},position:{get(){return this.ff.position},set(c){this.ff.position=c}}}));a=Object.assign(new F.Cf,a);-1==b&&(b=F.yh());a.fd=b;return F.streams[b]=a},Yg:a=>{F.streams[a]=
null},Xg:{open:a=>{a.De=F.kh(a.node.Rf).De;a.De.open&&a.De.open(a)},Re:()=>{throw new F.oe(70);}},ig:a=>a>>8,mi:a=>a&255,cf:(a,b)=>a<<8|b,ng:(a,b)=>{F.ug[a]={De:b}},kh:a=>F.ug[a],zg:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.wf)}return b},Mg:(a,b)=>{function c(h){F.Tf--;return b(h)}function d(h){if(h){if(!d.hh)return d.hh=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);F.Tf++;1<F.Tf&&k(`warning: ${F.Tf} FS.syncfs operations in flight at once, probably just doing extra work`);
var e=F.zg(F.root.He),g=0;e.forEach(h=>{if(!h.type.Mg)return d(null);h.type.Mg(h,a,d)})},He:(a,b,c)=>{var d="/"===c,e=!c;if(d&&F.root)throw new F.oe(10);if(!d&&!e){var g=F.Fe(c,{ag:!1});c=g.path;g=g.node;if(F.af(g))throw new F.oe(10);if(!F.Ie(g.mode))throw new F.oe(54);}b={type:a,xi:b,Gg:c,wf:[]};a=a.He(b);a.He=b;b.root=a;d?F.root=a:g&&(g.vf=b,g.He&&g.He.wf.push(b));return a},Di:a=>{a=F.Fe(a,{ag:!1});if(!F.af(a.node))throw new F.oe(28);a=a.node;var b=a.vf,c=F.zg(b);Object.keys(F.Se).forEach(d=>{for(d=
F.Se[d];d;){var e=d.df;c.includes(d.He)&&F.Zf(d);d=e}});a.vf=null;a.He.wf.splice(a.He.wf.indexOf(b),1)},bf:(a,b)=>a.Be.bf(a,b),We:(a,b,c)=>{var d=F.Fe(a,{parent:!0}).node;a=Na(a);if(!a||"."===a||".."===a)throw new F.oe(28);var e=F.jg(d,a);if(e)throw new F.oe(e);if(!d.Be.We)throw new F.oe(63);return d.Be.We(d,a,b,c)},create:(a,b)=>F.We(a,(void 0!==b?b:438)&4095|32768,0),Le:(a,b)=>F.We(a,(void 0!==b?b:511)&1023|16384,0),ni:(a,b)=>{a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];
try{F.Le(c,b)}catch(e){if(20!=e.Ne)throw e;}}},Pf:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return F.We(a,b|8192,c)},Ze:(a,b)=>{if(!Ra(a))throw new F.oe(44);var c=F.Fe(b,{parent:!0}).node;if(!c)throw new F.oe(44);b=Na(b);var d=F.jg(c,b);if(d)throw new F.oe(d);if(!c.Be.Ze)throw new F.oe(63);return c.Be.Ze(c,b,a)},zf:(a,b)=>{var c=Ma(a),d=Ma(b),e=Na(a),g=Na(b);var h=F.Fe(a,{parent:!0});var m=h.node;h=F.Fe(b,{parent:!0});h=h.node;if(!m||!h)throw new F.oe(44);if(m.He!==h.He)throw new F.oe(75);var q=
F.Ve(m,e);a=Sa(a,d);if("."!==a.charAt(0))throw new F.oe(28);a=Sa(b,c);if("."!==a.charAt(0))throw new F.oe(55);try{var r=F.Ve(h,g)}catch(v){}if(q!==r){b=F.Ie(q.mode);if(e=F.Of(m,e,b))throw new F.oe(e);if(e=r?F.Of(h,g,b):F.jg(h,g))throw new F.oe(e);if(!m.Be.zf)throw new F.oe(63);if(F.af(q)||r&&F.af(r))throw new F.oe(10);if(h!==m&&(e=F.ef(m,"w")))throw new F.oe(e);F.Cg(q);try{m.Be.zf(q,h,g)}catch(v){throw v;}finally{F.Bg(q)}}},Af:a=>{var b=F.Fe(a,{parent:!0}).node;a=Na(a);var c=F.Ve(b,a),d=F.Of(b,a,
!0);if(d)throw new F.oe(d);if(!b.Be.Af)throw new F.oe(63);if(F.af(c))throw new F.oe(10);b.Be.Af(b,a);F.Zf(c)},yf:a=>{a=F.Fe(a,{Oe:!0}).node;if(!a.Be.yf)throw new F.oe(54);return a.Be.yf(a)},hf:a=>{var b=F.Fe(a,{parent:!0}).node;if(!b)throw new F.oe(44);a=Na(a);var c=F.Ve(b,a),d=F.Of(b,a,!1);if(d)throw new F.oe(d);if(!b.Be.hf)throw new F.oe(63);if(F.af(c))throw new F.oe(10);b.Be.hf(b,a);F.Zf(c)},gf:a=>{a=F.Fe(a).node;if(!a)throw new F.oe(44);if(!a.Be.gf)throw new F.oe(28);return Ra(F.$e(a.parent),
a.Be.gf(a))},stat:(a,b)=>{a=F.Fe(a,{Oe:!b}).node;if(!a)throw new F.oe(44);if(!a.Be.Qe)throw new F.oe(63);return a.Be.Qe(a)},li:a=>F.stat(a,!0),Ef:(a,b,c)=>{a="string"==typeof a?F.Fe(a,{Oe:!c}).node:a;if(!a.Be.Je)throw new F.oe(63);a.Be.Je(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},ji:(a,b)=>{F.Ef(a,b,!0)},ai:(a,b)=>{a=F.Pe(a);F.Ef(a.node,b)},pg:(a,b,c,d)=>{a="string"==typeof a?F.Fe(a,{Oe:!d}).node:a;if(!a.Be.Je)throw new F.oe(63);a.Be.Je(a,{timestamp:Date.now()})},ki:(a,b,c)=>{F.pg(a,b,c,
!0)},bi:(a,b,c)=>{a=F.Pe(a);F.pg(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new F.oe(28);a="string"==typeof a?F.Fe(a,{Oe:!0}).node:a;if(!a.Be.Je)throw new F.oe(63);if(F.Ie(a.mode))throw new F.oe(31);if(!F.isFile(a.mode))throw new F.oe(28);var c=F.ef(a,"w");if(c)throw new F.oe(c);a.Be.Je(a,{size:b,timestamp:Date.now()})},di:(a,b)=>{a=F.Pe(a);if(0===(a.flags&2097155))throw new F.oe(28);F.truncate(a.node,b)},Fi:(a,b,c)=>{a=F.Fe(a,{Oe:!0}).node;a.Be.Je(a,{timestamp:Math.max(b,c)})},open:(a,b,c)=>{if(""===
a)throw new F.oe(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=E(a);try{e=F.Fe(a,{Oe:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new F.oe(20);}else e=F.We(a,c,0),d=!0;if(!e)throw new F.oe(44);F.If(e.mode)&&(b&=-513);if(b&65536&&!F.Ie(e.mode))throw new F.oe(54);if(!d&&(c=F.wh(e,b)))throw new F.oe(c);
b&512&&!d&&F.truncate(e,0);b&=-131713;e=F.eh({node:e,path:F.$e(e),flags:b,seekable:!0,position:0,De:e.De,Gh:[],error:!1});e.De.open&&e.De.open(e);!f.logReadFiles||b&1||(F.lg||(F.lg={}),a in F.lg||(F.lg[a]=1));return e},close:a=>{if(F.tf(a))throw new F.oe(8);a.eg&&(a.eg=null);try{a.De.close&&a.De.close(a)}catch(b){throw b;}finally{F.Yg(a.fd)}a.fd=null},tf:a=>null===a.fd,Re:(a,b,c)=>{if(F.tf(a))throw new F.oe(8);if(!a.seekable||!a.De.Re)throw new F.oe(70);if(0!=c&&1!=c&&2!=c)throw new F.oe(28);a.position=
a.De.Re(a,b,c);a.Gh=[];return a.position},read:(a,b,c,d,e)=>{if(0>d||0>e)throw new F.oe(28);if(F.tf(a))throw new F.oe(8);if(1===(a.flags&2097155))throw new F.oe(8);if(F.Ie(a.node.mode))throw new F.oe(31);if(!a.De.read)throw new F.oe(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F.oe(70);b=a.De.read(a,b,c,d,e);g||(a.position+=b);return b},write:(a,b,c,d,e,g)=>{if(0>d||0>e)throw new F.oe(28);if(F.tf(a))throw new F.oe(8);if(0===(a.flags&2097155))throw new F.oe(8);if(F.Ie(a.node.mode))throw new F.oe(31);
if(!a.De.write)throw new F.oe(28);a.seekable&&a.flags&1024&&F.Re(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new F.oe(70);b=a.De.write(a,b,c,d,e,g);h||(a.position+=b);return b},mf:(a,b,c)=>{if(F.tf(a))throw new F.oe(8);if(0>b||0>=c)throw new F.oe(28);if(0===(a.flags&2097155))throw new F.oe(8);if(!F.isFile(a.node.mode)&&!F.Ie(a.node.mode))throw new F.oe(43);if(!a.De.mf)throw new F.oe(138);a.De.mf(a,b,c)},kf:(a,b,c,d,e)=>{if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new F.oe(2);
if(1===(a.flags&2097155))throw new F.oe(2);if(!a.De.kf)throw new F.oe(43);return a.De.kf(a,b,c,d,e)},xf:(a,b,c,d,e)=>a.De.xf?a.De.xf(a,b,c,d,e):0,ti:()=>0,hg:(a,b,c)=>{if(!a.De.hg)throw new F.oe(59);return a.De.hg(a,b,c)},Ai:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=F.open(a,b.flags);a=F.stat(a).size;var e=new Uint8Array(a);F.read(d,e,0,a,0);"utf8"===b.encoding?c=C(e,0):"binary"===
b.encoding&&(c=e);F.close(d);return c},Ih:(a,b,c={})=>{c.flags=c.flags||577;a=F.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Ka(b)+1);b=D(b,d,0,d.length);F.write(a,d,0,b,void 0,c.Wg)}else if(ArrayBuffer.isView(b))F.write(a,b,0,b.byteLength,void 0,c.Wg);else throw Error("Unsupported data type");F.close(a)},Ff:()=>F.tg,Wh:a=>{a=F.Fe(a,{Oe:!0});if(null===a.node)throw new F.oe(44);if(!F.Ie(a.node.mode))throw new F.oe(54);var b=F.ef(a.node,"x");if(b)throw new F.oe(b);F.tg=a.path},
$g:()=>{F.Le("/tmp");F.Le("/home");F.Le("/home/web_user")},Zg:()=>{F.Le("/dev");F.ng(F.cf(1,3),{read:()=>0,write:(d,e,g,h)=>h});F.Pf("/dev/null",F.cf(1,3));Wa(F.cf(5,0),Ya);Wa(F.cf(6,0),Za);F.Pf("/dev/tty",F.cf(5,0));F.Pf("/dev/tty1",F.cf(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Qa(a).byteLength);return a[--b]};F.Me("/dev","random",c);F.Me("/dev","urandom",c);F.Le("/dev/shm");F.Le("/dev/shm/tmp")},bh:()=>{F.Le("/proc");var a=F.Le("/proc/self");F.Le("/proc/self/fd");F.He({He:()=>{var b=
F.createNode(a,"fd",16895,73);b.Be={bf:(c,d)=>{var e=F.Pe(+d);c={parent:null,He:{Gg:"fake"},Be:{gf:()=>e.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},dh:()=>{f.stdin?F.Me("/dev","stdin",f.stdin):F.Ze("/dev/tty","/dev/stdin");f.stdout?F.Me("/dev","stdout",null,f.stdout):F.Ze("/dev/tty","/dev/stdout");f.stderr?F.Me("/dev","stderr",null,f.stderr):F.Ze("/dev/tty1","/dev/stderr");F.open("/dev/stdin",0);F.open("/dev/stdout",1);F.open("/dev/stderr",1)},vg:()=>{F.oe||(F.oe=function(a,b){this.name=
"ErrnoError";this.node=b;this.Dh=function(c){this.Ne=c};this.Dh(a);this.message="FS error"},F.oe.prototype=Error(),F.oe.prototype.constructor=F.oe,[44].forEach(a=>{F.dg[a]=new F.oe(a);F.dg[a].stack="<generic error, no stack>"}))},Fh:()=>{F.vg();F.Se=Array(4096);F.He(G,{},"/");F.$g();F.Zg();F.bh();F.jh={MEMFS:G}},Hf:(a,b,c)=>{F.Hf.gg=!0;F.vg();f.stdin=a||f.stdin;f.stdout=b||f.stdout;f.stderr=c||f.stderr;F.dh()},zi:()=>{F.Hf.gg=!1;for(var a=0;a<F.streams.length;a++){var b=F.streams[a];b&&F.close(b)}},
ci:(a,b)=>{a=F.Ug(a,b);return a.wg?a.object:null},Ug:(a,b)=>{try{var c=F.Fe(a,{Oe:!b});a=c.path}catch(e){}var d={Jf:!1,wg:!1,error:0,name:null,path:null,object:null,zh:!1,Bh:null,Ah:null};try{c=F.Fe(a,{parent:!0}),d.zh=!0,d.Bh=c.path,d.Ah=c.node,d.name=Na(a),c=F.Fe(a,{Oe:!b}),d.wg=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.Jf="/"===c.path}catch(e){d.error=e.Ne}return d},Yf:(a,b)=>{a="string"==typeof a?a:F.$e(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=E(a+"/"+c);
try{F.Le(d)}catch(e){}a=d}}return d},ah:(a,b,c,d,e)=>{a="string"==typeof a?a:F.$e(a);b=E(a+"/"+b);return F.create(b,fb(d,e))},Xf:(a,b,c,d,e,g)=>{var h=b;a&&(a="string"==typeof a?a:F.$e(a),h=b?E(a+"/"+b):a);a=fb(d,e);h=F.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}F.Ef(h,a|146);b=F.open(h,577);F.write(b,c,0,c.length,0,g);F.close(b);F.Ef(h,a)}return h},Me:(a,b,c,d)=>{a=Oa("string"==typeof a?a:F.$e(a),b);b=fb(!!c,!!d);F.Me.ig||(F.Me.ig=
64);var e=F.cf(F.Me.ig++,0);F.ng(e,{open:g=>{g.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(g,h,m,q)=>{for(var r=0,v=0;v<q;v++){try{var t=c()}catch(z){throw new F.oe(29);}if(void 0===t&&0===r)throw new F.oe(6);if(null===t||void 0===t)break;r++;h[m+v]=t}r&&(g.node.timestamp=Date.now());return r},write:(g,h,m,q)=>{for(var r=0;r<q;r++)try{d(h[m+r])}catch(v){throw new F.oe(29);}q&&(g.node.timestamp=Date.now());return r}});return F.Pf(a,b,e)},bg:a=>{if(a.Fg||a.th||a.link||a.Ce)return!0;
if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(da)try{a.Ce=Ua(da(a.url)),a.Ge=a.Ce.length}catch(b){throw new F.oe(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},rg:(a,b,c,d,e)=>{if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
c={Fg:!1,url:c};var g=F.ah(a,b,c,d,e);c.Ce?g.Ce=c.Ce:c.url&&(g.Ce=null,g.url=c.url);Object.defineProperties(g,{Ge:{get:function(){return this.Ce.length}}});var h={};Object.keys(g.De).forEach(m=>{var q=g.De[m];h[m]=function(){F.bg(g);return q.apply(null,arguments)}});h.read=(m,q,r,v,t)=>{F.bg(g);m=m.node.Ce;if(t>=m.length)q=0;else{v=Math.min(m.length-t,v);if(m.slice)for(var z=0;z<v;z++)q[r+z]=m[t+z];else for(z=0;z<v;z++)q[r+z]=m.get(t+z);q=v}return q};h.kf=()=>{F.bg(g);l();throw new F.oe(48);};g.De=
h;return g}},gb=void 0;function hb(){gb+=4;return x[gb-4>>2]}var ib=0;function jb(){for(var a=H.length-1;0<=a;--a)kb(a);H=[];lb=[]}var lb=[];function mb(){if(navigator.userActivation?navigator.userActivation.isActive:ib&&nb.Wf)for(var a=0;a<lb.length;++a){var b=lb[a];lb.splice(a,1);--a;b.Bi.apply(null,b.Mh)}}var H=[];function kb(a){var b=H[a];b.target.removeEventListener(b.Ye,b.ih,b.lf);H.splice(a,1)}
function ob(a){function b(d){++ib;nb=a;mb();a.sf(d);mb();--ib}if(!a.target)return-4;if(a.nf)a.ih=b,a.target.addEventListener(a.Ye,b,a.lf),H.push(a),pb||(sa.push(jb),pb=!0);else for(var c=0;c<H.length;++c)H[c].target==a.target&&H[c].Ye==a.Ye&&kb(c--);return 0}var pb,nb,qb,rb,sb,tb,ub,vb,wb,xb=[0,document,window];function yb(a){a=2<a?a?C(w,a):"":a;return xb[a]||document.querySelector(a)}function zb(a){return 0>xb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Ab(a,b){B[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)B[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)B[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)x[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];x[a+1296>>2]=b.connected;x[a+1300>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;D(b.id,w,a+1304,64);D(b.mapping,w,a+1368,64)}var Bb;Bb=()=>performance.now();
function Cb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function Db(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Eb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Fb=1,Gb=[],I=[],Hb=[],Ib=[],Jb=[],J=[],Kb=[],Lb=[],K=[],Mb={},Nb=4;
function L(a){Ob||(Ob=a)}function Pb(a){for(var b=Fb++,c=a.length;c<b;c++)a[c]=null;return b}function Qb(a,b){a.ff||(a.ff=a.getContext,a.getContext=function(d,e){e=a.ff(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Rb(c,b):0}function Rb(a,b){var c=Pb(Lb),d={handle:c,attributes:b,version:b.uh,Vf:a};a.canvas&&(a.canvas.Jh=d);Lb[c]=d;("undefined"==typeof b.gh||b.gh)&&Sb(d);return c}
function Sb(a){a||(a=Tb);if(!a.nh){a.nh=!0;var b=a.Vf;Cb(b);Db(b);Eb(b);b.Ue=b.getExtension("EXT_disjoint_timer_query");b.si=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ub={},Ob,Tb;function Vb(a){M.activeTexture(a)}function Wb(a,b){M.attachShader(I[a],J[b])}function Xb(a,b,c){M.bindAttribLocation(I[a],b,c?C(w,c):"")}function Yb(a,b){M.bindBuffer(a,Gb[b])}
function Zb(a,b){M.bindFramebuffer(a,Hb[b])}function $b(a,b){M.bindRenderbuffer(a,Ib[b])}function ac(a,b){M.bindTexture(a,Jb[b])}function bc(a,b){M.blendFunc(a,b)}function cc(a,b,c,d){M.bufferData(a,c?w.subarray(c,c+b):b,d)}function dc(a,b,c,d){M.bufferSubData(a,b,w.subarray(d,d+c))}function ec(a){return M.checkFramebufferStatus(a)}function fc(a){M.clear(a)}function gc(a,b,c,d){M.clearColor(a,b,c,d)}function hc(a){M.clearDepth(a)}function ic(a){M.compileShader(J[a])}
function jc(a,b,c,d,e,g,h,m){M.compressedTexImage2D(a,b,c,d,e,g,m?w.subarray(m,m+h):null)}function kc(){var a=Pb(I),b=M.createProgram();b.name=a;b.Nf=b.Lf=b.Mf=0;b.og=1;I[a]=b;return a}function lc(a){var b=Pb(J);J[b]=M.createShader(a);return b}function mc(a){M.cullFace(a)}function nc(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Hb[d];e&&(M.deleteFramebuffer(e),e.name=0,Hb[d]=null)}}function oc(a){if(a){var b=I[a];b?(M.deleteProgram(b),b.name=0,I[a]=null):L(1281)}}
function pc(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Ib[d];e&&(M.deleteRenderbuffer(e),e.name=0,Ib[d]=null)}}function qc(a){if(a){var b=J[a];b?(M.deleteShader(b),J[a]=null):L(1281)}}function rc(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Jb[d];e&&(M.deleteTexture(e),e.name=0,Jb[d]=null)}}function sc(a){M.depthFunc(a)}function tc(a,b){M.detachShader(I[a],J[b])}function uc(a){M.disable(a)}function vc(a,b,c){M.drawArrays(a,b,c)}var wc=[];function xc(a,b,c,d){M.drawElements(a,b,c,d)}
function yc(a){M.enable(a)}function zc(a){M.enableVertexAttribArray(a)}function Ac(a,b,c,d){M.framebufferRenderbuffer(a,b,c,Ib[d])}function Bc(a,b,c,d,e){M.framebufferTexture2D(a,b,c,Jb[d],e)}function Cc(a){M.frontFace(a)}function Dc(a,b,c,d){for(var e=0;e<a;e++){var g=M[c](),h=g&&Pb(d);g?(g.name=h,d[h]=g):L(1282);x[b+4*e>>2]=h}}function Ec(a,b){Dc(a,b,"createBuffer",Gb)}function Fc(a,b){Dc(a,b,"createFramebuffer",Hb)}function Gc(a,b){Dc(a,b,"createRenderbuffer",Ib)}
function Hc(a,b){Dc(a,b,"createTexture",Jb)}function Ic(a,b,c,d,e,g,h,m){b=I[b];if(a=M[a](b,c))d=m&&D(a.name,w,m,d),e&&(x[e>>2]=d),g&&(x[g>>2]=a.size),h&&(x[h>>2]=a.type)}function Jc(a,b){return M.getAttribLocation(I[a],b?C(w,b):"")}function Kc(a,b){y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296}
function Lc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&L(1280);return;case 36345:d=0;break;case 34466:var e=M.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=M.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":L(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:L(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:u[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){L(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:L(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Kc(b,
d);break;case 0:x[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:u[b>>0]=d?1:0}}else L(1281)}function Mc(a,b){Lc(a,b,2)}function Nc(a,b,c,d){a=M.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a}function Oc(a,b,c,d){a=M.getProgramInfoLog(I[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,w,d,b):0;c&&(x[c>>2]=b)}
function Pc(a,b,c){if(c)if(a>=Fb)L(1281);else if(a=I[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.Nf)for(b=0;b<M.getProgramParameter(a,35718);++b)a.Nf=Math.max(a.Nf,M.getActiveUniform(a,b).name.length+1);x[c>>2]=a.Nf}else if(35722==b){if(!a.Lf)for(b=0;b<M.getProgramParameter(a,35721);++b)a.Lf=Math.max(a.Lf,M.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.Lf}else if(35381==b){if(!a.Mf)for(b=0;b<M.getProgramParameter(a,35382);++b)a.Mf=
Math.max(a.Mf,M.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.Mf}else x[c>>2]=M.getProgramParameter(a,b);else L(1281)}function Qc(a,b,c){if(c){a=M.Ue.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Kc(c,d)}else L(1281)}function Rc(a,b,c){if(c){a=M.Ue.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else L(1281)}function Sc(a,b,c,d){a=M.getShaderInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,w,d,b):0;c&&(x[c>>2]=b)}
function Tc(a,b,c){c?35716==b?(a=M.getShaderInfoLog(J[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(J[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=M.getShaderParameter(J[a],b):L(1281)}var Uc=a=>{var b=Ka(a)+1,c=N(b);c&&D(a,w,c,b);return c};
function Vc(a){var b=Mb[a];if(!b){switch(a){case 7939:b=M.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Uc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=M.getParameter(a))||L(1280);b=b&&Uc(b);break;case 7938:b=Uc("OpenGL ES 2.0 ("+M.getParameter(7938)+")");break;case 35724:b=M.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Uc(b);break;
default:L(1280)}Mb[a]=b}return b}function Wc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Xc(a){var b=a.Bf,c=a.Og,d;if(!b)for(a.Bf=b={},a.Ng={},d=0;d<M.getProgramParameter(a,35718);++d){var e=M.getActiveUniform(a,d);var g=e.name;e=e.size;var h=Wc(g);h=0<h?g.slice(0,h):g;var m=a.og;a.og+=e;c[h]=[e,m];for(g=0;g<e;++g)b[m]=g,a.Ng[m++]=h}}
function Yc(a,b){b=b?C(w,b):"";if(a=I[a]){Xc(a);var c=a.Bf,d=0,e=b,g=Wc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Og[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else L(1281);return-1}function O(a){var b=M.fh;if(b){var c=b.Bf[a];"number"==typeof c&&(b.Bf[a]=c=M.getUniformLocation(b,b.Ng[a]+(0<c?"["+c+"]":"")));return c}L(1282)}
function Zc(a,b,c,d){if(c)if(a=I[a],Xc(a),a=M.getUniform(a,O(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else L(1281)}
function $c(a,b,c,d){if(c)if(a=M.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else L(1281)}function ad(a){a=I[a];M.linkProgram(a);a.Bf=0;a.Og={}}function bd(a,b){3317==a&&(Nb=b);M.pixelStorei(a,b)}
function cd(a,b,c,d,e){a-=5120;a=1==a?w:4==a?x:6==a?A:5==a||28922==a?y:ma;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Nb;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}function dd(a,b,c,d,e,g,h){(h=cd(g,e,c,d,h))?M.readPixels(a,b,c,d,e,g,h):L(1280)}function ed(a,b,c,d){M.renderbufferStorage(a,b,c,d)}function fd(a,b,c,d){M.scissor(a,b,c,d)}
function gd(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?x[d+4*g>>2]:-1,m=x[c+4*g>>2];h=m?C(w,m,0>h?void 0:h):"";e+=h}M.shaderSource(J[a],e)}function hd(a,b,c,d,e,g,h,m,q){M.texImage2D(a,b,c,d,e,g,h,m,q?cd(m,h,d,e,q):null)}function jd(a,b,c){M.texParameterf(a,b,c)}function kd(a,b,c){M.texParameteri(a,b,c)}var P=[];function ld(a,b){M.uniform1i(O(a),b)}var md=[];
function nd(a,b,c){if(144>=b)for(var d=P[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);M.uniform2fv(O(a),d)}function od(a,b,c,d,e){M.uniform4f(O(a),b,c,d,e)}function pd(a,b,c){if(72>=b){var d=P[4*b-1],e=A;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=A.subarray(c>>2,c+16*b>>2);M.uniform4fv(O(a),d)}
function qd(a,b,c,d){if(18>=b){var e=P[16*b-1],g=A;d>>=2;for(var h=0;h<16*b;h+=16){var m=d+h;e[h]=g[m];e[h+1]=g[m+1];e[h+2]=g[m+2];e[h+3]=g[m+3];e[h+4]=g[m+4];e[h+5]=g[m+5];e[h+6]=g[m+6];e[h+7]=g[m+7];e[h+8]=g[m+8];e[h+9]=g[m+9];e[h+10]=g[m+10];e[h+11]=g[m+11];e[h+12]=g[m+12];e[h+13]=g[m+13];e[h+14]=g[m+14];e[h+15]=g[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(O(a),!!c,e)}function rd(a){a=I[a];M.useProgram(a);M.fh=a}function sd(a,b,c,d,e,g){M.vertexAttribPointer(a,b,c,!!d,e,g)}
function td(a,b,c,d){M.viewport(a,b,c,d)}
function ud(a,b,c,d){rb||(rb=N(72));a=yb(a);return ob({target:a,Wf:!0,Ye:"click",nf:d,sf:function(e=event){var g=a,h=rb;B[h>>3]=e.timeStamp;h>>=2;x[h+2]=e.screenX;x[h+3]=e.screenY;x[h+4]=e.clientX;x[h+5]=e.clientY;x[h+6]=e.ctrlKey;x[h+7]=e.shiftKey;x[h+8]=e.altKey;x[h+9]=e.metaKey;la[2*h+20]=e.button;la[2*h+21]=e.buttons;x[h+11]=e.movementX;x[h+12]=e.movementY;g=zb(g);x[h+13]=e.clientX-g.left;x[h+14]=e.clientY-g.top;vd.apply(null,[d,4,rb,b])&&e.preventDefault()},lf:c})}
function wd(a,b,c,d,e){tb||(tb=N(280));return ob({target:a,Ye:e,nf:d,sf:function(g=event){var h=tb,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,q=!!m;x[h>>2]=q;x[h+4>>2]=document.fullscreenEnabled||document.webkitFullscreenEnabled;var r=q?m:sb,v=r&&r.id?r.id:"";D(r?r==window?"#window":r==screen?"#screen":r&&r.nodeName?r.nodeName:"":"",w,h+8,128);D(v,w,h+136,128);x[h+264>>2]=r?r.clientWidth:0;x[h+268>>2]=r?r.clientHeight:
0;x[h+272>>2]=screen.width;x[h+276>>2]=screen.height;q&&(sb=m);vd.apply(null,[d,19,h,b])&&g.preventDefault()},lf:c})}function xd(a,b,c,d,e){ub||(ub=N(1432));b={target:yb(2),Wf:!0,Ye:e,nf:c,sf:function(g=event){var h=ub;Ab(h,g.gamepad);vd.apply(null,[c,d,h,a])&&g.preventDefault()},lf:b};return ob(b)}
function yd(a,b,c,d){vb||(vb=N(36));a=yb(a);return ob({target:a,Ye:"resize",nf:d,sf:function(e=event){if(e.target==a){var g=document.body;if(g){var h=vb;x[h>>2]=e.detail;x[h+4>>2]=g.clientWidth;x[h+8>>2]=g.clientHeight;x[h+12>>2]=innerWidth;x[h+16>>2]=innerHeight;x[h+20>>2]=outerWidth;x[h+24>>2]=outerHeight;x[h+28>>2]=pageXOffset;x[h+32>>2]=pageYOffset;vd.apply(null,[d,10,h,b])&&e.preventDefault()}}},lf:c})}
function zd(a,b,c,d,e,g){wb||(wb=N(1696));a=yb(a);return ob({target:a,Wf:"touchstart"==g||"touchend"==g,Ye:g,nf:d,sf:function(h){for(var m,q={},r=h.touches,v=0;v<r.length;++v)m=r[v],m.Eg=m.Hg=0,q[m.identifier]=m;for(v=0;v<h.changedTouches.length;++v)m=h.changedTouches[v],m.Eg=1,q[m.identifier]=m;for(v=0;v<h.targetTouches.length;++v)q[h.targetTouches[v].identifier].Hg=1;r=wb;B[r>>3]=h.timeStamp;var t=r>>2;x[t+3]=h.ctrlKey;x[t+4]=h.shiftKey;x[t+5]=h.altKey;x[t+6]=h.metaKey;t+=7;var z=zb(a),R=0;for(v in q)if(m=
q[v],x[t]=m.identifier,x[t+1]=m.screenX,x[t+2]=m.screenY,x[t+3]=m.clientX,x[t+4]=m.clientY,x[t+5]=m.pageX,x[t+6]=m.pageY,x[t+7]=m.Eg,x[t+8]=m.Hg,x[t+9]=m.clientX-z.left,x[t+10]=m.clientY-z.top,t+=13,31<++R)break;x[r+8>>2]=R;vd.apply(null,[d,e,r,b])&&h.preventDefault()},lf:c})}
function Ad(a,b){Bd=a;Cd=b;if(Dd)if(Ed||(Ed=!0),0==a)Q=function(){var d=Math.max(0,Fd+b-Bb())|0;setTimeout(Gd,d)};else if(1==a)Q=function(){Hd(Gd)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}Q=function(){setImmediate(Gd)}}}
function Id(a){!Dd||l("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Dd=a;var b=Jd;Ed=!1;Gd=function(){if(!p)if(0<Kd.length){var c=Date.now(),d=Kd.shift();d.ei(d.Lh);if(Ld){var e=Ld,g=0==e%1?e-1:Math.floor(e);Ld=d.Xh?g:(8*e+(g+.5))/9}ha('main loop blocker "'+d.name+'" took '+(Date.now()-c)+" ms");f.setStatus&&(c=f.statusMessage||"Please wait...",d=Ld,e=Md.$h,
d?d<e?f.setStatus(c+" ("+(e-d)+"/"+e+")"):f.setStatus(c):f.setStatus(""));b<Jd||setTimeout(Gd,0)}else b<Jd||(Nd=Nd+1|0,1==Bd&&1<Cd&&0!=Nd%Cd?Q():(0==Bd&&(Fd=Bb()),p||f.preMainLoop&&!1===f.preMainLoop()||(Od(a),f.postMainLoop&&f.postMainLoop()),b<Jd||("object"==typeof SDL&&SDL.audio&&SDL.audio.Ch&&SDL.audio.Ch(),Q())))}}
var Pd=a=>{a instanceof Ha||"unwind"==a||ba(1,a)},Qd=a=>{ka=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);p=!0}ba(a,new Ha(a))},Od=a=>{if(!p)try{if(a(),!noExitRuntime)try{ka=a=ka,Qd(a)}catch(b){Pd(b)}}catch(b){Pd(b)}},Rd=(a,b)=>setTimeout(()=>{Od(a)},b),Ed=!1,Q=null,Jd=0,Dd=null,Bd=0,Cd=0,Nd=0,Kd=[];function Sd(){Jd++;var a=Bd,b=Cd,c=Dd;Dd=null;Id(c);Ad(a,b);Q()}var Md={},Fd,Gd,Ld,Td=!1,Ud=!1,Vd=[];
function eb(){function a(){Ud=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!Wd){Wd=!0;bb.push({canHandle:function(c){return!f.wi&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=new Blob([c],{type:Xd(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Xd(d)}));var m=URL.createObjectURL(h),q=new Image;q.onload=()=>{q.complete||l("Image "+
d+" could not be decoded");var r=document.createElement("canvas");r.width=q.width;r.height=q.height;r.getContext("2d").drawImage(q,0,0);URL.revokeObjectURL(m);e&&e(c)};q.onerror=()=>{ha("Image "+m+" could not be decoded");g&&g()};q.src=m}});bb.push({canHandle:function(c){return!f.vi&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function g(){h||(h=!0,e&&e(c))}var h=!1,m=URL.createObjectURL(new Blob([c],{type:Xd(d)})),q=new Audio;q.addEventListener("canplaythrough",()=>g(q),!1);
q.onerror=function(){if(!h){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var r="",v=0,t=0,z=0;z<c.length;z++)for(v=v<<8|c[z],t+=8;6<=t;){var R=v>>t-6&63;t-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[R]}2==t?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],r+="=="):4==t&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],r+="=");q.src="data:audio/x-"+d.substr(-3)+
";base64,"+r;g(q)}};q.src=m;Rd(()=>{g(q)},1E4)}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!Ud&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Yd(a,b,c,d){if(b&&f.pf&&a==f.canvas)return f.pf;var e;if(b){var g={antialias:!1,alpha:!1,uh:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof Ub&&(e=Qb(a,g)))var m=Lb[e].Vf}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof M||l("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.pf=m,b&&(Tb=Lb[e],f.pf=M=Tb&&Tb.Vf),f.Ei=b,Vd.forEach(q=>q()),eb());return m}var Zd=!1,$d=void 0,ae=void 0;
function be(a,b){function c(){Td=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=ce,$d&&d.requestPointerLock(),Td=!0,ae?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),de(f.canvas),ee()):de(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),ae?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&
-8388609),de(f.canvas),ee()):de(d));if(f.onFullScreen)f.onFullScreen(Td);if(f.onFullscreen)f.onFullscreen(Td)}$d=a;ae=b;"undefined"==typeof $d&&($d=!0);"undefined"==typeof ae&&(ae=!1);var d=f.canvas;Zd||(Zd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function ce(){if(!Td)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var fe=0;function Hd(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===fe)fe=b+1E3/60;else for(;b+2>=fe;)fe+=1E3/60;setTimeout(a,Math.max(fe-b,0))}}
function Xd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ge=0,he=0,ie=0,je=0;
function ke(a){if(Ud)"mousemove"!=a.type&&"mozMovementX"in a?ie=je=0:(ie=a.movementX||a.mozMovementX||a.webkitMovementX||0,je=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(ge=SDL.oi+ie,he=SDL.pi+je):(ge+=ie,he+=je);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,ie=e-ge,je=a-he,ge=e,he=a)}}var le=[];function ee(){var a=f.canvas;le.forEach(b=>b(a.width,a.height))}function me(a,b,c){de(f.canvas,a,b);c||ee()}
function de(a,b,c){b&&c?(a.Hh=b,a.mh=c):(b=a.Hh,c=a.mh);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}ae?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var db={},Wd;
function ne(a,b,c,d){this.id=a;this.y=this.x=0;this.cg=!1;this.Lg=this.Kg=0;this.width=b;this.height=c;this.Jg=b;this.Ig=c;this.title=d;this.attributes=S;this.buttons=0;this.keys=[];this.$f=[];this.Eh=0;this.Df=this.Kf=this.rf=this.Sf=this.jf=this.qf=this.Qf=this.Pg=this.yg=this.Rg=this.Qg=this.Uf=this.title=null}function T(a){return 0>=a||!U?null:U[a-1]}
var oe=null,V=null,pe=null,U=null,qe=null,S=null,re={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0};
function se(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function te(){var a=V,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function ue(a){V&&V.Df&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||dynCall_vii.apply(null,[V.Df,V.id,a]))}
function ve(a,b){if(V){var c=se(a);if(-1!=c){var d=b&&V.keys[c];V.keys[c]=b;V.$f[a]=b;V.Kf&&(d&&(b=2),we.apply(null,[V.Kf,V.id,c,a,b,te()]))}}}function xe(){ye()}function ze(){ye()}function Ae(a){ve(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Ce(a){ve(a.keyCode,0)}function De(){if(V)for(var a=0;a<V.$f.length;++a)V.$f[a]&&ve(a,0)}function Ee(a){V&&(ke(a),a.target==f.canvas&&V.qf&&V.qf&&Fe.apply(null,[V.qf,V.id,ge,he]))}
function Ge(a){V&&a.target==f.canvas&&V.jf&&dynCall_vii.apply(null,[V.jf,V.id,1])}function He(a){V&&a.target==f.canvas&&V.jf&&dynCall_vii.apply(null,[V.jf,V.id,0])}function Ie(a,b){if(V&&(ke(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){V.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else V.buttons&=~(1<<c);V.Qf&&Je.apply(null,[V.Qf,V.id,c,b,te()])}}function Ke(a){V&&Ie(a,1)}function Le(a){V&&Ie(a,0)}
function Me(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);V&&V.Sf&&a.target==f.canvas&&(Fe.apply(null,[V.Sf,V.id,"mousewheel"==a.type?a.wheelDeltaX:a.deltaX,b]),a.preventDefault())}
var W={},Ne=[],Oe=null;
function ye(){if(Nd!==Oe||!Nd){Ne=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Oe=Nd;for(var a=0;a<Ne.length;++a){var b=Ne[a];if(b){W[a]||(ha("glfw joystick connected:",a),W[a]={id:Uc(b.id),Qh:b.buttons.length,Oh:b.axes.length,buttons:N(b.buttons.length),axes:N(4*b.axes.length)});for(var c=W[a],d=0;d<b.buttons.length;++d)u[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)A[c.axes+4*d>>2]=b.axes[d]}else W[a]&&(ha("glfw joystick disconnected",
a),Pe(W[a].id),Pe(W[a].buttons),Pe(W[a].axes),delete W[a])}}}
function Qe(a){function b(m){var q="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),r=new FileReader;r.onloadend=t=>{if(2!=r.readyState)++g,ha("failed to read dropped file: "+m.name+": "+r.error);else if(F.Ih(q,new Uint8Array(t.target.result)),++g===e){Re.apply(null,[V.rf,V.id,e,c]);for(t=0;t<d.length;++t)Pe(d[t]);Pe(c)}};r.readAsArrayBuffer(m);var v=Uc(q);d.push(v);y[c+4*h>>2]=v}if(V&&V.rf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=N(4*a.dataTransfer.files.length),
d=[],e=a.dataTransfer.files.length,g=0;F.Yf("/",".glfw_dropped_files");for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function Se(a){if(V&&V.rf)return a.preventDefault(),!1}function Te(a){try{a()}catch(b){l(b)}}function Ue(a){var b={},c;for(c in a)(function(d){var e=a[d];b[d]="function"==typeof e?function(){Ve.push(d);try{return e.apply(null,arguments)}finally{p||(Ve.pop()===d||l(),X&&1===Y&&0===Ve.length&&(Y=0,Te(We),"undefined"!=typeof Fibers&&Fibers.Ci()))}}:e})(c);return b}
var Y=0,X=null,Xe=0,Ve=[],Ye={},Ze={},$e=0,af=null,bf=[];function cf(){var a=N(4108),b=a+12;y[a>>2]=b;y[a+4>>2]=b+4096;b=Ve[0];var c=Ye[b];void 0===c&&(c=$e++,Ye[b]=c,Ze[c]=b);x[a+8>>2]=c;return a}
function df(a){if(!p){if(0===Y){var b=!1,c=!1;a((d=0)=>{if(!p&&(Xe=d,b=!0,c)){Y=2;Te(()=>ef(X));"undefined"!=typeof db&&Dd&&Sd();d=!1;try{var e=(0,n[Ze[x[X+8>>2]]])()}catch(m){e=m,d=!0}var g=!1;if(!X){var h=af;h&&(af=null,(d?h.reject:h.resolve)(e),g=!0)}if(d&&!g)throw e;}});c=!0;b||(Y=1,X=cf(),"undefined"!=typeof db&&Dd&&(Q=null,Jd++),Te(()=>ff(X)))}else 2===Y?(Y=0,Te(gf),Pe(X),X=null,bf.forEach(d=>Od(d))):l(`invalid state: ${Y}`);return Xe}}
function hf(a,b,c,d){a||(a=this);this.parent=a;this.He=a.He;this.vf=null;this.id=F.xh++;this.name=b;this.mode=c;this.Be={};this.De={};this.Rf=d}Object.defineProperties(hf.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},th:{get:function(){return F.Ie(this.mode)}},Fg:{get:function(){return F.If(this.mode)}}});F.Sg=hf;
F.sg=function(a,b,c,d,e,g,h,m,q,r){function v(R){function Be(of){r&&r();m||F.Xf(a,b,of,d,e,q);g&&g();za(z)}cb(R,t,Be,()=>{h&&h();za(z)})||Be(R)}var t=b?Ra(E(a+"/"+b)):a,z=`cp ${t}`;ya(z);"string"==typeof c?ab(c,R=>v(R),h):v(c)};F.Fh();f.FS_createPath=F.Yf;f.FS_createDataFile=F.Xf;f.FS_createPreloadedFile=F.sg;f.FS_unlink=F.hf;f.FS_createLazyFile=F.rg;f.FS_createDevice=F.Me;for(var M,Z=0;32>Z;++Z)wc.push(Array(Z));var jf=new Float32Array(288);for(Z=0;288>Z;++Z)P[Z]=jf.subarray(0,Z+1);var kf=new Int32Array(288);
for(Z=0;288>Z;++Z)md[Z]=kf.subarray(0,Z+1);f.requestFullscreen=function(a,b){be(a,b)};f.requestAnimationFrame=function(a){Hd(a)};f.setCanvasSize=function(a,b,c){me(a,b,c)};f.pauseMainLoop=function(){Q=null;Jd++};f.resumeMainLoop=function(){Sd()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return Yd(a,b,c,d)};
var mf={Z:function(){return window.innerHeight},_:function(){return window.innerWidth},e:(a,b,c,d)=>{l(`Assertion failed: ${a?C(w,a):""}, at: `+[b?b?C(w,b):"":"unknown filename",c,d?d?C(w,d):"":"unknown function"])},Qa:function(a,b){try{if(0===b)return-28;var c=F.Ff(),d=Ka(c)+1;if(b<d)return-68;D(c,w,a,b);return d}catch(e){if("undefined"==typeof F||"ErrnoError"!==e.name)throw e;return-e.Ne}},Ua:function(a,b,c){gb=c;try{var d=F.Pe(a);switch(b){case 21509:return d.Ee?0:-59;case 21505:if(!d.Ee)return-59;
if(d.Ee.Xe.oh){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=hb();x[e>>2]=25856;x[e+4>>2]=5;x[e+8>>2]=191;x[e+12>>2]=35387;for(var g=0;32>g;g++)u[e+g+17>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.Ee?0:-59;case 21506:case 21507:case 21508:if(!d.Ee)return-59;if(d.Ee.Xe.ph)for(e=hb(),a=[],g=0;32>g;g++)a.push(u[e+g+17>>0]);return 0;case 21519:if(!d.Ee)return-59;e=hb();return x[e>>2]=0;case 21520:return d.Ee?-28:-59;case 21531:return e=hb(),F.hg(d,
b,e);case 21523:if(!d.Ee)return-59;d.Ee.Xe.qh&&(g=[24,80],e=hb(),la[e>>1]=g[0],la[e+2>>1]=g[1]);return 0;case 21524:return d.Ee?0:-59;case 21515:return d.Ee?0:-59;default:return-28}}catch(h){if("undefined"==typeof F||"ErrnoError"!==h.name)throw h;return-h.Ne}},Va:function(a,b,c,d){gb=d;try{b=b?C(w,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?F.Ff():F.Pe(a).path;if(0==e.length)throw new F.oe(44);b=E(g+"/"+e)}var h=d?hb():0;return F.open(b,c,h).fd}catch(m){if("undefined"==typeof F||"ErrnoError"!==
m.name)throw m;return-m.Ne}},Wa:function(){return Date.now()},be:function(a,b,c){a=yb(a);if(!a)return-4;a=zb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},$:function(a,b){if(0>a||a>=qb.length)return-5;if(!qb[a])return-7;Ab(b,qb[a]);return 0},I:Bb,aa:function(){return qb.length},Hd:Vb,Gd:Wb,Yd:function(a,b){M.Ue.beginQueryEXT(a,K[b])},Fd:Xb,Ed:Yb,Cd:Zb,Bd:$b,Ad:ac,Qd:function(a){M.bindVertexArray(Kb[a])},zd:function(a,b,c,d){M.blendColor(a,b,c,d)},yd:function(a){M.blendEquation(a)},xd:function(a,b){M.blendEquationSeparate(a,
b)},wd:bc,vd:function(a,b,c,d){M.blendFuncSeparate(a,b,c,d)},ud:cc,td:dc,sd:ec,rd:fc,qd:gc,pd:hc,od:function(a){M.clearStencil(a)},nd:function(a,b,c,d){M.colorMask(!!a,!!b,!!c,!!d)},md:ic,ld:jc,kd:function(a,b,c,d,e,g,h,m,q){M.compressedTexSubImage2D(a,b,c,d,e,g,h,q?w.subarray(q,q+m):null)},jd:function(a,b,c,d,e,g,h,m){M.copyTexImage2D(a,b,c,d,e,g,h,m)},id:function(a,b,c,d,e,g,h,m){M.copyTexSubImage2D(a,b,c,d,e,g,h,m)},hd:kc,gd:lc,fd:mc,ed:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Gb[d];
e&&(M.deleteBuffer(e),e.name=0,Gb[d]=null)}},dd:nc,cd:oc,$d:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=K[d];e&&(M.Ue.deleteQueryEXT(e),K[d]=null)}},bd:pc,ad:qc,$c:rc,Pd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];M.deleteVertexArray(Kb[d]);Kb[d]=null}},Zc:sc,Yc:function(a){M.depthMask(!!a)},Xc:function(a,b){M.depthRange(a,b)},Wc:tc,Vc:uc,Uc:function(a){M.disableVertexAttribArray(a)},Tc:vc,Kd:function(a,b,c,d){M.drawArraysInstanced(a,b,c,d)},Ld:function(a,b){for(var c=wc[a],d=
0;d<a;d++)c[d]=x[b+4*d>>2];M.drawBuffers(c)},Sc:xc,Jd:function(a,b,c,d,e){M.drawElementsInstanced(a,b,c,d,e)},Rc:yc,Qc:zc,Xd:function(a){M.Ue.endQueryEXT(a)},Oc:function(){M.finish()},Nc:function(){M.flush()},Mc:Ac,Lc:Bc,Kc:Cc,Jc:Ec,Hc:Fc,ae:function(a,b){for(var c=0;c<a;c++){var d=M.Ue.createQueryEXT();if(!d){for(L(1282);c<a;)x[b+4*c++>>2]=0;break}var e=Pb(K);d.name=e;K[e]=d;x[b+4*c>>2]=e}},Gc,Fc:Hc,Nd:function(a,b){Dc(a,b,"createVertexArray",Kb)},Ic:function(a){M.generateMipmap(a)},Dc:function(a,
b,c,d,e,g,h){Ic("getActiveAttrib",a,b,c,d,e,g,h)},Cc:function(a,b,c,d,e,g,h){Ic("getActiveUniform",a,b,c,d,e,g,h)},Bc:function(a,b,c,d){a=M.getAttachedShaders(I[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=J.indexOf(a[b])},Ac:Jc,zc:function(a,b){Lc(a,b,4)},yc:function(a,b,c){c?x[c>>2]=M.getBufferParameter(a,b):L(1281)},xc:function(){var a=M.getError()||Ob;Ob=0;return a},wc:Mc,vc:Nc,uc:function(a,b){Lc(a,b,0)},rc:Oc,sc:Pc,Sd:Qc,Ud:Rc,Rd:Qc,Td:Rc,Vd:function(a,b,c){c?x[c>>2]=
M.Ue.getQueryEXT(a,b):L(1281)},qc:function(a,b,c){c?x[c>>2]=M.getRenderbufferParameter(a,b):L(1281)},oc:Sc,nc:function(a,b,c,d){a=M.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},mc:function(a,b,c,d){if(a=M.getShaderSource(J[a]))b=0<b&&d?D(a,w,d,b):0,c&&(x[c>>2]=b)},pc:Tc,lc:Vc,kc:function(a,b,c){c?A[c>>2]=M.getTexParameter(a,b):L(1281)},jc:function(a,b,c){c?x[c>>2]=M.getTexParameter(a,b):L(1281)},gc:Yc,ic:function(a,b,c){Zc(a,b,c,2)},hc:function(a,b,c){Zc(a,
b,c,0)},dc:function(a,b,c){c?x[c>>2]=M.getVertexAttribOffset(a,b):L(1281)},fc:function(a,b,c){$c(a,b,c,2)},ec:function(a,b,c){$c(a,b,c,5)},cc:function(a,b){M.hint(a,b)},bc:function(a){return(a=Gb[a])?M.isBuffer(a):0},ac:function(a){return M.isEnabled(a)},$b:function(a){return(a=Hb[a])?M.isFramebuffer(a):0},_b:function(a){return(a=I[a])?M.isProgram(a):0},_d:function(a){return(a=K[a])?M.Ue.isQueryEXT(a):0},Zb:function(a){return(a=Ib[a])?M.isRenderbuffer(a):0},Yb:function(a){return(a=J[a])?M.isShader(a):
0},Xb:function(a){return(a=Jb[a])?M.isTexture(a):0},Md:function(a){return(a=Kb[a])?M.isVertexArray(a):0},Wb:function(a){M.lineWidth(a)},Vb:ad,Ub:bd,Tb:function(a,b){M.polygonOffset(a,b)},Wd:function(a,b){M.Ue.queryCounterEXT(K[a],b)},Sb:dd,Rb:function(){},Qb:ed,Pb:function(a,b){M.sampleCoverage(a,!!b)},Ob:fd,Nb:function(){L(1280)},Mb:gd,Lb:function(a,b,c){M.stencilFunc(a,b,c)},Kb:function(a,b,c,d){M.stencilFuncSeparate(a,b,c,d)},Jb:function(a){M.stencilMask(a)},Ib:function(a,b){M.stencilMaskSeparate(a,
b)},Hb:function(a,b,c){M.stencilOp(a,b,c)},Gb:function(a,b,c,d){M.stencilOpSeparate(a,b,c,d)},Fb:hd,Eb:jd,Db:function(a,b,c){M.texParameterf(a,b,A[c>>2])},Cb:kd,Bb:function(a,b,c){M.texParameteri(a,b,x[c>>2])},Ab:function(a,b,c,d,e,g,h,m,q){var r=null;q&&(r=cd(m,h,e,g,q));M.texSubImage2D(a,b,c,d,e,g,h,m,r)},zb:function(a,b){M.uniform1f(O(a),b)},yb:function(a,b,c){if(288>=b)for(var d=P[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);M.uniform1fv(O(a),d)},xb:ld,wb:function(a,b,c){if(288>=
b)for(var d=md[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);M.uniform1iv(O(a),d)},vb:function(a,b,c){M.uniform2f(O(a),b,c)},ub:nd,tb:function(a,b,c){M.uniform2i(O(a),b,c)},sb:function(a,b,c){if(144>=b)for(var d=md[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);M.uniform2iv(O(a),d)},rb:function(a,b,c,d){M.uniform3f(O(a),b,c,d)},qb:function(a,b,c){if(96>=b)for(var d=P[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],
d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);M.uniform3fv(O(a),d)},pb:function(a,b,c,d){M.uniform3i(O(a),b,c,d)},ob:function(a,b,c){if(96>=b)for(var d=md[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);M.uniform3iv(O(a),d)},nb:od,mb:pd,lb:function(a,b,c,d,e){M.uniform4i(O(a),b,c,d,e)},kb:function(a,b,c){if(72>=b)for(var d=md[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=
x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);M.uniform4iv(O(a),d)},jb:function(a,b,c,d){if(72>=b)for(var e=P[4*b-1],g=0;g<4*b;g+=4)e[g]=A[d+4*g>>2],e[g+1]=A[d+(4*g+4)>>2],e[g+2]=A[d+(4*g+8)>>2],e[g+3]=A[d+(4*g+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);M.uniformMatrix2fv(O(a),!!c,e)},ib:function(a,b,c,d){if(32>=b)for(var e=P[9*b-1],g=0;g<9*b;g+=9)e[g]=A[d+4*g>>2],e[g+1]=A[d+(4*g+4)>>2],e[g+2]=A[d+(4*g+8)>>2],e[g+3]=A[d+(4*g+12)>>2],e[g+4]=A[d+(4*g+16)>>2],e[g+5]=A[d+(4*g+20)>>2],e[g+6]=A[d+(4*
g+24)>>2],e[g+7]=A[d+(4*g+28)>>2],e[g+8]=A[d+(4*g+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);M.uniformMatrix3fv(O(a),!!c,e)},hb:qd,gb:rd,fb:function(a){M.validateProgram(I[a])},eb:function(a,b){M.vertexAttrib1f(a,b)},db:function(a,b){M.vertexAttrib1f(a,A[b>>2])},cb:function(a,b,c){M.vertexAttrib2f(a,b,c)},bb:function(a,b){M.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},ab:function(a,b,c,d){M.vertexAttrib3f(a,b,c,d)},$a:function(a,b){M.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},_a:function(a,b,c,d,e){M.vertexAttrib4f(a,
b,c,d,e)},Za:function(a,b){M.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},Id:function(a,b){M.vertexAttribDivisor(a,b)},Ya:sd,Xa:td,Ra:(a,b,c)=>w.copyWithin(a,b,b+c),Oa:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ja.buffer.byteLength+65535>>>16;try{ja.grow(e);oa();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},da:a=>{eval(a?
C(w,a):"")},ba:function(){return(qb=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},ce:function(a,b,c){a=yb(a);if(!a)return-4;a.width=b;a.height=c;return 0},na:function(a,b,c,d){return ud(a,b,c,d)},pa:function(a,b,c,d){if(!document.fullscreenEnabled&&!document.webkitFullscreenEnabled)return-1;a=yb(a);if(!a)return-4;wd(a,b,c,d,"webkitfullscreenchange");return wd(a,b,c,d,"fullscreenchange")},ia:function(a,b,c){return navigator.getGamepads||
navigator.webkitGetGamepads?xd(a,b,c,26,"gamepadconnected"):-1},ha:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?xd(a,b,c,27,"gamepaddisconnected"):-1},oa:function(a,b,c,d){return yd(a,b,c,d)},ja:function(a,b,c,d){return zd(a,b,c,d,25,"touchcancel")},la:function(a,b,c,d){return zd(a,b,c,d,23,"touchend")},ka:function(a,b,c,d){return zd(a,b,c,d,24,"touchmove")},ma:function(a,b,c,d){return zd(a,b,c,d,22,"touchstart")},ea:function(a){fa(a?C(w,a):"")},fa:function(a){return df(b=>
Rd(b,a))},ie:a=>{ka=a;Qd(a)},J:function(a){try{var b=F.Pe(a);F.close(b);return 0}catch(c){if("undefined"==typeof F||"ErrnoError"!==c.name)throw c;return c.Ne}},Ta:function(a,b,c,d){try{a:{var e=F.Pe(a);a=b;for(var g,h=b=0;h<c;h++){var m=y[a>>2],q=y[a+4>>2];a+=8;var r=F.read(e,u,m,q,g);if(0>r){var v=-1;break a}b+=r;if(r<q)break;"undefined"!==typeof g&&(g+=r)}v=b}y[d>>2]=v;return 0}catch(t){if("undefined"==typeof F||"ErrnoError"!==t.name)throw t;return t.Ne}},Pa:function(a,b,c,d){b=-9007199254740992>
b||9007199254740992<b?NaN:Number(b);d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);try{if(isNaN(b))return 61;var e=F.Pe(a);F.Re(e,b,c);na[d>>3]=BigInt(e.position);e.eg&&0===b&&0===c&&(e.eg=null);return 0}catch(g){if("undefined"==typeof F||"ErrnoError"!==g.name)throw g;return g.Ne}},Sa:function(a,b,c,d){try{a:{var e=F.Pe(a);a=b;for(var g,h=b=0;h<c;h++){var m=y[a>>2],q=y[a+4>>2];a+=8;var r=F.write(e,u,m,q,g);if(0>r){var v=-1;break a}b+=r;"undefined"!==typeof g&&(g+=r)}v=b}y[d>>2]=v;return 0}catch(t){if("undefined"==
typeof F||"ErrnoError"!==t.name)throw t;return t.Ne}},H:Vb,y:Wb,l:Xb,a:Yb,c:Zb,F:$b,i:ac,_c:bc,o:cc,m:dc,Ca:ec,L:fc,M:gc,tc:hc,wa:ic,Ga:jc,ua:kc,ya:lc,Zd:mc,Aa:nc,ra:oc,Ba:pc,A:qc,K:rc,Pc:sc,B:tc,N:uc,G:vc,Ka:xc,t:yc,j:zc,D:Ac,r:Bc,Ec:Cc,p:Ec,E:Fc,Fa:Gc,Ia:Hc,h:Jc,Dd:Mc,C:Nc,sa:Oc,x:Pc,va:Sc,z:Tc,q:Vc,b:Yc,ta:ad,Ja:bd,Da:dd,Ea:ed,Od:fd,xa:gd,Ha:hd,za:jd,n:kd,La:ld,u:nd,Ma:od,qa:pd,Na:qd,k:rd,d:sd,s:td,v:function(a,b,c,d){var e;for(e=0;e<U.length&&null!==U[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";
var g=e+1;if(0>=a||0>=b)g=0;else{d?be():me(a,b);for(e=0;e<U.length&&null==U[e];e++);d=0<S[139265];e==U.length&&(d?f.pf=Yd(f.canvas,!0,!0,{antialias:1<S[135181],depth:0<S[135173],stencil:0<S[135174],alpha:0<S[135172]}):eb());!f.pf&&d?g=0:(a=new ne(g,a,b,c),g-1==U.length?U.push(a):U[g-1]=a,V=a,g=a.id)}return g},W:function(){S=re},w:function(){return 1},g:function(){return Bb()/1E3-qe},V:function(a,b){return x[b>>2]=0},X:function(){if(U)return 1;qe=Bb()/1E3;S=re;U=[];V=null;pe=devicePixelRatio;window.addEventListener("gamepadconnected",
xe,!0);window.addEventListener("gamepaddisconnected",ze,!0);window.addEventListener("keydown",Ae,!0);window.addEventListener("keypress",ue,!0);window.addEventListener("keyup",Ce,!0);window.addEventListener("blur",De,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});pe=devicePixelRatio;V&&V.Pg&&lf.apply(null,[V.Pg,V.id,pe,pe])})();f.canvas.addEventListener("touchmove",Ee,!0);f.canvas.addEventListener("touchstart",Ke,!0);f.canvas.addEventListener("touchcancel",
Le,!0);f.canvas.addEventListener("touchend",Le,!0);f.canvas.addEventListener("mousemove",Ee,!0);f.canvas.addEventListener("mousedown",Ke,!0);f.canvas.addEventListener("mouseup",Le,!0);f.canvas.addEventListener("wheel",Me,!0);f.canvas.addEventListener("mousewheel",Me,!0);f.canvas.addEventListener("mouseenter",Ge,!0);f.canvas.addEventListener("mouseleave",He,!0);f.canvas.addEventListener("drop",Qe,!0);f.canvas.addEventListener("dragover",Se,!0);le.push((b,c)=>{if(V){var d=!0;document.fullscreen||document.fullScreen||
document.mozFullScreen||document.webkitIsFullScreen?(V.Kg=V.x,V.Lg=V.y,V.Jg=V.width,V.Ig=V.height,V.x=V.y=0,V.width=screen.width,V.height=screen.height,V.cg=!0):1==V.cg?(V.x=V.Kg,V.y=V.Lg,V.width=V.Jg,V.height=V.Ig,V.cg=!1):V.width!=b||V.height!=c?(V.width=b,V.height=c):d=!1;d&&(me(V.width,V.height,!0),V&&V.Uf&&Re.apply(null,[V.Uf,V.id,V.width,V.height]),V&&V.yg&&Re.apply(null,[V.yg,V.id,V.width,V.height]))}});return 1},ee:function(){},P:function(a,b){if(a=T(a)){var c=a.Df;a.Df=b;b=c}else b=null;
return b},fe:function(a,b){a=T(a);if(!a)return null;var c=a.jf;a.jf=b;return c},he:function(a,b){if(a=T(a)){var c=a.qf;a.qf=b;b=c}else b=null;return b},R:function(a,b){if(a=T(a)){var c=a.rf;a.rf=b;b=c}else b=null;return b},Y:function(a){var b=oe;oe=a;return b},Q:function(a,b){if(a=T(a)){var c=a.Kf;a.Kf=b;b=c}else b=null;return b},O:function(a,b){if(a=T(a)){var c=a.Qf;a.Qf=b;b=c}else b=null;return b},ge:function(a,b){if(a=T(a)){var c=a.Sf;a.Sf=b;b=c}else b=null;return b},S:function(a,b){a=T(a);if(!a)return null;
var c=a.Qg;a.Qg=b;return c},T:function(a,b){a=T(a);if(!a)return null;var c=a.Rg;a.Rg=b;return c},de:function(a,b){if(a=T(a))a.Eh=b},U:function(a,b){if(a=T(a)){var c=a.Uf;a.Uf=b;b=c}else b=null;return b},ca:function(){},ga:function(){window.removeEventListener("gamepadconnected",xe,!0);window.removeEventListener("gamepaddisconnected",ze,!0);window.removeEventListener("keydown",Ae,!0);window.removeEventListener("keypress",ue,!0);window.removeEventListener("keyup",Ce,!0);window.removeEventListener("blur",
De,!0);f.canvas.removeEventListener("touchmove",Ee,!0);f.canvas.removeEventListener("touchstart",Ke,!0);f.canvas.removeEventListener("touchcancel",Le,!0);f.canvas.removeEventListener("touchend",Le,!0);f.canvas.removeEventListener("mousemove",Ee,!0);f.canvas.removeEventListener("mousedown",Ke,!0);f.canvas.removeEventListener("mouseup",Le,!0);f.canvas.removeEventListener("wheel",Me,!0);f.canvas.removeEventListener("mousewheel",Me,!0);f.canvas.removeEventListener("mouseenter",Ge,!0);f.canvas.removeEventListener("mouseleave",
He,!0);f.canvas.removeEventListener("drop",Qe,!0);f.canvas.removeEventListener("dragover",Se,!0);f.canvas.width=f.canvas.height=1;V=U=null},f:function(a,b){S[a]=b}};(function(){function a(c){c=c.exports;n=c=Ue(c);ja=n.je;oa();qa.unshift(n.ke);za("wasm-instantiate");return c}var b={a:mf};ya("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}Ga(b,function(c){a(c.instance)});return{}})();
var Pe=a=>(Pe=n.le)(a),N=a=>(N=n.me)(a),nf=f._main=(a,b)=>(nf=f._main=n.ne)(a,b),vd=f.dynCall_iiii=(a,b,c,d)=>(vd=f.dynCall_iiii=n.pe)(a,b,c,d),dynCall_vii=f.dynCall_vii=(a,b,c)=>(dynCall_vii=f.dynCall_vii=n.qe)(a,b,c),Re=f.dynCall_viii=(a,b,c,d)=>(Re=f.dynCall_viii=n.re)(a,b,c,d),we=f.dynCall_viiiii=(a,b,c,d,e,g)=>(we=f.dynCall_viiiii=n.se)(a,b,c,d,e,g),Je=f.dynCall_viiii=(a,b,c,d,e)=>(Je=f.dynCall_viiii=n.te)(a,b,c,d,e),Fe=f.dynCall_vidd=(a,b,c,d)=>(Fe=f.dynCall_vidd=n.ue)(a,b,c,d),dynCall_vi=f.dynCall_vi=
(a,b)=>(dynCall_vi=f.dynCall_vi=n.ve)(a,b),lf=f.dynCall_viff=(a,b,c,d)=>(lf=f.dynCall_viff=n.we)(a,b,c,d),ff=a=>(ff=n.xe)(a),We=()=>(We=n.ye)(),ef=a=>(ef=n.ze)(a),gf=()=>(gf=n.Ae)();f.___start_em_js=55312;f.___stop_em_js=55385;f.addRunDependency=ya;f.removeRunDependency=za;f.FS_createPath=F.Yf;f.FS_createDataFile=F.Xf;f.FS_createLazyFile=F.rg;f.FS_createDevice=F.Me;f.FS_unlink=F.hf;f.FS_createPreloadedFile=F.sg;f.FS=F;var pf;xa=function qf(){pf||rf();pf||(xa=qf)};
function rf(){function a(){if(!pf&&(pf=!0,f.calledRun=!0,!p)){f.noFSInit||F.Hf.gg||F.Hf();F.Dg=!1;Ia(qa);Ia(ra);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(sf){var b=nf;try{var c=b(0,0);ka=c;Qd(c)}catch(d){Pd(d)}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),ta.unshift(b);Ia(ta)}}if(!(0<va)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ua();Ia(pa);0<va||(f.setStatus?(f.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var sf=!0;f.noInitialRun&&(sf=!1);rf();
